set_directive_bind_op -op mul -impl fabric "case_75" m8
set_directive_bind_op -op mul -impl fabric "case_75" m9
set_directive_bind_op -op mul -impl fabric "case_75" m10
set_directive_bind_op -op mul -impl fabric "case_75" m11
set_directive_bind_op -op mul -impl fabric "case_75" m12
set_directive_bind_op -op mul -impl fabric "case_75" m13
set_directive_bind_op -op mul -impl fabric "case_75" m14
set_directive_bind_op -op mul -impl fabric "case_75" m15
set_directive_bind_op -op mul -impl fabric "case_75" m16
set_directive_bind_op -op mul -impl fabric "case_75" m17
set_directive_bind_op -op mul -impl fabric "case_75" m18
set_directive_bind_op -op mul -impl fabric "case_75" m19
set_directive_bind_op -op mul -impl fabric "case_75" m20
set_directive_bind_op -op mul -impl fabric "case_75" m21
set_directive_bind_op -op mul -impl fabric "case_75" m22
set_directive_bind_op -op mul -impl fabric "case_75" m23
set_directive_bind_op -op mul -impl fabric "case_75" m24
set_directive_bind_op -op mul -impl fabric "case_75" m25
set_directive_bind_op -op mul -impl fabric "case_75" m26
set_directive_bind_op -op mul -impl fabric "case_75" m27
set_directive_bind_op -op mul -impl fabric "case_75" m28
set_directive_bind_op -op mul -impl fabric "case_75" m29
set_directive_bind_op -op mul -impl fabric "case_75" m30
set_directive_bind_op -op mul -impl fabric "case_75" m31
set_directive_bind_op -op mul -impl fabric "case_75" m32
set_directive_bind_op -op mul -impl fabric "case_75" m33
set_directive_bind_op -op mul -impl fabric "case_75" m34
set_directive_bind_op -op mul -impl fabric "case_75" m35
set_directive_bind_op -op mul -impl fabric "case_75" m36
set_directive_bind_op -op mul -impl fabric "case_75" m37
set_directive_bind_op -op mul -impl fabric "case_75" m38
set_directive_bind_op -op mul -impl fabric "case_75" m39
set_directive_bind_op -op mul -impl fabric "case_75" m40
set_directive_bind_op -op mul -impl fabric "case_75" m41
set_directive_bind_op -op mul -impl fabric "case_75" m42
set_directive_bind_op -op mul -impl fabric "case_75" m43
set_directive_bind_op -op mul -impl fabric "case_75" m44
set_directive_bind_op -op mul -impl fabric "case_75" m45
set_directive_bind_op -op mul -impl fabric "case_75" m46
set_directive_bind_op -op mul -impl fabric "case_75" m47
set_directive_bind_op -op mul -impl fabric "case_75" m48
set_directive_bind_op -op mul -impl fabric "case_75" m49
set_directive_bind_op -op mul -impl fabric "case_75" m50
set_directive_bind_op -op mul -impl fabric "case_75" m51
set_directive_bind_op -op mul -impl fabric "case_75" m52
set_directive_bind_op -op mul -impl fabric "case_75" m53
set_directive_bind_op -op mul -impl fabric "case_75" m54
set_directive_bind_op -op mul -impl fabric "case_75" m55
set_directive_bind_op -op mul -impl fabric "case_75" m56
set_directive_bind_op -op mul -impl fabric "case_75" m57
set_directive_bind_op -op mul -impl fabric "case_75" m58
set_directive_bind_op -op mul -impl fabric "case_75" m59
set_directive_bind_op -op mul -impl fabric "case_75" m60
set_directive_bind_op -op mul -impl fabric "case_75" m61
set_directive_bind_op -op mul -impl fabric "case_75" m62
set_directive_bind_op -op mul -impl fabric "case_75" m63
set_directive_bind_op -op mul -impl fabric "case_75" m64
set_directive_bind_op -op mul -impl fabric "case_75" m65
set_directive_bind_op -op mul -impl fabric "case_75" m66
set_directive_bind_op -op mul -impl fabric "case_75" m67
set_directive_bind_op -op mul -impl fabric "case_75" m68
set_directive_bind_op -op mul -impl fabric "case_75" m69
set_directive_bind_op -op mul -impl fabric "case_75" m70
set_directive_bind_op -op mul -impl fabric "case_75" m71
set_directive_bind_op -op mul -impl fabric "case_75" m72

