set_directive_bind_op -op mul -impl fabric "case_21" m19
set_directive_bind_op -op mul -impl fabric "case_21" m20
set_directive_bind_op -op mul -impl fabric "case_21" m21
set_directive_bind_op -op mul -impl fabric "case_21" m22
set_directive_bind_op -op mul -impl fabric "case_21" m23
set_directive_bind_op -op mul -impl fabric "case_21" m24
set_directive_bind_op -op mul -impl fabric "case_21" m25
set_directive_bind_op -op mul -impl fabric "case_21" m26
set_directive_bind_op -op mul -impl fabric "case_21" m27
set_directive_bind_op -op mul -impl fabric "case_21" m28
set_directive_bind_op -op mul -impl fabric "case_21" m29
set_directive_bind_op -op mul -impl fabric "case_21" m30
set_directive_bind_op -op mul -impl fabric "case_21" m31
set_directive_bind_op -op mul -impl fabric "case_21" m32
set_directive_bind_op -op mul -impl fabric "case_21" m33
set_directive_bind_op -op mul -impl fabric "case_21" m34
set_directive_bind_op -op mul -impl fabric "case_21" m35
set_directive_bind_op -op mul -impl fabric "case_21" m36
set_directive_bind_op -op mul -impl fabric "case_21" m37
set_directive_bind_op -op mul -impl fabric "case_21" m38
set_directive_bind_op -op mul -impl fabric "case_21" m39
set_directive_bind_op -op mul -impl fabric "case_21" m40
set_directive_bind_op -op mul -impl fabric "case_21" m41
set_directive_bind_op -op mul -impl fabric "case_21" m42
set_directive_bind_op -op mul -impl fabric "case_21" m43
set_directive_bind_op -op mul -impl fabric "case_21" m44
set_directive_bind_op -op mul -impl fabric "case_21" m45
set_directive_bind_op -op mul -impl fabric "case_21" m46
set_directive_bind_op -op mul -impl fabric "case_21" m47
set_directive_bind_op -op mul -impl fabric "case_21" m48
set_directive_bind_op -op mul -impl fabric "case_21" m49
set_directive_bind_op -op mul -impl fabric "case_21" m50
set_directive_bind_op -op mul -impl fabric "case_21" m51
set_directive_bind_op -op mul -impl fabric "case_21" m52
set_directive_bind_op -op mul -impl fabric "case_21" m53
set_directive_bind_op -op mul -impl fabric "case_21" m54
set_directive_bind_op -op mul -impl fabric "case_21" m55
set_directive_bind_op -op mul -impl fabric "case_21" m56
set_directive_bind_op -op mul -impl fabric "case_21" m57
set_directive_bind_op -op mul -impl fabric "case_21" m58
set_directive_bind_op -op mul -impl fabric "case_21" m59
set_directive_bind_op -op mul -impl fabric "case_21" m60

