set_directive_bind_op -op mul -impl fabric "case_88" m7
set_directive_bind_op -op mul -impl fabric "case_88" m8
set_directive_bind_op -op mul -impl fabric "case_88" m9
set_directive_bind_op -op mul -impl fabric "case_88" m10
set_directive_bind_op -op mul -impl fabric "case_88" m11
set_directive_bind_op -op mul -impl fabric "case_88" m12
set_directive_bind_op -op mul -impl fabric "case_88" m13
set_directive_bind_op -op mul -impl fabric "case_88" m14
set_directive_bind_op -op mul -impl fabric "case_88" m15
set_directive_bind_op -op mul -impl fabric "case_88" m16
set_directive_bind_op -op mul -impl fabric "case_88" m17
set_directive_bind_op -op mul -impl fabric "case_88" m18
set_directive_bind_op -op mul -impl fabric "case_88" m19
set_directive_bind_op -op mul -impl fabric "case_88" m20
set_directive_bind_op -op mul -impl fabric "case_88" m21
set_directive_bind_op -op mul -impl fabric "case_88" m22
set_directive_bind_op -op mul -impl fabric "case_88" m23
set_directive_bind_op -op mul -impl fabric "case_88" m24
set_directive_bind_op -op mul -impl fabric "case_88" m25
set_directive_bind_op -op mul -impl fabric "case_88" m26
set_directive_bind_op -op mul -impl fabric "case_88" m27
set_directive_bind_op -op mul -impl fabric "case_88" m28
set_directive_bind_op -op mul -impl fabric "case_88" m29
set_directive_bind_op -op mul -impl fabric "case_88" m30
set_directive_bind_op -op mul -impl fabric "case_88" m31
set_directive_bind_op -op mul -impl fabric "case_88" m32
set_directive_bind_op -op mul -impl fabric "case_88" m33
set_directive_bind_op -op mul -impl fabric "case_88" m34
set_directive_bind_op -op mul -impl fabric "case_88" m35
set_directive_bind_op -op mul -impl fabric "case_88" m36
set_directive_bind_op -op mul -impl fabric "case_88" m37
set_directive_bind_op -op mul -impl fabric "case_88" m38
set_directive_bind_op -op mul -impl fabric "case_88" m39
set_directive_bind_op -op mul -impl fabric "case_88" m40

