set_directive_bind_op -op mul -impl fabric "case_72" m30
set_directive_bind_op -op mul -impl fabric "case_72" m31
set_directive_bind_op -op mul -impl fabric "case_72" m32
set_directive_bind_op -op mul -impl fabric "case_72" m33
set_directive_bind_op -op mul -impl fabric "case_72" m34
set_directive_bind_op -op mul -impl fabric "case_72" m35
set_directive_bind_op -op mul -impl fabric "case_72" m36
set_directive_bind_op -op mul -impl fabric "case_72" m37
set_directive_bind_op -op mul -impl fabric "case_72" m38
set_directive_bind_op -op mul -impl fabric "case_72" m39
set_directive_bind_op -op mul -impl fabric "case_72" m40
set_directive_bind_op -op mul -impl fabric "case_72" m41
set_directive_bind_op -op mul -impl fabric "case_72" m42
set_directive_bind_op -op mul -impl fabric "case_72" m43
set_directive_bind_op -op mul -impl fabric "case_72" m44
set_directive_bind_op -op mul -impl fabric "case_72" m45
set_directive_bind_op -op mul -impl fabric "case_72" m46
set_directive_bind_op -op mul -impl fabric "case_72" m47
set_directive_bind_op -op mul -impl fabric "case_72" m48
set_directive_bind_op -op mul -impl fabric "case_72" m49
set_directive_bind_op -op mul -impl fabric "case_72" m50
set_directive_bind_op -op mul -impl fabric "case_72" m51
set_directive_bind_op -op mul -impl fabric "case_72" m52
set_directive_bind_op -op mul -impl fabric "case_72" m53
set_directive_bind_op -op mul -impl fabric "case_72" m54
set_directive_bind_op -op mul -impl fabric "case_72" m55
set_directive_bind_op -op mul -impl fabric "case_72" m56
set_directive_bind_op -op mul -impl fabric "case_72" m57
set_directive_bind_op -op mul -impl fabric "case_72" m58
set_directive_bind_op -op mul -impl fabric "case_72" m59
set_directive_bind_op -op mul -impl fabric "case_72" m60
set_directive_bind_op -op mul -impl fabric "case_72" m61
set_directive_bind_op -op mul -impl fabric "case_72" m62
set_directive_bind_op -op mul -impl fabric "case_72" m63
set_directive_bind_op -op mul -impl fabric "case_72" m64
set_directive_bind_op -op mul -impl fabric "case_72" m65
set_directive_bind_op -op mul -impl fabric "case_72" m66
set_directive_bind_op -op mul -impl fabric "case_72" m67
set_directive_bind_op -op mul -impl fabric "case_72" m68
set_directive_bind_op -op mul -impl fabric "case_72" m69
set_directive_bind_op -op mul -impl fabric "case_72" m70
set_directive_bind_op -op mul -impl fabric "case_72" m71
set_directive_bind_op -op mul -impl fabric "case_72" m72
set_directive_bind_op -op mul -impl fabric "case_72" m73
set_directive_bind_op -op mul -impl fabric "case_72" m74
set_directive_bind_op -op mul -impl fabric "case_72" m75
set_directive_bind_op -op mul -impl fabric "case_72" m76
set_directive_bind_op -op mul -impl fabric "case_72" m77
set_directive_bind_op -op mul -impl fabric "case_72" m78
set_directive_bind_op -op mul -impl fabric "case_72" m79
set_directive_bind_op -op mul -impl fabric "case_72" m80
set_directive_bind_op -op mul -impl fabric "case_72" m81
set_directive_bind_op -op mul -impl fabric "case_72" m82
set_directive_bind_op -op mul -impl fabric "case_72" m83
set_directive_bind_op -op mul -impl fabric "case_72" m84
set_directive_bind_op -op mul -impl fabric "case_72" m85
set_directive_bind_op -op mul -impl fabric "case_72" m86
set_directive_bind_op -op mul -impl fabric "case_72" m87
set_directive_bind_op -op mul -impl fabric "case_72" m88
set_directive_bind_op -op mul -impl fabric "case_72" m89
set_directive_bind_op -op mul -impl fabric "case_72" m90
set_directive_bind_op -op mul -impl fabric "case_72" m91
set_directive_bind_op -op mul -impl fabric "case_72" m92
set_directive_bind_op -op mul -impl fabric "case_72" m93
set_directive_bind_op -op mul -impl fabric "case_72" m94
set_directive_bind_op -op mul -impl fabric "case_72" m95
set_directive_bind_op -op mul -impl fabric "case_72" m96
set_directive_bind_op -op mul -impl fabric "case_72" m97
set_directive_bind_op -op mul -impl fabric "case_72" m98
set_directive_bind_op -op mul -impl fabric "case_72" m99
set_directive_bind_op -op mul -impl fabric "case_72" m100
set_directive_bind_op -op mul -impl fabric "case_72" m101
set_directive_bind_op -op mul -impl fabric "case_72" m102
set_directive_bind_op -op mul -impl fabric "case_72" m103
set_directive_bind_op -op mul -impl fabric "case_72" m104
set_directive_bind_op -op mul -impl fabric "case_72" m105
set_directive_bind_op -op mul -impl fabric "case_72" m106
set_directive_bind_op -op mul -impl fabric "case_72" m107
set_directive_bind_op -op mul -impl fabric "case_72" m108
set_directive_bind_op -op mul -impl fabric "case_72" m109
set_directive_bind_op -op mul -impl fabric "case_72" m110
set_directive_bind_op -op mul -impl fabric "case_72" m111
set_directive_bind_op -op mul -impl fabric "case_72" m112
set_directive_bind_op -op mul -impl fabric "case_72" m113
set_directive_bind_op -op mul -impl fabric "case_72" m114
set_directive_bind_op -op mul -impl fabric "case_72" m115
set_directive_bind_op -op mul -impl fabric "case_72" m116
set_directive_bind_op -op mul -impl fabric "case_72" m117
set_directive_bind_op -op mul -impl fabric "case_72" m118
set_directive_bind_op -op mul -impl fabric "case_72" m119
set_directive_bind_op -op mul -impl fabric "case_72" m120
set_directive_bind_op -op mul -impl fabric "case_72" m121
set_directive_bind_op -op mul -impl fabric "case_72" m122
set_directive_bind_op -op mul -impl fabric "case_72" m123
set_directive_bind_op -op mul -impl fabric "case_72" m124
set_directive_bind_op -op mul -impl fabric "case_72" m125
set_directive_bind_op -op mul -impl fabric "case_72" m126
set_directive_bind_op -op mul -impl fabric "case_72" m127
set_directive_bind_op -op mul -impl fabric "case_72" m128
set_directive_bind_op -op mul -impl fabric "case_72" m129
set_directive_bind_op -op mul -impl fabric "case_72" m130
set_directive_bind_op -op mul -impl fabric "case_72" m131
set_directive_bind_op -op mul -impl fabric "case_72" m132
set_directive_bind_op -op mul -impl fabric "case_72" m133

