set_directive_bind_op -op mul -impl fabric "case_58" m23
set_directive_bind_op -op mul -impl fabric "case_58" m24
set_directive_bind_op -op mul -impl fabric "case_58" m25
set_directive_bind_op -op mul -impl fabric "case_58" m26
set_directive_bind_op -op mul -impl fabric "case_58" m27
set_directive_bind_op -op mul -impl fabric "case_58" m28
set_directive_bind_op -op mul -impl fabric "case_58" m29
set_directive_bind_op -op mul -impl fabric "case_58" m30
set_directive_bind_op -op mul -impl fabric "case_58" m31
set_directive_bind_op -op mul -impl fabric "case_58" m32
set_directive_bind_op -op mul -impl fabric "case_58" m33
set_directive_bind_op -op mul -impl fabric "case_58" m34
set_directive_bind_op -op mul -impl fabric "case_58" m35
set_directive_bind_op -op mul -impl fabric "case_58" m36
set_directive_bind_op -op mul -impl fabric "case_58" m37
set_directive_bind_op -op mul -impl fabric "case_58" m38
set_directive_bind_op -op mul -impl fabric "case_58" m39
set_directive_bind_op -op mul -impl fabric "case_58" m40
set_directive_bind_op -op mul -impl fabric "case_58" m41
set_directive_bind_op -op mul -impl fabric "case_58" m42
set_directive_bind_op -op mul -impl fabric "case_58" m43
set_directive_bind_op -op mul -impl fabric "case_58" m44
set_directive_bind_op -op mul -impl fabric "case_58" m45
set_directive_bind_op -op mul -impl fabric "case_58" m46
set_directive_bind_op -op mul -impl fabric "case_58" m47
set_directive_bind_op -op mul -impl fabric "case_58" m48
set_directive_bind_op -op mul -impl fabric "case_58" m49
set_directive_bind_op -op mul -impl fabric "case_58" m50
set_directive_bind_op -op mul -impl fabric "case_58" m51
set_directive_bind_op -op mul -impl fabric "case_58" m52
set_directive_bind_op -op mul -impl fabric "case_58" m53
set_directive_bind_op -op mul -impl fabric "case_58" m54
set_directive_bind_op -op mul -impl fabric "case_58" m55
set_directive_bind_op -op mul -impl fabric "case_58" m56
set_directive_bind_op -op mul -impl fabric "case_58" m57
set_directive_bind_op -op mul -impl fabric "case_58" m58
set_directive_bind_op -op mul -impl fabric "case_58" m59
set_directive_bind_op -op mul -impl fabric "case_58" m60
set_directive_bind_op -op mul -impl fabric "case_58" m61
set_directive_bind_op -op mul -impl fabric "case_58" m62
set_directive_bind_op -op mul -impl fabric "case_58" m63
set_directive_bind_op -op mul -impl fabric "case_58" m64
set_directive_bind_op -op mul -impl fabric "case_58" m65
set_directive_bind_op -op mul -impl fabric "case_58" m66
set_directive_bind_op -op mul -impl fabric "case_58" m67
set_directive_bind_op -op mul -impl fabric "case_58" m68
set_directive_bind_op -op mul -impl fabric "case_58" m69
set_directive_bind_op -op mul -impl fabric "case_58" m70
set_directive_bind_op -op mul -impl fabric "case_58" m71
set_directive_bind_op -op mul -impl fabric "case_58" m72
set_directive_bind_op -op mul -impl fabric "case_58" m73
set_directive_bind_op -op mul -impl fabric "case_58" m74
set_directive_bind_op -op mul -impl fabric "case_58" m75
set_directive_bind_op -op mul -impl fabric "case_58" m76
set_directive_bind_op -op mul -impl fabric "case_58" m77
set_directive_bind_op -op mul -impl fabric "case_58" m78
set_directive_bind_op -op mul -impl fabric "case_58" m79
set_directive_bind_op -op mul -impl fabric "case_58" m80
set_directive_bind_op -op mul -impl fabric "case_58" m81
set_directive_bind_op -op mul -impl fabric "case_58" m82
set_directive_bind_op -op mul -impl fabric "case_58" m83
set_directive_bind_op -op mul -impl fabric "case_58" m84
set_directive_bind_op -op mul -impl fabric "case_58" m85
set_directive_bind_op -op mul -impl fabric "case_58" m86
set_directive_bind_op -op mul -impl fabric "case_58" m87
set_directive_bind_op -op mul -impl fabric "case_58" m88
set_directive_bind_op -op mul -impl fabric "case_58" m89
set_directive_bind_op -op mul -impl fabric "case_58" m90
set_directive_bind_op -op mul -impl fabric "case_58" m91
set_directive_bind_op -op mul -impl fabric "case_58" m92
set_directive_bind_op -op mul -impl fabric "case_58" m93
set_directive_bind_op -op mul -impl fabric "case_58" m94
set_directive_bind_op -op mul -impl fabric "case_58" m95
set_directive_bind_op -op mul -impl fabric "case_58" m96
set_directive_bind_op -op mul -impl fabric "case_58" m97
set_directive_bind_op -op mul -impl fabric "case_58" m98
set_directive_bind_op -op mul -impl fabric "case_58" m99
set_directive_bind_op -op mul -impl fabric "case_58" m100
set_directive_bind_op -op mul -impl fabric "case_58" m101
set_directive_bind_op -op mul -impl fabric "case_58" m102
set_directive_bind_op -op mul -impl fabric "case_58" m103
set_directive_bind_op -op mul -impl fabric "case_58" m104
set_directive_bind_op -op mul -impl fabric "case_58" m105
set_directive_bind_op -op mul -impl fabric "case_58" m106
set_directive_bind_op -op mul -impl fabric "case_58" m107
set_directive_bind_op -op mul -impl fabric "case_58" m108
set_directive_bind_op -op mul -impl fabric "case_58" m109
set_directive_bind_op -op mul -impl fabric "case_58" m110
set_directive_bind_op -op mul -impl fabric "case_58" m111
set_directive_bind_op -op mul -impl fabric "case_58" m112
set_directive_bind_op -op mul -impl fabric "case_58" m113
set_directive_bind_op -op mul -impl fabric "case_58" m114
set_directive_bind_op -op mul -impl fabric "case_58" m115
set_directive_bind_op -op mul -impl fabric "case_58" m116

