set_directive_bind_op -op mul -impl fabric "case_92" m12
set_directive_bind_op -op mul -impl fabric "case_92" m13
set_directive_bind_op -op mul -impl fabric "case_92" m14
set_directive_bind_op -op mul -impl fabric "case_92" m15
set_directive_bind_op -op mul -impl fabric "case_92" m16
set_directive_bind_op -op mul -impl fabric "case_92" m17
set_directive_bind_op -op mul -impl fabric "case_92" m18
set_directive_bind_op -op mul -impl fabric "case_92" m19
set_directive_bind_op -op mul -impl fabric "case_92" m20
set_directive_bind_op -op mul -impl fabric "case_92" m21
set_directive_bind_op -op mul -impl fabric "case_92" m22
set_directive_bind_op -op mul -impl fabric "case_92" m23
set_directive_bind_op -op mul -impl fabric "case_92" m24
set_directive_bind_op -op mul -impl fabric "case_92" m25
set_directive_bind_op -op mul -impl fabric "case_92" m26
set_directive_bind_op -op mul -impl fabric "case_92" m27
set_directive_bind_op -op mul -impl fabric "case_92" m28
set_directive_bind_op -op mul -impl fabric "case_92" m29
set_directive_bind_op -op mul -impl fabric "case_92" m30
set_directive_bind_op -op mul -impl fabric "case_92" m31
set_directive_bind_op -op mul -impl fabric "case_92" m32
set_directive_bind_op -op mul -impl fabric "case_92" m33
set_directive_bind_op -op mul -impl fabric "case_92" m34
set_directive_bind_op -op mul -impl fabric "case_92" m35
set_directive_bind_op -op mul -impl fabric "case_92" m36
set_directive_bind_op -op mul -impl fabric "case_92" m37
set_directive_bind_op -op mul -impl fabric "case_92" m38
set_directive_bind_op -op mul -impl fabric "case_92" m39
set_directive_bind_op -op mul -impl fabric "case_92" m40
set_directive_bind_op -op mul -impl fabric "case_92" m41
set_directive_bind_op -op mul -impl fabric "case_92" m42
set_directive_bind_op -op mul -impl fabric "case_92" m43
set_directive_bind_op -op mul -impl fabric "case_92" m44
set_directive_bind_op -op mul -impl fabric "case_92" m45
set_directive_bind_op -op mul -impl fabric "case_92" m46
set_directive_bind_op -op mul -impl fabric "case_92" m47
set_directive_bind_op -op mul -impl fabric "case_92" m48
set_directive_bind_op -op mul -impl fabric "case_92" m49
set_directive_bind_op -op mul -impl fabric "case_92" m50
set_directive_bind_op -op mul -impl fabric "case_92" m51
set_directive_bind_op -op mul -impl fabric "case_92" m52
set_directive_bind_op -op mul -impl fabric "case_92" m53
set_directive_bind_op -op mul -impl fabric "case_92" m54
set_directive_bind_op -op mul -impl fabric "case_92" m55
set_directive_bind_op -op mul -impl fabric "case_92" m56
set_directive_bind_op -op mul -impl fabric "case_92" m57
set_directive_bind_op -op mul -impl fabric "case_92" m58
set_directive_bind_op -op mul -impl fabric "case_92" m59
set_directive_bind_op -op mul -impl fabric "case_92" m60
set_directive_bind_op -op mul -impl fabric "case_92" m61
set_directive_bind_op -op mul -impl fabric "case_92" m62
set_directive_bind_op -op mul -impl fabric "case_92" m63
set_directive_bind_op -op mul -impl fabric "case_92" m64

