set_directive_bind_op -op mul -impl fabric "case_80" m27
set_directive_bind_op -op mul -impl fabric "case_80" m28
set_directive_bind_op -op mul -impl fabric "case_80" m29
set_directive_bind_op -op mul -impl fabric "case_80" m30
set_directive_bind_op -op mul -impl fabric "case_80" m31
set_directive_bind_op -op mul -impl fabric "case_80" m32
set_directive_bind_op -op mul -impl fabric "case_80" m33
set_directive_bind_op -op mul -impl fabric "case_80" m34
set_directive_bind_op -op mul -impl fabric "case_80" m35
set_directive_bind_op -op mul -impl fabric "case_80" m36
set_directive_bind_op -op mul -impl fabric "case_80" m37
set_directive_bind_op -op mul -impl fabric "case_80" m38
set_directive_bind_op -op mul -impl fabric "case_80" m39
set_directive_bind_op -op mul -impl fabric "case_80" m40
set_directive_bind_op -op mul -impl fabric "case_80" m41
set_directive_bind_op -op mul -impl fabric "case_80" m42
set_directive_bind_op -op mul -impl fabric "case_80" m43
set_directive_bind_op -op mul -impl fabric "case_80" m44
set_directive_bind_op -op mul -impl fabric "case_80" m45
set_directive_bind_op -op mul -impl fabric "case_80" m46
set_directive_bind_op -op mul -impl fabric "case_80" m47
set_directive_bind_op -op mul -impl fabric "case_80" m48
set_directive_bind_op -op mul -impl fabric "case_80" m49
set_directive_bind_op -op mul -impl fabric "case_80" m50
set_directive_bind_op -op mul -impl fabric "case_80" m51
set_directive_bind_op -op mul -impl fabric "case_80" m52
set_directive_bind_op -op mul -impl fabric "case_80" m53
set_directive_bind_op -op mul -impl fabric "case_80" m54
set_directive_bind_op -op mul -impl fabric "case_80" m55
set_directive_bind_op -op mul -impl fabric "case_80" m56
set_directive_bind_op -op mul -impl fabric "case_80" m57
set_directive_bind_op -op mul -impl fabric "case_80" m58
set_directive_bind_op -op mul -impl fabric "case_80" m59
set_directive_bind_op -op mul -impl fabric "case_80" m60
set_directive_bind_op -op mul -impl fabric "case_80" m61
set_directive_bind_op -op mul -impl fabric "case_80" m62
set_directive_bind_op -op mul -impl fabric "case_80" m63
set_directive_bind_op -op mul -impl fabric "case_80" m64
set_directive_bind_op -op mul -impl fabric "case_80" m65
set_directive_bind_op -op mul -impl fabric "case_80" m66
set_directive_bind_op -op mul -impl fabric "case_80" m67
set_directive_bind_op -op mul -impl fabric "case_80" m68
set_directive_bind_op -op mul -impl fabric "case_80" m69
set_directive_bind_op -op mul -impl fabric "case_80" m70
set_directive_bind_op -op mul -impl fabric "case_80" m71
set_directive_bind_op -op mul -impl fabric "case_80" m72
set_directive_bind_op -op mul -impl fabric "case_80" m73
set_directive_bind_op -op mul -impl fabric "case_80" m74
set_directive_bind_op -op mul -impl fabric "case_80" m75
set_directive_bind_op -op mul -impl fabric "case_80" m76
set_directive_bind_op -op mul -impl fabric "case_80" m77
set_directive_bind_op -op mul -impl fabric "case_80" m78
set_directive_bind_op -op mul -impl fabric "case_80" m79
set_directive_bind_op -op mul -impl fabric "case_80" m80
set_directive_bind_op -op mul -impl fabric "case_80" m81
set_directive_bind_op -op mul -impl fabric "case_80" m82
set_directive_bind_op -op mul -impl fabric "case_80" m83
set_directive_bind_op -op mul -impl fabric "case_80" m84
set_directive_bind_op -op mul -impl fabric "case_80" m85
set_directive_bind_op -op mul -impl fabric "case_80" m86
set_directive_bind_op -op mul -impl fabric "case_80" m87
set_directive_bind_op -op mul -impl fabric "case_80" m88
set_directive_bind_op -op mul -impl fabric "case_80" m89
set_directive_bind_op -op mul -impl fabric "case_80" m90
set_directive_bind_op -op mul -impl fabric "case_80" m91
set_directive_bind_op -op mul -impl fabric "case_80" m92
set_directive_bind_op -op mul -impl fabric "case_80" m93
set_directive_bind_op -op mul -impl fabric "case_80" m94
set_directive_bind_op -op mul -impl fabric "case_80" m95

