set_directive_bind_op -op mul -impl fabric "case_93" m14
set_directive_bind_op -op mul -impl fabric "case_93" m15
set_directive_bind_op -op mul -impl fabric "case_93" m16
set_directive_bind_op -op mul -impl fabric "case_93" m17
set_directive_bind_op -op mul -impl fabric "case_93" m18
set_directive_bind_op -op mul -impl fabric "case_93" m19
set_directive_bind_op -op mul -impl fabric "case_93" m20
set_directive_bind_op -op mul -impl fabric "case_93" m21
set_directive_bind_op -op mul -impl fabric "case_93" m22
set_directive_bind_op -op mul -impl fabric "case_93" m23
set_directive_bind_op -op mul -impl fabric "case_93" m24
set_directive_bind_op -op mul -impl fabric "case_93" m25
set_directive_bind_op -op mul -impl fabric "case_93" m26
set_directive_bind_op -op mul -impl fabric "case_93" m27
set_directive_bind_op -op mul -impl fabric "case_93" m28
set_directive_bind_op -op mul -impl fabric "case_93" m29
set_directive_bind_op -op mul -impl fabric "case_93" m30
set_directive_bind_op -op mul -impl fabric "case_93" m31
set_directive_bind_op -op mul -impl fabric "case_93" m32
set_directive_bind_op -op mul -impl fabric "case_93" m33
set_directive_bind_op -op mul -impl fabric "case_93" m34
set_directive_bind_op -op mul -impl fabric "case_93" m35
set_directive_bind_op -op mul -impl fabric "case_93" m36
set_directive_bind_op -op mul -impl fabric "case_93" m37
set_directive_bind_op -op mul -impl fabric "case_93" m38
set_directive_bind_op -op mul -impl fabric "case_93" m39
set_directive_bind_op -op mul -impl fabric "case_93" m40
set_directive_bind_op -op mul -impl fabric "case_93" m41
set_directive_bind_op -op mul -impl fabric "case_93" m42
set_directive_bind_op -op mul -impl fabric "case_93" m43
set_directive_bind_op -op mul -impl fabric "case_93" m44
set_directive_bind_op -op mul -impl fabric "case_93" m45
set_directive_bind_op -op mul -impl fabric "case_93" m46
set_directive_bind_op -op mul -impl fabric "case_93" m47
set_directive_bind_op -op mul -impl fabric "case_93" m48
set_directive_bind_op -op mul -impl fabric "case_93" m49
set_directive_bind_op -op mul -impl fabric "case_93" m50
set_directive_bind_op -op mul -impl fabric "case_93" m51
set_directive_bind_op -op mul -impl fabric "case_93" m52
set_directive_bind_op -op mul -impl fabric "case_93" m53
set_directive_bind_op -op mul -impl fabric "case_93" m54
set_directive_bind_op -op mul -impl fabric "case_93" m55
set_directive_bind_op -op mul -impl fabric "case_93" m56
set_directive_bind_op -op mul -impl fabric "case_93" m57

