set_directive_bind_op -op mul -impl fabric "case_16" m23
set_directive_bind_op -op mul -impl fabric "case_16" m24
set_directive_bind_op -op mul -impl fabric "case_16" m25
set_directive_bind_op -op mul -impl fabric "case_16" m26
set_directive_bind_op -op mul -impl fabric "case_16" m27
set_directive_bind_op -op mul -impl fabric "case_16" m28
set_directive_bind_op -op mul -impl fabric "case_16" m29
set_directive_bind_op -op mul -impl fabric "case_16" m30
set_directive_bind_op -op mul -impl fabric "case_16" m31
set_directive_bind_op -op mul -impl fabric "case_16" m32
set_directive_bind_op -op mul -impl fabric "case_16" m33
set_directive_bind_op -op mul -impl fabric "case_16" m34
set_directive_bind_op -op mul -impl fabric "case_16" m35
set_directive_bind_op -op mul -impl fabric "case_16" m36
set_directive_bind_op -op mul -impl fabric "case_16" m37
set_directive_bind_op -op mul -impl fabric "case_16" m38
set_directive_bind_op -op mul -impl fabric "case_16" m39
set_directive_bind_op -op mul -impl fabric "case_16" m40
set_directive_bind_op -op mul -impl fabric "case_16" m41
set_directive_bind_op -op mul -impl fabric "case_16" m42
set_directive_bind_op -op mul -impl fabric "case_16" m43
set_directive_bind_op -op mul -impl fabric "case_16" m44
set_directive_bind_op -op mul -impl fabric "case_16" m45
set_directive_bind_op -op mul -impl fabric "case_16" m46
set_directive_bind_op -op mul -impl fabric "case_16" m47
set_directive_bind_op -op mul -impl fabric "case_16" m48
set_directive_bind_op -op mul -impl fabric "case_16" m49
set_directive_bind_op -op mul -impl fabric "case_16" m50
set_directive_bind_op -op mul -impl fabric "case_16" m51
set_directive_bind_op -op mul -impl fabric "case_16" m52
set_directive_bind_op -op mul -impl fabric "case_16" m53
set_directive_bind_op -op mul -impl fabric "case_16" m54
set_directive_bind_op -op mul -impl fabric "case_16" m55
set_directive_bind_op -op mul -impl fabric "case_16" m56
set_directive_bind_op -op mul -impl fabric "case_16" m57
set_directive_bind_op -op mul -impl fabric "case_16" m58
set_directive_bind_op -op mul -impl fabric "case_16" m59
set_directive_bind_op -op mul -impl fabric "case_16" m60
set_directive_bind_op -op mul -impl fabric "case_16" m61
set_directive_bind_op -op mul -impl fabric "case_16" m62
set_directive_bind_op -op mul -impl fabric "case_16" m63
set_directive_bind_op -op mul -impl fabric "case_16" m64
set_directive_bind_op -op mul -impl fabric "case_16" m65
set_directive_bind_op -op mul -impl fabric "case_16" m66
set_directive_bind_op -op mul -impl fabric "case_16" m67
set_directive_bind_op -op mul -impl fabric "case_16" m68
set_directive_bind_op -op mul -impl fabric "case_16" m69
set_directive_bind_op -op mul -impl fabric "case_16" m70
set_directive_bind_op -op mul -impl fabric "case_16" m71
set_directive_bind_op -op mul -impl fabric "case_16" m72
set_directive_bind_op -op mul -impl fabric "case_16" m73
set_directive_bind_op -op mul -impl fabric "case_16" m74
set_directive_bind_op -op mul -impl fabric "case_16" m75
set_directive_bind_op -op mul -impl fabric "case_16" m76
set_directive_bind_op -op mul -impl fabric "case_16" m77
set_directive_bind_op -op mul -impl fabric "case_16" m78

