set_directive_bind_op -op mul -impl fabric "case_74" m12
set_directive_bind_op -op mul -impl fabric "case_74" m13
set_directive_bind_op -op mul -impl fabric "case_74" m14
set_directive_bind_op -op mul -impl fabric "case_74" m15
set_directive_bind_op -op mul -impl fabric "case_74" m16
set_directive_bind_op -op mul -impl fabric "case_74" m17
set_directive_bind_op -op mul -impl fabric "case_74" m18
set_directive_bind_op -op mul -impl fabric "case_74" m19
set_directive_bind_op -op mul -impl fabric "case_74" m20
set_directive_bind_op -op mul -impl fabric "case_74" m21
set_directive_bind_op -op mul -impl fabric "case_74" m22
set_directive_bind_op -op mul -impl fabric "case_74" m23
set_directive_bind_op -op mul -impl fabric "case_74" m24
set_directive_bind_op -op mul -impl fabric "case_74" m25
set_directive_bind_op -op mul -impl fabric "case_74" m26
set_directive_bind_op -op mul -impl fabric "case_74" m27
set_directive_bind_op -op mul -impl fabric "case_74" m28
set_directive_bind_op -op mul -impl fabric "case_74" m29
set_directive_bind_op -op mul -impl fabric "case_74" m30
set_directive_bind_op -op mul -impl fabric "case_74" m31
set_directive_bind_op -op mul -impl fabric "case_74" m32
set_directive_bind_op -op mul -impl fabric "case_74" m33
set_directive_bind_op -op mul -impl fabric "case_74" m34
set_directive_bind_op -op mul -impl fabric "case_74" m35
set_directive_bind_op -op mul -impl fabric "case_74" m36
set_directive_bind_op -op mul -impl fabric "case_74" m37
set_directive_bind_op -op mul -impl fabric "case_74" m38
set_directive_bind_op -op mul -impl fabric "case_74" m39
set_directive_bind_op -op mul -impl fabric "case_74" m40
set_directive_bind_op -op mul -impl fabric "case_74" m41
set_directive_bind_op -op mul -impl fabric "case_74" m42
set_directive_bind_op -op mul -impl fabric "case_74" m43
set_directive_bind_op -op mul -impl fabric "case_74" m44
set_directive_bind_op -op mul -impl fabric "case_74" m45
set_directive_bind_op -op mul -impl fabric "case_74" m46
set_directive_bind_op -op mul -impl fabric "case_74" m47
set_directive_bind_op -op mul -impl fabric "case_74" m48
set_directive_bind_op -op mul -impl fabric "case_74" m49
set_directive_bind_op -op mul -impl fabric "case_74" m50
set_directive_bind_op -op mul -impl fabric "case_74" m51
set_directive_bind_op -op mul -impl fabric "case_74" m52
set_directive_bind_op -op mul -impl fabric "case_74" m53
set_directive_bind_op -op mul -impl fabric "case_74" m54
set_directive_bind_op -op mul -impl fabric "case_74" m55
set_directive_bind_op -op mul -impl fabric "case_74" m56
set_directive_bind_op -op mul -impl fabric "case_74" m57
set_directive_bind_op -op mul -impl fabric "case_74" m58
set_directive_bind_op -op mul -impl fabric "case_74" m59
set_directive_bind_op -op mul -impl fabric "case_74" m60
set_directive_bind_op -op mul -impl fabric "case_74" m61
set_directive_bind_op -op mul -impl fabric "case_74" m62
set_directive_bind_op -op mul -impl fabric "case_74" m63
set_directive_bind_op -op mul -impl fabric "case_74" m64
set_directive_bind_op -op mul -impl fabric "case_74" m65
set_directive_bind_op -op mul -impl fabric "case_74" m66
set_directive_bind_op -op mul -impl fabric "case_74" m67
set_directive_bind_op -op mul -impl fabric "case_74" m68
set_directive_bind_op -op mul -impl fabric "case_74" m69
set_directive_bind_op -op mul -impl fabric "case_74" m70
set_directive_bind_op -op mul -impl fabric "case_74" m71
set_directive_bind_op -op mul -impl fabric "case_74" m72
set_directive_bind_op -op mul -impl fabric "case_74" m73
set_directive_bind_op -op mul -impl fabric "case_74" m74
set_directive_bind_op -op mul -impl fabric "case_74" m75
set_directive_bind_op -op mul -impl fabric "case_74" m76
set_directive_bind_op -op mul -impl fabric "case_74" m77
set_directive_bind_op -op mul -impl fabric "case_74" m78
set_directive_bind_op -op mul -impl fabric "case_74" m79
set_directive_bind_op -op mul -impl fabric "case_74" m80
set_directive_bind_op -op mul -impl fabric "case_74" m81
set_directive_bind_op -op mul -impl fabric "case_74" m82
set_directive_bind_op -op mul -impl fabric "case_74" m83

