set_directive_bind_op -op mul -impl fabric "case_50" m16
set_directive_bind_op -op mul -impl fabric "case_50" m17
set_directive_bind_op -op mul -impl fabric "case_50" m18
set_directive_bind_op -op mul -impl fabric "case_50" m19
set_directive_bind_op -op mul -impl fabric "case_50" m20
set_directive_bind_op -op mul -impl fabric "case_50" m21
set_directive_bind_op -op mul -impl fabric "case_50" m22
set_directive_bind_op -op mul -impl fabric "case_50" m23
set_directive_bind_op -op mul -impl fabric "case_50" m24
set_directive_bind_op -op mul -impl fabric "case_50" m25
set_directive_bind_op -op mul -impl fabric "case_50" m26
set_directive_bind_op -op mul -impl fabric "case_50" m27
set_directive_bind_op -op mul -impl fabric "case_50" m28
set_directive_bind_op -op mul -impl fabric "case_50" m29
set_directive_bind_op -op mul -impl fabric "case_50" m30
set_directive_bind_op -op mul -impl fabric "case_50" m31
set_directive_bind_op -op mul -impl fabric "case_50" m32
set_directive_bind_op -op mul -impl fabric "case_50" m33
set_directive_bind_op -op mul -impl fabric "case_50" m34
set_directive_bind_op -op mul -impl fabric "case_50" m35
set_directive_bind_op -op mul -impl fabric "case_50" m36
set_directive_bind_op -op mul -impl fabric "case_50" m37
set_directive_bind_op -op mul -impl fabric "case_50" m38
set_directive_bind_op -op mul -impl fabric "case_50" m39
set_directive_bind_op -op mul -impl fabric "case_50" m40
set_directive_bind_op -op mul -impl fabric "case_50" m41
set_directive_bind_op -op mul -impl fabric "case_50" m42
set_directive_bind_op -op mul -impl fabric "case_50" m43
set_directive_bind_op -op mul -impl fabric "case_50" m44
set_directive_bind_op -op mul -impl fabric "case_50" m45
set_directive_bind_op -op mul -impl fabric "case_50" m46
set_directive_bind_op -op mul -impl fabric "case_50" m47
set_directive_bind_op -op mul -impl fabric "case_50" m48
set_directive_bind_op -op mul -impl fabric "case_50" m49
set_directive_bind_op -op mul -impl fabric "case_50" m50
set_directive_bind_op -op mul -impl fabric "case_50" m51
set_directive_bind_op -op mul -impl fabric "case_50" m52
set_directive_bind_op -op mul -impl fabric "case_50" m53
set_directive_bind_op -op mul -impl fabric "case_50" m54
set_directive_bind_op -op mul -impl fabric "case_50" m55
set_directive_bind_op -op mul -impl fabric "case_50" m56
set_directive_bind_op -op mul -impl fabric "case_50" m57
set_directive_bind_op -op mul -impl fabric "case_50" m58
set_directive_bind_op -op mul -impl fabric "case_50" m59
set_directive_bind_op -op mul -impl fabric "case_50" m60
set_directive_bind_op -op mul -impl fabric "case_50" m61
set_directive_bind_op -op mul -impl fabric "case_50" m62
set_directive_bind_op -op mul -impl fabric "case_50" m63
set_directive_bind_op -op mul -impl fabric "case_50" m64
set_directive_bind_op -op mul -impl fabric "case_50" m65
set_directive_bind_op -op mul -impl fabric "case_50" m66
set_directive_bind_op -op mul -impl fabric "case_50" m67
set_directive_bind_op -op mul -impl fabric "case_50" m68
set_directive_bind_op -op mul -impl fabric "case_50" m69
set_directive_bind_op -op mul -impl fabric "case_50" m70
set_directive_bind_op -op mul -impl fabric "case_50" m71
set_directive_bind_op -op mul -impl fabric "case_50" m72
set_directive_bind_op -op mul -impl fabric "case_50" m73
set_directive_bind_op -op mul -impl fabric "case_50" m74
set_directive_bind_op -op mul -impl fabric "case_50" m75
set_directive_bind_op -op mul -impl fabric "case_50" m76
set_directive_bind_op -op mul -impl fabric "case_50" m77
set_directive_bind_op -op mul -impl fabric "case_50" m78
set_directive_bind_op -op mul -impl fabric "case_50" m79
set_directive_bind_op -op mul -impl fabric "case_50" m80
set_directive_bind_op -op mul -impl fabric "case_50" m81
set_directive_bind_op -op mul -impl fabric "case_50" m82
set_directive_bind_op -op mul -impl fabric "case_50" m83
set_directive_bind_op -op mul -impl fabric "case_50" m84
set_directive_bind_op -op mul -impl fabric "case_50" m85
set_directive_bind_op -op mul -impl fabric "case_50" m86
set_directive_bind_op -op mul -impl fabric "case_50" m87
set_directive_bind_op -op mul -impl fabric "case_50" m88
set_directive_bind_op -op mul -impl fabric "case_50" m89
set_directive_bind_op -op mul -impl fabric "case_50" m90
set_directive_bind_op -op mul -impl fabric "case_50" m91
set_directive_bind_op -op mul -impl fabric "case_50" m92
set_directive_bind_op -op mul -impl fabric "case_50" m93
set_directive_bind_op -op mul -impl fabric "case_50" m94
set_directive_bind_op -op mul -impl fabric "case_50" m95
set_directive_bind_op -op mul -impl fabric "case_50" m96
set_directive_bind_op -op mul -impl fabric "case_50" m97
set_directive_bind_op -op mul -impl fabric "case_50" m98
set_directive_bind_op -op mul -impl fabric "case_50" m99
set_directive_bind_op -op mul -impl fabric "case_50" m100
set_directive_bind_op -op mul -impl fabric "case_50" m101
set_directive_bind_op -op mul -impl fabric "case_50" m102
set_directive_bind_op -op mul -impl fabric "case_50" m103
set_directive_bind_op -op mul -impl fabric "case_50" m104
set_directive_bind_op -op mul -impl fabric "case_50" m105
set_directive_bind_op -op mul -impl fabric "case_50" m106
set_directive_bind_op -op mul -impl fabric "case_50" m107
set_directive_bind_op -op mul -impl fabric "case_50" m108
set_directive_bind_op -op mul -impl fabric "case_50" m109
set_directive_bind_op -op mul -impl fabric "case_50" m110
set_directive_bind_op -op mul -impl fabric "case_50" m111
set_directive_bind_op -op mul -impl fabric "case_50" m112
set_directive_bind_op -op mul -impl fabric "case_50" m113
set_directive_bind_op -op mul -impl fabric "case_50" m114
set_directive_bind_op -op mul -impl fabric "case_50" m115
set_directive_bind_op -op mul -impl fabric "case_50" m116
set_directive_bind_op -op mul -impl fabric "case_50" m117
set_directive_bind_op -op mul -impl fabric "case_50" m118
set_directive_bind_op -op mul -impl fabric "case_50" m119
set_directive_bind_op -op mul -impl fabric "case_50" m120
set_directive_bind_op -op mul -impl fabric "case_50" m121
set_directive_bind_op -op mul -impl fabric "case_50" m122
set_directive_bind_op -op mul -impl fabric "case_50" m123
set_directive_bind_op -op mul -impl fabric "case_50" m124
set_directive_bind_op -op mul -impl fabric "case_50" m125
set_directive_bind_op -op mul -impl fabric "case_50" m126
set_directive_bind_op -op mul -impl fabric "case_50" m127
set_directive_bind_op -op mul -impl fabric "case_50" m128
set_directive_bind_op -op mul -impl fabric "case_50" m129
set_directive_bind_op -op mul -impl fabric "case_50" m130
set_directive_bind_op -op mul -impl fabric "case_50" m131
set_directive_bind_op -op mul -impl fabric "case_50" m132
set_directive_bind_op -op mul -impl fabric "case_50" m133
set_directive_bind_op -op mul -impl fabric "case_50" m134
set_directive_bind_op -op mul -impl fabric "case_50" m135
set_directive_bind_op -op mul -impl fabric "case_50" m136
set_directive_bind_op -op mul -impl fabric "case_50" m137
set_directive_bind_op -op mul -impl fabric "case_50" m138
set_directive_bind_op -op mul -impl fabric "case_50" m139
set_directive_bind_op -op mul -impl fabric "case_50" m140
set_directive_bind_op -op mul -impl fabric "case_50" m141
set_directive_bind_op -op mul -impl fabric "case_50" m142
set_directive_bind_op -op mul -impl fabric "case_50" m143
set_directive_bind_op -op mul -impl fabric "case_50" m144
set_directive_bind_op -op mul -impl fabric "case_50" m145
set_directive_bind_op -op mul -impl fabric "case_50" m146
set_directive_bind_op -op mul -impl fabric "case_50" m147
set_directive_bind_op -op mul -impl fabric "case_50" m148
set_directive_bind_op -op mul -impl fabric "case_50" m149
set_directive_bind_op -op mul -impl fabric "case_50" m150
set_directive_bind_op -op mul -impl fabric "case_50" m151
set_directive_bind_op -op mul -impl fabric "case_50" m152
set_directive_bind_op -op mul -impl fabric "case_50" m153
set_directive_bind_op -op mul -impl fabric "case_50" m154
set_directive_bind_op -op mul -impl fabric "case_50" m155
set_directive_bind_op -op mul -impl fabric "case_50" m156
set_directive_bind_op -op mul -impl fabric "case_50" m157
set_directive_bind_op -op mul -impl fabric "case_50" m158
set_directive_bind_op -op mul -impl fabric "case_50" m159
set_directive_bind_op -op mul -impl fabric "case_50" m160
set_directive_bind_op -op mul -impl fabric "case_50" m161
set_directive_bind_op -op mul -impl fabric "case_50" m162
set_directive_bind_op -op mul -impl fabric "case_50" m163

