set_directive_resource -core Mul_LUT "case_1" m28
set_directive_resource -core Mul_LUT "case_1" m29
set_directive_resource -core Mul_LUT "case_1" m30
set_directive_resource -core Mul_LUT "case_1" m31
set_directive_resource -core Mul_LUT "case_1" m32
set_directive_resource -core Mul_LUT "case_1" m33
set_directive_resource -core Mul_LUT "case_1" m34
set_directive_resource -core Mul_LUT "case_1" m35
set_directive_resource -core Mul_LUT "case_1" m36
set_directive_resource -core Mul_LUT "case_1" m37
set_directive_resource -core Mul_LUT "case_1" m38
set_directive_resource -core Mul_LUT "case_1" m39
set_directive_resource -core Mul_LUT "case_1" m40
set_directive_resource -core Mul_LUT "case_1" m41
set_directive_resource -core Mul_LUT "case_1" m42
set_directive_resource -core Mul_LUT "case_1" m43
set_directive_resource -core Mul_LUT "case_1" m44
set_directive_resource -core Mul_LUT "case_1" m45
set_directive_resource -core Mul_LUT "case_1" m46
set_directive_resource -core Mul_LUT "case_1" m47
set_directive_resource -core Mul_LUT "case_1" m48
set_directive_resource -core Mul_LUT "case_1" m49
set_directive_resource -core Mul_LUT "case_1" m50
set_directive_resource -core Mul_LUT "case_1" m51
set_directive_resource -core Mul_LUT "case_1" m52
set_directive_resource -core Mul_LUT "case_1" m53
set_directive_resource -core Mul_LUT "case_1" m54
set_directive_resource -core Mul_LUT "case_1" m55
set_directive_resource -core Mul_LUT "case_1" m56
set_directive_resource -core Mul_LUT "case_1" m57
set_directive_resource -core Mul_LUT "case_1" m58
set_directive_resource -core Mul_LUT "case_1" m59
set_directive_resource -core Mul_LUT "case_1" m60
set_directive_resource -core Mul_LUT "case_1" m61
set_directive_resource -core Mul_LUT "case_1" m62
set_directive_resource -core Mul_LUT "case_1" m63
set_directive_resource -core Mul_LUT "case_1" m64
set_directive_resource -core Mul_LUT "case_1" m65
set_directive_resource -core Mul_LUT "case_1" m66
set_directive_resource -core Mul_LUT "case_1" m67
set_directive_resource -core Mul_LUT "case_1" m68
set_directive_resource -core Mul_LUT "case_1" m69
set_directive_resource -core Mul_LUT "case_1" m70
set_directive_resource -core Mul_LUT "case_1" m71
set_directive_resource -core Mul_LUT "case_1" m72
set_directive_resource -core Mul_LUT "case_1" m73
set_directive_resource -core Mul_LUT "case_1" m74
set_directive_resource -core Mul_LUT "case_1" m75
set_directive_resource -core Mul_LUT "case_1" m76
set_directive_resource -core Mul_LUT "case_1" m77
set_directive_resource -core Mul_LUT "case_1" m78
set_directive_resource -core Mul_LUT "case_1" m79
set_directive_resource -core Mul_LUT "case_1" m80
set_directive_resource -core Mul_LUT "case_1" m81
set_directive_resource -core Mul_LUT "case_1" m82
set_directive_resource -core Mul_LUT "case_1" m83
set_directive_resource -core Mul_LUT "case_1" m84
set_directive_resource -core Mul_LUT "case_1" m85
set_directive_resource -core Mul_LUT "case_1" m86
set_directive_resource -core Mul_LUT "case_1" m87
set_directive_resource -core Mul_LUT "case_1" m88
set_directive_resource -core Mul_LUT "case_1" m89
set_directive_resource -core Mul_LUT "case_1" m90
set_directive_resource -core Mul_LUT "case_1" m91
set_directive_resource -core Mul_LUT "case_1" m92
set_directive_resource -core Mul_LUT "case_1" m93
set_directive_resource -core Mul_LUT "case_1" m94
set_directive_resource -core Mul_LUT "case_1" m95
set_directive_resource -core Mul_LUT "case_1" m96
set_directive_resource -core Mul_LUT "case_1" m97
set_directive_resource -core Mul_LUT "case_1" m98
set_directive_resource -core Mul_LUT "case_1" m99
set_directive_resource -core Mul_LUT "case_1" m100
set_directive_resource -core Mul_LUT "case_1" m101
set_directive_resource -core Mul_LUT "case_1" m102
set_directive_resource -core Mul_LUT "case_1" m103
set_directive_resource -core Mul_LUT "case_1" m104
set_directive_resource -core Mul_LUT "case_1" m105
set_directive_resource -core Mul_LUT "case_1" m106
set_directive_resource -core Mul_LUT "case_1" m107
set_directive_resource -core Mul_LUT "case_1" m108
set_directive_resource -core Mul_LUT "case_1" m109
set_directive_resource -core Mul_LUT "case_1" m110
set_directive_resource -core Mul_LUT "case_1" m111
set_directive_resource -core Mul_LUT "case_1" m112
set_directive_resource -core Mul_LUT "case_1" m113
set_directive_resource -core Mul_LUT "case_1" m114
set_directive_resource -core Mul_LUT "case_1" m115
set_directive_resource -core Mul_LUT "case_1" m116
set_directive_resource -core Mul_LUT "case_1" m117
set_directive_resource -core Mul_LUT "case_1" m118
set_directive_resource -core Mul_LUT "case_1" m119
set_directive_resource -core Mul_LUT "case_1" m120
set_directive_resource -core Mul_LUT "case_1" m121
set_directive_resource -core Mul_LUT "case_1" m122
set_directive_resource -core Mul_LUT "case_1" m123
set_directive_resource -core Mul_LUT "case_1" m124
set_directive_resource -core Mul_LUT "case_1" m125
set_directive_resource -core Mul_LUT "case_1" m126
set_directive_resource -core Mul_LUT "case_1" m127
set_directive_resource -core Mul_LUT "case_1" m128
set_directive_resource -core Mul_LUT "case_1" m129
set_directive_resource -core Mul_LUT "case_1" m130
set_directive_resource -core Mul_LUT "case_1" m131
set_directive_resource -core Mul_LUT "case_1" m132
set_directive_resource -core Mul_LUT "case_1" m133
set_directive_resource -core Mul_LUT "case_1" m134
set_directive_resource -core Mul_LUT "case_1" m135
set_directive_resource -core Mul_LUT "case_1" m136
set_directive_resource -core Mul_LUT "case_1" m137
set_directive_resource -core Mul_LUT "case_1" m138
set_directive_resource -core Mul_LUT "case_1" m139
set_directive_resource -core Mul_LUT "case_1" m140
set_directive_resource -core Mul_LUT "case_1" m141
set_directive_resource -core Mul_LUT "case_1" m142
set_directive_resource -core Mul_LUT "case_1" m143
set_directive_resource -core Mul_LUT "case_1" m144
set_directive_resource -core Mul_LUT "case_1" m145
set_directive_resource -core Mul_LUT "case_1" m146
set_directive_resource -core Mul_LUT "case_1" m147
set_directive_resource -core Mul_LUT "case_1" m148
set_directive_resource -core Mul_LUT "case_1" m149
set_directive_resource -core Mul_LUT "case_1" m150
set_directive_resource -core Mul_LUT "case_1" m151
set_directive_resource -core Mul_LUT "case_1" m152
set_directive_resource -core Mul_LUT "case_1" m153
set_directive_resource -core Mul_LUT "case_1" m154
set_directive_resource -core Mul_LUT "case_1" m155
set_directive_resource -core Mul_LUT "case_1" m156
set_directive_resource -core Mul_LUT "case_1" m157
set_directive_resource -core Mul_LUT "case_1" m158
set_directive_resource -core Mul_LUT "case_1" m159
set_directive_resource -core Mul_LUT "case_1" m160
set_directive_resource -core Mul_LUT "case_1" m161
set_directive_resource -core Mul_LUT "case_1" m162
set_directive_resource -core Mul_LUT "case_1" m163
set_directive_resource -core Mul_LUT "case_1" m164
set_directive_resource -core Mul_LUT "case_1" m165
set_directive_resource -core Mul_LUT "case_1" m166
set_directive_resource -core Mul_LUT "case_1" m167
set_directive_resource -core Mul_LUT "case_1" m168
set_directive_resource -core Mul_LUT "case_1" m169
set_directive_resource -core Mul_LUT "case_1" m170
set_directive_resource -core Mul_LUT "case_1" m171
set_directive_resource -core Mul_LUT "case_1" m172
set_directive_resource -core Mul_LUT "case_1" m173
set_directive_resource -core Mul_LUT "case_1" m174
set_directive_resource -core Mul_LUT "case_1" m175
set_directive_resource -core Mul_LUT "case_1" m176
set_directive_resource -core Mul_LUT "case_1" m177
set_directive_resource -core Mul_LUT "case_1" m178
set_directive_resource -core Mul_LUT "case_1" m179
set_directive_resource -core Mul_LUT "case_1" m180
set_directive_resource -core Mul_LUT "case_1" m181
set_directive_resource -core Mul_LUT "case_1" m182
set_directive_resource -core Mul_LUT "case_1" m183
set_directive_resource -core Mul_LUT "case_1" m184
set_directive_resource -core Mul_LUT "case_1" m185
set_directive_resource -core Mul_LUT "case_1" m186
set_directive_resource -core Mul_LUT "case_1" m187
set_directive_resource -core Mul_LUT "case_1" m188
set_directive_resource -core Mul_LUT "case_1" m189
set_directive_resource -core Mul_LUT "case_1" m190
set_directive_resource -core Mul_LUT "case_1" m191
set_directive_resource -core Mul_LUT "case_1" m192
set_directive_resource -core Mul_LUT "case_1" m193
set_directive_resource -core Mul_LUT "case_1" m194
set_directive_resource -core Mul_LUT "case_1" m195
set_directive_resource -core Mul_LUT "case_1" m196
set_directive_resource -core Mul_LUT "case_1" m197
set_directive_resource -core Mul_LUT "case_1" m198
set_directive_resource -core Mul_LUT "case_1" m199
set_directive_resource -core Mul_LUT "case_1" m200
set_directive_resource -core Mul_LUT "case_1" m201
set_directive_resource -core Mul_LUT "case_1" m202
set_directive_resource -core Mul_LUT "case_1" m203
set_directive_resource -core Mul_LUT "case_1" m204
set_directive_resource -core Mul_LUT "case_1" m205
set_directive_resource -core Mul_LUT "case_1" m206
set_directive_resource -core Mul_LUT "case_1" m207
set_directive_resource -core Mul_LUT "case_1" m208
set_directive_resource -core Mul_LUT "case_1" m209
set_directive_resource -core Mul_LUT "case_1" m210
set_directive_resource -core Mul_LUT "case_1" m211
set_directive_resource -core Mul_LUT "case_1" m212

