set_directive_bind_op -op mul -impl fabric "case_46" m6
set_directive_bind_op -op mul -impl fabric "case_46" m7
set_directive_bind_op -op mul -impl fabric "case_46" m8
set_directive_bind_op -op mul -impl fabric "case_46" m9
set_directive_bind_op -op mul -impl fabric "case_46" m10
set_directive_bind_op -op mul -impl fabric "case_46" m11
set_directive_bind_op -op mul -impl fabric "case_46" m12
set_directive_bind_op -op mul -impl fabric "case_46" m13
set_directive_bind_op -op mul -impl fabric "case_46" m14
set_directive_bind_op -op mul -impl fabric "case_46" m15
set_directive_bind_op -op mul -impl fabric "case_46" m16
set_directive_bind_op -op mul -impl fabric "case_46" m17
set_directive_bind_op -op mul -impl fabric "case_46" m18
set_directive_bind_op -op mul -impl fabric "case_46" m19
set_directive_bind_op -op mul -impl fabric "case_46" m20
set_directive_bind_op -op mul -impl fabric "case_46" m21
set_directive_bind_op -op mul -impl fabric "case_46" m22
set_directive_bind_op -op mul -impl fabric "case_46" m23
set_directive_bind_op -op mul -impl fabric "case_46" m24
set_directive_bind_op -op mul -impl fabric "case_46" m25
set_directive_bind_op -op mul -impl fabric "case_46" m26
set_directive_bind_op -op mul -impl fabric "case_46" m27
set_directive_bind_op -op mul -impl fabric "case_46" m28
set_directive_bind_op -op mul -impl fabric "case_46" m29
set_directive_bind_op -op mul -impl fabric "case_46" m30
set_directive_bind_op -op mul -impl fabric "case_46" m31
set_directive_bind_op -op mul -impl fabric "case_46" m32
set_directive_bind_op -op mul -impl fabric "case_46" m33
set_directive_bind_op -op mul -impl fabric "case_46" m34
set_directive_bind_op -op mul -impl fabric "case_46" m35
set_directive_bind_op -op mul -impl fabric "case_46" m36
set_directive_bind_op -op mul -impl fabric "case_46" m37
set_directive_bind_op -op mul -impl fabric "case_46" m38
set_directive_bind_op -op mul -impl fabric "case_46" m39
set_directive_bind_op -op mul -impl fabric "case_46" m40
set_directive_bind_op -op mul -impl fabric "case_46" m41
set_directive_bind_op -op mul -impl fabric "case_46" m42
set_directive_bind_op -op mul -impl fabric "case_46" m43
set_directive_bind_op -op mul -impl fabric "case_46" m44
set_directive_bind_op -op mul -impl fabric "case_46" m45
set_directive_bind_op -op mul -impl fabric "case_46" m46
set_directive_bind_op -op mul -impl fabric "case_46" m47
set_directive_bind_op -op mul -impl fabric "case_46" m48
set_directive_bind_op -op mul -impl fabric "case_46" m49
set_directive_bind_op -op mul -impl fabric "case_46" m50
set_directive_bind_op -op mul -impl fabric "case_46" m51
set_directive_bind_op -op mul -impl fabric "case_46" m52
set_directive_bind_op -op mul -impl fabric "case_46" m53
set_directive_bind_op -op mul -impl fabric "case_46" m54
set_directive_bind_op -op mul -impl fabric "case_46" m55
set_directive_bind_op -op mul -impl fabric "case_46" m56
set_directive_bind_op -op mul -impl fabric "case_46" m57
set_directive_bind_op -op mul -impl fabric "case_46" m58
set_directive_bind_op -op mul -impl fabric "case_46" m59
set_directive_bind_op -op mul -impl fabric "case_46" m60
set_directive_bind_op -op mul -impl fabric "case_46" m61
set_directive_bind_op -op mul -impl fabric "case_46" m62
set_directive_bind_op -op mul -impl fabric "case_46" m63
set_directive_bind_op -op mul -impl fabric "case_46" m64
set_directive_bind_op -op mul -impl fabric "case_46" m65
set_directive_bind_op -op mul -impl fabric "case_46" m66
set_directive_bind_op -op mul -impl fabric "case_46" m67
set_directive_bind_op -op mul -impl fabric "case_46" m68
set_directive_bind_op -op mul -impl fabric "case_46" m69
set_directive_bind_op -op mul -impl fabric "case_46" m70
set_directive_bind_op -op mul -impl fabric "case_46" m71
set_directive_bind_op -op mul -impl fabric "case_46" m72
set_directive_bind_op -op mul -impl fabric "case_46" m73
set_directive_bind_op -op mul -impl fabric "case_46" m74
set_directive_bind_op -op mul -impl fabric "case_46" m75
set_directive_bind_op -op mul -impl fabric "case_46" m76
set_directive_bind_op -op mul -impl fabric "case_46" m77
set_directive_bind_op -op mul -impl fabric "case_46" m78
set_directive_bind_op -op mul -impl fabric "case_46" m79
set_directive_bind_op -op mul -impl fabric "case_46" m80
set_directive_bind_op -op mul -impl fabric "case_46" m81
set_directive_bind_op -op mul -impl fabric "case_46" m82
set_directive_bind_op -op mul -impl fabric "case_46" m83
set_directive_bind_op -op mul -impl fabric "case_46" m84
set_directive_bind_op -op mul -impl fabric "case_46" m85
set_directive_bind_op -op mul -impl fabric "case_46" m86
set_directive_bind_op -op mul -impl fabric "case_46" m87
set_directive_bind_op -op mul -impl fabric "case_46" m88
set_directive_bind_op -op mul -impl fabric "case_46" m89
set_directive_bind_op -op mul -impl fabric "case_46" m90
set_directive_bind_op -op mul -impl fabric "case_46" m91
set_directive_bind_op -op mul -impl fabric "case_46" m92
set_directive_bind_op -op mul -impl fabric "case_46" m93
set_directive_bind_op -op mul -impl fabric "case_46" m94

