set_directive_bind_op -op mul -impl fabric "case_1" m7
set_directive_bind_op -op mul -impl fabric "case_1" m8
set_directive_bind_op -op mul -impl fabric "case_1" m9
set_directive_bind_op -op mul -impl fabric "case_1" m10
set_directive_bind_op -op mul -impl fabric "case_1" m11
set_directive_bind_op -op mul -impl fabric "case_1" m12
set_directive_bind_op -op mul -impl fabric "case_1" m13
set_directive_bind_op -op mul -impl fabric "case_1" m14
set_directive_bind_op -op mul -impl fabric "case_1" m15
set_directive_bind_op -op mul -impl fabric "case_1" m16
set_directive_bind_op -op mul -impl fabric "case_1" m17
set_directive_bind_op -op mul -impl fabric "case_1" m18
set_directive_bind_op -op mul -impl fabric "case_1" m19
set_directive_bind_op -op mul -impl fabric "case_1" m20
set_directive_bind_op -op mul -impl fabric "case_1" m21
set_directive_bind_op -op mul -impl fabric "case_1" m22
set_directive_bind_op -op mul -impl fabric "case_1" m23
set_directive_bind_op -op mul -impl fabric "case_1" m24
set_directive_bind_op -op mul -impl fabric "case_1" m25
set_directive_bind_op -op mul -impl fabric "case_1" m26
set_directive_bind_op -op mul -impl fabric "case_1" m27
set_directive_bind_op -op mul -impl fabric "case_1" m28
set_directive_bind_op -op mul -impl fabric "case_1" m29

