set_directive_bind_op -op mul -impl fabric "case_68" m20
set_directive_bind_op -op mul -impl fabric "case_68" m21
set_directive_bind_op -op mul -impl fabric "case_68" m22
set_directive_bind_op -op mul -impl fabric "case_68" m23
set_directive_bind_op -op mul -impl fabric "case_68" m24
set_directive_bind_op -op mul -impl fabric "case_68" m25
set_directive_bind_op -op mul -impl fabric "case_68" m26
set_directive_bind_op -op mul -impl fabric "case_68" m27
set_directive_bind_op -op mul -impl fabric "case_68" m28
set_directive_bind_op -op mul -impl fabric "case_68" m29
set_directive_bind_op -op mul -impl fabric "case_68" m30
set_directive_bind_op -op mul -impl fabric "case_68" m31
set_directive_bind_op -op mul -impl fabric "case_68" m32
set_directive_bind_op -op mul -impl fabric "case_68" m33
set_directive_bind_op -op mul -impl fabric "case_68" m34
set_directive_bind_op -op mul -impl fabric "case_68" m35
set_directive_bind_op -op mul -impl fabric "case_68" m36
set_directive_bind_op -op mul -impl fabric "case_68" m37
set_directive_bind_op -op mul -impl fabric "case_68" m38
set_directive_bind_op -op mul -impl fabric "case_68" m39
set_directive_bind_op -op mul -impl fabric "case_68" m40
set_directive_bind_op -op mul -impl fabric "case_68" m41
set_directive_bind_op -op mul -impl fabric "case_68" m42
set_directive_bind_op -op mul -impl fabric "case_68" m43
set_directive_bind_op -op mul -impl fabric "case_68" m44
set_directive_bind_op -op mul -impl fabric "case_68" m45
set_directive_bind_op -op mul -impl fabric "case_68" m46
set_directive_bind_op -op mul -impl fabric "case_68" m47
set_directive_bind_op -op mul -impl fabric "case_68" m48
set_directive_bind_op -op mul -impl fabric "case_68" m49
set_directive_bind_op -op mul -impl fabric "case_68" m50
set_directive_bind_op -op mul -impl fabric "case_68" m51
set_directive_bind_op -op mul -impl fabric "case_68" m52
set_directive_bind_op -op mul -impl fabric "case_68" m53
set_directive_bind_op -op mul -impl fabric "case_68" m54
set_directive_bind_op -op mul -impl fabric "case_68" m55
set_directive_bind_op -op mul -impl fabric "case_68" m56
set_directive_bind_op -op mul -impl fabric "case_68" m57
set_directive_bind_op -op mul -impl fabric "case_68" m58
set_directive_bind_op -op mul -impl fabric "case_68" m59
set_directive_bind_op -op mul -impl fabric "case_68" m60
set_directive_bind_op -op mul -impl fabric "case_68" m61
set_directive_bind_op -op mul -impl fabric "case_68" m62
set_directive_bind_op -op mul -impl fabric "case_68" m63
set_directive_bind_op -op mul -impl fabric "case_68" m64
set_directive_bind_op -op mul -impl fabric "case_68" m65
set_directive_bind_op -op mul -impl fabric "case_68" m66
set_directive_bind_op -op mul -impl fabric "case_68" m67
set_directive_bind_op -op mul -impl fabric "case_68" m68
set_directive_bind_op -op mul -impl fabric "case_68" m69
set_directive_bind_op -op mul -impl fabric "case_68" m70
set_directive_bind_op -op mul -impl fabric "case_68" m71
set_directive_bind_op -op mul -impl fabric "case_68" m72
set_directive_bind_op -op mul -impl fabric "case_68" m73
set_directive_bind_op -op mul -impl fabric "case_68" m74
set_directive_bind_op -op mul -impl fabric "case_68" m75
set_directive_bind_op -op mul -impl fabric "case_68" m76
set_directive_bind_op -op mul -impl fabric "case_68" m77
set_directive_bind_op -op mul -impl fabric "case_68" m78
set_directive_bind_op -op mul -impl fabric "case_68" m79
set_directive_bind_op -op mul -impl fabric "case_68" m80
set_directive_bind_op -op mul -impl fabric "case_68" m81
set_directive_bind_op -op mul -impl fabric "case_68" m82
set_directive_bind_op -op mul -impl fabric "case_68" m83
set_directive_bind_op -op mul -impl fabric "case_68" m84
set_directive_bind_op -op mul -impl fabric "case_68" m85
set_directive_bind_op -op mul -impl fabric "case_68" m86
set_directive_bind_op -op mul -impl fabric "case_68" m87
set_directive_bind_op -op mul -impl fabric "case_68" m88
set_directive_bind_op -op mul -impl fabric "case_68" m89
set_directive_bind_op -op mul -impl fabric "case_68" m90
set_directive_bind_op -op mul -impl fabric "case_68" m91
set_directive_bind_op -op mul -impl fabric "case_68" m92
set_directive_bind_op -op mul -impl fabric "case_68" m93
set_directive_bind_op -op mul -impl fabric "case_68" m94
set_directive_bind_op -op mul -impl fabric "case_68" m95
set_directive_bind_op -op mul -impl fabric "case_68" m96
set_directive_bind_op -op mul -impl fabric "case_68" m97
set_directive_bind_op -op mul -impl fabric "case_68" m98
set_directive_bind_op -op mul -impl fabric "case_68" m99
set_directive_bind_op -op mul -impl fabric "case_68" m100
set_directive_bind_op -op mul -impl fabric "case_68" m101
set_directive_bind_op -op mul -impl fabric "case_68" m102
set_directive_bind_op -op mul -impl fabric "case_68" m103
set_directive_bind_op -op mul -impl fabric "case_68" m104
set_directive_bind_op -op mul -impl fabric "case_68" m105
set_directive_bind_op -op mul -impl fabric "case_68" m106
set_directive_bind_op -op mul -impl fabric "case_68" m107
set_directive_bind_op -op mul -impl fabric "case_68" m108
set_directive_bind_op -op mul -impl fabric "case_68" m109
set_directive_bind_op -op mul -impl fabric "case_68" m110
set_directive_bind_op -op mul -impl fabric "case_68" m111
set_directive_bind_op -op mul -impl fabric "case_68" m112
set_directive_bind_op -op mul -impl fabric "case_68" m113
set_directive_bind_op -op mul -impl fabric "case_68" m114
set_directive_bind_op -op mul -impl fabric "case_68" m115
set_directive_bind_op -op mul -impl fabric "case_68" m116
set_directive_bind_op -op mul -impl fabric "case_68" m117
set_directive_bind_op -op mul -impl fabric "case_68" m118
set_directive_bind_op -op mul -impl fabric "case_68" m119
set_directive_bind_op -op mul -impl fabric "case_68" m120
set_directive_bind_op -op mul -impl fabric "case_68" m121
set_directive_bind_op -op mul -impl fabric "case_68" m122
set_directive_bind_op -op mul -impl fabric "case_68" m123
set_directive_bind_op -op mul -impl fabric "case_68" m124
set_directive_bind_op -op mul -impl fabric "case_68" m125
set_directive_bind_op -op mul -impl fabric "case_68" m126
set_directive_bind_op -op mul -impl fabric "case_68" m127
set_directive_bind_op -op mul -impl fabric "case_68" m128
set_directive_bind_op -op mul -impl fabric "case_68" m129
set_directive_bind_op -op mul -impl fabric "case_68" m130
set_directive_bind_op -op mul -impl fabric "case_68" m131
set_directive_bind_op -op mul -impl fabric "case_68" m132
set_directive_bind_op -op mul -impl fabric "case_68" m133
set_directive_bind_op -op mul -impl fabric "case_68" m134
set_directive_bind_op -op mul -impl fabric "case_68" m135
set_directive_bind_op -op mul -impl fabric "case_68" m136
set_directive_bind_op -op mul -impl fabric "case_68" m137
set_directive_bind_op -op mul -impl fabric "case_68" m138
set_directive_bind_op -op mul -impl fabric "case_68" m139
set_directive_bind_op -op mul -impl fabric "case_68" m140
set_directive_bind_op -op mul -impl fabric "case_68" m141
set_directive_bind_op -op mul -impl fabric "case_68" m142
set_directive_bind_op -op mul -impl fabric "case_68" m143
set_directive_bind_op -op mul -impl fabric "case_68" m144
set_directive_bind_op -op mul -impl fabric "case_68" m145
set_directive_bind_op -op mul -impl fabric "case_68" m146
set_directive_bind_op -op mul -impl fabric "case_68" m147
set_directive_bind_op -op mul -impl fabric "case_68" m148
set_directive_bind_op -op mul -impl fabric "case_68" m149
set_directive_bind_op -op mul -impl fabric "case_68" m150
set_directive_bind_op -op mul -impl fabric "case_68" m151
set_directive_bind_op -op mul -impl fabric "case_68" m152
set_directive_bind_op -op mul -impl fabric "case_68" m153
set_directive_bind_op -op mul -impl fabric "case_68" m154
set_directive_bind_op -op mul -impl fabric "case_68" m155
set_directive_bind_op -op mul -impl fabric "case_68" m156
set_directive_bind_op -op mul -impl fabric "case_68" m157
set_directive_bind_op -op mul -impl fabric "case_68" m158
set_directive_bind_op -op mul -impl fabric "case_68" m159
set_directive_bind_op -op mul -impl fabric "case_68" m160
set_directive_bind_op -op mul -impl fabric "case_68" m161
set_directive_bind_op -op mul -impl fabric "case_68" m162
set_directive_bind_op -op mul -impl fabric "case_68" m163
set_directive_bind_op -op mul -impl fabric "case_68" m164
set_directive_bind_op -op mul -impl fabric "case_68" m165
set_directive_bind_op -op mul -impl fabric "case_68" m166
set_directive_bind_op -op mul -impl fabric "case_68" m167
set_directive_bind_op -op mul -impl fabric "case_68" m168
set_directive_bind_op -op mul -impl fabric "case_68" m169
set_directive_bind_op -op mul -impl fabric "case_68" m170
set_directive_bind_op -op mul -impl fabric "case_68" m171
set_directive_bind_op -op mul -impl fabric "case_68" m172
set_directive_bind_op -op mul -impl fabric "case_68" m173
set_directive_bind_op -op mul -impl fabric "case_68" m174
set_directive_bind_op -op mul -impl fabric "case_68" m175
set_directive_bind_op -op mul -impl fabric "case_68" m176
set_directive_bind_op -op mul -impl fabric "case_68" m177
set_directive_bind_op -op mul -impl fabric "case_68" m178
set_directive_bind_op -op mul -impl fabric "case_68" m179
set_directive_bind_op -op mul -impl fabric "case_68" m180
set_directive_bind_op -op mul -impl fabric "case_68" m181
set_directive_bind_op -op mul -impl fabric "case_68" m182
set_directive_bind_op -op mul -impl fabric "case_68" m183
set_directive_bind_op -op mul -impl fabric "case_68" m184
set_directive_bind_op -op mul -impl fabric "case_68" m185
set_directive_bind_op -op mul -impl fabric "case_68" m186
set_directive_bind_op -op mul -impl fabric "case_68" m187
set_directive_bind_op -op mul -impl fabric "case_68" m188
set_directive_bind_op -op mul -impl fabric "case_68" m189
set_directive_bind_op -op mul -impl fabric "case_68" m190
set_directive_bind_op -op mul -impl fabric "case_68" m191
set_directive_bind_op -op mul -impl fabric "case_68" m192
set_directive_bind_op -op mul -impl fabric "case_68" m193
set_directive_bind_op -op mul -impl fabric "case_68" m194
set_directive_bind_op -op mul -impl fabric "case_68" m195
set_directive_bind_op -op mul -impl fabric "case_68" m196
set_directive_bind_op -op mul -impl fabric "case_68" m197
set_directive_bind_op -op mul -impl fabric "case_68" m198
set_directive_bind_op -op mul -impl fabric "case_68" m199
set_directive_bind_op -op mul -impl fabric "case_68" m200
set_directive_bind_op -op mul -impl fabric "case_68" m201
set_directive_bind_op -op mul -impl fabric "case_68" m202
set_directive_bind_op -op mul -impl fabric "case_68" m203
set_directive_bind_op -op mul -impl fabric "case_68" m204
set_directive_bind_op -op mul -impl fabric "case_68" m205
set_directive_bind_op -op mul -impl fabric "case_68" m206
set_directive_bind_op -op mul -impl fabric "case_68" m207
set_directive_bind_op -op mul -impl fabric "case_68" m208
set_directive_bind_op -op mul -impl fabric "case_68" m209
set_directive_bind_op -op mul -impl fabric "case_68" m210
set_directive_bind_op -op mul -impl fabric "case_68" m211
set_directive_bind_op -op mul -impl fabric "case_68" m212
set_directive_bind_op -op mul -impl fabric "case_68" m213

