set_directive_bind_op -op mul -impl fabric "case_97" m18
set_directive_bind_op -op mul -impl fabric "case_97" m19
set_directive_bind_op -op mul -impl fabric "case_97" m20
set_directive_bind_op -op mul -impl fabric "case_97" m21
set_directive_bind_op -op mul -impl fabric "case_97" m22
set_directive_bind_op -op mul -impl fabric "case_97" m23
set_directive_bind_op -op mul -impl fabric "case_97" m24
set_directive_bind_op -op mul -impl fabric "case_97" m25
set_directive_bind_op -op mul -impl fabric "case_97" m26
set_directive_bind_op -op mul -impl fabric "case_97" m27
set_directive_bind_op -op mul -impl fabric "case_97" m28
set_directive_bind_op -op mul -impl fabric "case_97" m29
set_directive_bind_op -op mul -impl fabric "case_97" m30
set_directive_bind_op -op mul -impl fabric "case_97" m31
set_directive_bind_op -op mul -impl fabric "case_97" m32
set_directive_bind_op -op mul -impl fabric "case_97" m33
set_directive_bind_op -op mul -impl fabric "case_97" m34
set_directive_bind_op -op mul -impl fabric "case_97" m35
set_directive_bind_op -op mul -impl fabric "case_97" m36
set_directive_bind_op -op mul -impl fabric "case_97" m37
set_directive_bind_op -op mul -impl fabric "case_97" m38
set_directive_bind_op -op mul -impl fabric "case_97" m39
set_directive_bind_op -op mul -impl fabric "case_97" m40
set_directive_bind_op -op mul -impl fabric "case_97" m41
set_directive_bind_op -op mul -impl fabric "case_97" m42
set_directive_bind_op -op mul -impl fabric "case_97" m43
set_directive_bind_op -op mul -impl fabric "case_97" m44
set_directive_bind_op -op mul -impl fabric "case_97" m45
set_directive_bind_op -op mul -impl fabric "case_97" m46
set_directive_bind_op -op mul -impl fabric "case_97" m47
set_directive_bind_op -op mul -impl fabric "case_97" m48
set_directive_bind_op -op mul -impl fabric "case_97" m49
set_directive_bind_op -op mul -impl fabric "case_97" m50
set_directive_bind_op -op mul -impl fabric "case_97" m51
set_directive_bind_op -op mul -impl fabric "case_97" m52
set_directive_bind_op -op mul -impl fabric "case_97" m53
set_directive_bind_op -op mul -impl fabric "case_97" m54
set_directive_bind_op -op mul -impl fabric "case_97" m55
set_directive_bind_op -op mul -impl fabric "case_97" m56
set_directive_bind_op -op mul -impl fabric "case_97" m57
set_directive_bind_op -op mul -impl fabric "case_97" m58
set_directive_bind_op -op mul -impl fabric "case_97" m59
set_directive_bind_op -op mul -impl fabric "case_97" m60
set_directive_bind_op -op mul -impl fabric "case_97" m61
set_directive_bind_op -op mul -impl fabric "case_97" m62
set_directive_bind_op -op mul -impl fabric "case_97" m63
set_directive_bind_op -op mul -impl fabric "case_97" m64
set_directive_bind_op -op mul -impl fabric "case_97" m65
set_directive_bind_op -op mul -impl fabric "case_97" m66
set_directive_bind_op -op mul -impl fabric "case_97" m67
set_directive_bind_op -op mul -impl fabric "case_97" m68
set_directive_bind_op -op mul -impl fabric "case_97" m69
set_directive_bind_op -op mul -impl fabric "case_97" m70
set_directive_bind_op -op mul -impl fabric "case_97" m71
set_directive_bind_op -op mul -impl fabric "case_97" m72
set_directive_bind_op -op mul -impl fabric "case_97" m73
set_directive_bind_op -op mul -impl fabric "case_97" m74
set_directive_bind_op -op mul -impl fabric "case_97" m75
set_directive_bind_op -op mul -impl fabric "case_97" m76
set_directive_bind_op -op mul -impl fabric "case_97" m77
set_directive_bind_op -op mul -impl fabric "case_97" m78
set_directive_bind_op -op mul -impl fabric "case_97" m79
set_directive_bind_op -op mul -impl fabric "case_97" m80
set_directive_bind_op -op mul -impl fabric "case_97" m81
set_directive_bind_op -op mul -impl fabric "case_97" m82
set_directive_bind_op -op mul -impl fabric "case_97" m83
set_directive_bind_op -op mul -impl fabric "case_97" m84
set_directive_bind_op -op mul -impl fabric "case_97" m85
set_directive_bind_op -op mul -impl fabric "case_97" m86
set_directive_bind_op -op mul -impl fabric "case_97" m87
set_directive_bind_op -op mul -impl fabric "case_97" m88
set_directive_bind_op -op mul -impl fabric "case_97" m89
set_directive_bind_op -op mul -impl fabric "case_97" m90
set_directive_bind_op -op mul -impl fabric "case_97" m91
set_directive_bind_op -op mul -impl fabric "case_97" m92
set_directive_bind_op -op mul -impl fabric "case_97" m93
set_directive_bind_op -op mul -impl fabric "case_97" m94
set_directive_bind_op -op mul -impl fabric "case_97" m95
set_directive_bind_op -op mul -impl fabric "case_97" m96
set_directive_bind_op -op mul -impl fabric "case_97" m97
set_directive_bind_op -op mul -impl fabric "case_97" m98
set_directive_bind_op -op mul -impl fabric "case_97" m99
set_directive_bind_op -op mul -impl fabric "case_97" m100
set_directive_bind_op -op mul -impl fabric "case_97" m101
set_directive_bind_op -op mul -impl fabric "case_97" m102
set_directive_bind_op -op mul -impl fabric "case_97" m103
set_directive_bind_op -op mul -impl fabric "case_97" m104
set_directive_bind_op -op mul -impl fabric "case_97" m105
set_directive_bind_op -op mul -impl fabric "case_97" m106
set_directive_bind_op -op mul -impl fabric "case_97" m107
set_directive_bind_op -op mul -impl fabric "case_97" m108
set_directive_bind_op -op mul -impl fabric "case_97" m109
set_directive_bind_op -op mul -impl fabric "case_97" m110
set_directive_bind_op -op mul -impl fabric "case_97" m111
set_directive_bind_op -op mul -impl fabric "case_97" m112
set_directive_bind_op -op mul -impl fabric "case_97" m113
set_directive_bind_op -op mul -impl fabric "case_97" m114
set_directive_bind_op -op mul -impl fabric "case_97" m115
set_directive_bind_op -op mul -impl fabric "case_97" m116
set_directive_bind_op -op mul -impl fabric "case_97" m117
set_directive_bind_op -op mul -impl fabric "case_97" m118
set_directive_bind_op -op mul -impl fabric "case_97" m119
set_directive_bind_op -op mul -impl fabric "case_97" m120
set_directive_bind_op -op mul -impl fabric "case_97" m121
set_directive_bind_op -op mul -impl fabric "case_97" m122
set_directive_bind_op -op mul -impl fabric "case_97" m123
set_directive_bind_op -op mul -impl fabric "case_97" m124
set_directive_bind_op -op mul -impl fabric "case_97" m125
set_directive_bind_op -op mul -impl fabric "case_97" m126
set_directive_bind_op -op mul -impl fabric "case_97" m127
set_directive_bind_op -op mul -impl fabric "case_97" m128
set_directive_bind_op -op mul -impl fabric "case_97" m129
set_directive_bind_op -op mul -impl fabric "case_97" m130
set_directive_bind_op -op mul -impl fabric "case_97" m131
set_directive_bind_op -op mul -impl fabric "case_97" m132
set_directive_bind_op -op mul -impl fabric "case_97" m133
set_directive_bind_op -op mul -impl fabric "case_97" m134
set_directive_bind_op -op mul -impl fabric "case_97" m135
set_directive_bind_op -op mul -impl fabric "case_97" m136
set_directive_bind_op -op mul -impl fabric "case_97" m137
set_directive_bind_op -op mul -impl fabric "case_97" m138
set_directive_bind_op -op mul -impl fabric "case_97" m139
set_directive_bind_op -op mul -impl fabric "case_97" m140
set_directive_bind_op -op mul -impl fabric "case_97" m141
set_directive_bind_op -op mul -impl fabric "case_97" m142
set_directive_bind_op -op mul -impl fabric "case_97" m143
set_directive_bind_op -op mul -impl fabric "case_97" m144
set_directive_bind_op -op mul -impl fabric "case_97" m145
set_directive_bind_op -op mul -impl fabric "case_97" m146
set_directive_bind_op -op mul -impl fabric "case_97" m147
set_directive_bind_op -op mul -impl fabric "case_97" m148
set_directive_bind_op -op mul -impl fabric "case_97" m149
set_directive_bind_op -op mul -impl fabric "case_97" m150
set_directive_bind_op -op mul -impl fabric "case_97" m151

