set_directive_bind_op -op mul -impl fabric "case_90" m13
set_directive_bind_op -op mul -impl fabric "case_90" m14
set_directive_bind_op -op mul -impl fabric "case_90" m15
set_directive_bind_op -op mul -impl fabric "case_90" m16
set_directive_bind_op -op mul -impl fabric "case_90" m17
set_directive_bind_op -op mul -impl fabric "case_90" m18
set_directive_bind_op -op mul -impl fabric "case_90" m19
set_directive_bind_op -op mul -impl fabric "case_90" m20
set_directive_bind_op -op mul -impl fabric "case_90" m21
set_directive_bind_op -op mul -impl fabric "case_90" m22
set_directive_bind_op -op mul -impl fabric "case_90" m23
set_directive_bind_op -op mul -impl fabric "case_90" m24
set_directive_bind_op -op mul -impl fabric "case_90" m25
set_directive_bind_op -op mul -impl fabric "case_90" m26
set_directive_bind_op -op mul -impl fabric "case_90" m27
set_directive_bind_op -op mul -impl fabric "case_90" m28
set_directive_bind_op -op mul -impl fabric "case_90" m29
set_directive_bind_op -op mul -impl fabric "case_90" m30
set_directive_bind_op -op mul -impl fabric "case_90" m31
set_directive_bind_op -op mul -impl fabric "case_90" m32
set_directive_bind_op -op mul -impl fabric "case_90" m33
set_directive_bind_op -op mul -impl fabric "case_90" m34
set_directive_bind_op -op mul -impl fabric "case_90" m35
set_directive_bind_op -op mul -impl fabric "case_90" m36
set_directive_bind_op -op mul -impl fabric "case_90" m37
set_directive_bind_op -op mul -impl fabric "case_90" m38
set_directive_bind_op -op mul -impl fabric "case_90" m39
set_directive_bind_op -op mul -impl fabric "case_90" m40
set_directive_bind_op -op mul -impl fabric "case_90" m41
set_directive_bind_op -op mul -impl fabric "case_90" m42
set_directive_bind_op -op mul -impl fabric "case_90" m43
set_directive_bind_op -op mul -impl fabric "case_90" m44
set_directive_bind_op -op mul -impl fabric "case_90" m45
set_directive_bind_op -op mul -impl fabric "case_90" m46
set_directive_bind_op -op mul -impl fabric "case_90" m47
set_directive_bind_op -op mul -impl fabric "case_90" m48
set_directive_bind_op -op mul -impl fabric "case_90" m49
set_directive_bind_op -op mul -impl fabric "case_90" m50
set_directive_bind_op -op mul -impl fabric "case_90" m51
set_directive_bind_op -op mul -impl fabric "case_90" m52
set_directive_bind_op -op mul -impl fabric "case_90" m53
set_directive_bind_op -op mul -impl fabric "case_90" m54
set_directive_bind_op -op mul -impl fabric "case_90" m55
set_directive_bind_op -op mul -impl fabric "case_90" m56
set_directive_bind_op -op mul -impl fabric "case_90" m57
set_directive_bind_op -op mul -impl fabric "case_90" m58
set_directive_bind_op -op mul -impl fabric "case_90" m59
set_directive_bind_op -op mul -impl fabric "case_90" m60
set_directive_bind_op -op mul -impl fabric "case_90" m61
set_directive_bind_op -op mul -impl fabric "case_90" m62
set_directive_bind_op -op mul -impl fabric "case_90" m63
set_directive_bind_op -op mul -impl fabric "case_90" m64
set_directive_bind_op -op mul -impl fabric "case_90" m65
set_directive_bind_op -op mul -impl fabric "case_90" m66
set_directive_bind_op -op mul -impl fabric "case_90" m67
set_directive_bind_op -op mul -impl fabric "case_90" m68
set_directive_bind_op -op mul -impl fabric "case_90" m69
set_directive_bind_op -op mul -impl fabric "case_90" m70
set_directive_bind_op -op mul -impl fabric "case_90" m71
set_directive_bind_op -op mul -impl fabric "case_90" m72
set_directive_bind_op -op mul -impl fabric "case_90" m73
set_directive_bind_op -op mul -impl fabric "case_90" m74
set_directive_bind_op -op mul -impl fabric "case_90" m75
set_directive_bind_op -op mul -impl fabric "case_90" m76
set_directive_bind_op -op mul -impl fabric "case_90" m77
set_directive_bind_op -op mul -impl fabric "case_90" m78
set_directive_bind_op -op mul -impl fabric "case_90" m79
set_directive_bind_op -op mul -impl fabric "case_90" m80
set_directive_bind_op -op mul -impl fabric "case_90" m81
set_directive_bind_op -op mul -impl fabric "case_90" m82
set_directive_bind_op -op mul -impl fabric "case_90" m83
set_directive_bind_op -op mul -impl fabric "case_90" m84
set_directive_bind_op -op mul -impl fabric "case_90" m85
set_directive_bind_op -op mul -impl fabric "case_90" m86
set_directive_bind_op -op mul -impl fabric "case_90" m87
set_directive_bind_op -op mul -impl fabric "case_90" m88
set_directive_bind_op -op mul -impl fabric "case_90" m89
set_directive_bind_op -op mul -impl fabric "case_90" m90
set_directive_bind_op -op mul -impl fabric "case_90" m91
set_directive_bind_op -op mul -impl fabric "case_90" m92
set_directive_bind_op -op mul -impl fabric "case_90" m93
set_directive_bind_op -op mul -impl fabric "case_90" m94
set_directive_bind_op -op mul -impl fabric "case_90" m95
set_directive_bind_op -op mul -impl fabric "case_90" m96
set_directive_bind_op -op mul -impl fabric "case_90" m97
set_directive_bind_op -op mul -impl fabric "case_90" m98
set_directive_bind_op -op mul -impl fabric "case_90" m99
set_directive_bind_op -op mul -impl fabric "case_90" m100
set_directive_bind_op -op mul -impl fabric "case_90" m101
set_directive_bind_op -op mul -impl fabric "case_90" m102
set_directive_bind_op -op mul -impl fabric "case_90" m103
set_directive_bind_op -op mul -impl fabric "case_90" m104
set_directive_bind_op -op mul -impl fabric "case_90" m105
set_directive_bind_op -op mul -impl fabric "case_90" m106
set_directive_bind_op -op mul -impl fabric "case_90" m107
set_directive_bind_op -op mul -impl fabric "case_90" m108
set_directive_bind_op -op mul -impl fabric "case_90" m109
set_directive_bind_op -op mul -impl fabric "case_90" m110
set_directive_bind_op -op mul -impl fabric "case_90" m111
set_directive_bind_op -op mul -impl fabric "case_90" m112
set_directive_bind_op -op mul -impl fabric "case_90" m113
set_directive_bind_op -op mul -impl fabric "case_90" m114
set_directive_bind_op -op mul -impl fabric "case_90" m115
set_directive_bind_op -op mul -impl fabric "case_90" m116
set_directive_bind_op -op mul -impl fabric "case_90" m117
set_directive_bind_op -op mul -impl fabric "case_90" m118
set_directive_bind_op -op mul -impl fabric "case_90" m119
set_directive_bind_op -op mul -impl fabric "case_90" m120
set_directive_bind_op -op mul -impl fabric "case_90" m121
set_directive_bind_op -op mul -impl fabric "case_90" m122
set_directive_bind_op -op mul -impl fabric "case_90" m123
set_directive_bind_op -op mul -impl fabric "case_90" m124
set_directive_bind_op -op mul -impl fabric "case_90" m125
set_directive_bind_op -op mul -impl fabric "case_90" m126
set_directive_bind_op -op mul -impl fabric "case_90" m127

