set_directive_bind_op -op mul -impl fabric "case_98" m18
set_directive_bind_op -op mul -impl fabric "case_98" m19
set_directive_bind_op -op mul -impl fabric "case_98" m20
set_directive_bind_op -op mul -impl fabric "case_98" m21
set_directive_bind_op -op mul -impl fabric "case_98" m22
set_directive_bind_op -op mul -impl fabric "case_98" m23
set_directive_bind_op -op mul -impl fabric "case_98" m24
set_directive_bind_op -op mul -impl fabric "case_98" m25
set_directive_bind_op -op mul -impl fabric "case_98" m26
set_directive_bind_op -op mul -impl fabric "case_98" m27
set_directive_bind_op -op mul -impl fabric "case_98" m28
set_directive_bind_op -op mul -impl fabric "case_98" m29
set_directive_bind_op -op mul -impl fabric "case_98" m30
set_directive_bind_op -op mul -impl fabric "case_98" m31
set_directive_bind_op -op mul -impl fabric "case_98" m32
set_directive_bind_op -op mul -impl fabric "case_98" m33
set_directive_bind_op -op mul -impl fabric "case_98" m34
set_directive_bind_op -op mul -impl fabric "case_98" m35
set_directive_bind_op -op mul -impl fabric "case_98" m36
set_directive_bind_op -op mul -impl fabric "case_98" m37
set_directive_bind_op -op mul -impl fabric "case_98" m38
set_directive_bind_op -op mul -impl fabric "case_98" m39
set_directive_bind_op -op mul -impl fabric "case_98" m40
set_directive_bind_op -op mul -impl fabric "case_98" m41
set_directive_bind_op -op mul -impl fabric "case_98" m42
set_directive_bind_op -op mul -impl fabric "case_98" m43
set_directive_bind_op -op mul -impl fabric "case_98" m44
set_directive_bind_op -op mul -impl fabric "case_98" m45
set_directive_bind_op -op mul -impl fabric "case_98" m46
set_directive_bind_op -op mul -impl fabric "case_98" m47
set_directive_bind_op -op mul -impl fabric "case_98" m48
set_directive_bind_op -op mul -impl fabric "case_98" m49
set_directive_bind_op -op mul -impl fabric "case_98" m50
set_directive_bind_op -op mul -impl fabric "case_98" m51
set_directive_bind_op -op mul -impl fabric "case_98" m52
set_directive_bind_op -op mul -impl fabric "case_98" m53
set_directive_bind_op -op mul -impl fabric "case_98" m54
set_directive_bind_op -op mul -impl fabric "case_98" m55
set_directive_bind_op -op mul -impl fabric "case_98" m56
set_directive_bind_op -op mul -impl fabric "case_98" m57
set_directive_bind_op -op mul -impl fabric "case_98" m58
set_directive_bind_op -op mul -impl fabric "case_98" m59
set_directive_bind_op -op mul -impl fabric "case_98" m60
set_directive_bind_op -op mul -impl fabric "case_98" m61
set_directive_bind_op -op mul -impl fabric "case_98" m62
set_directive_bind_op -op mul -impl fabric "case_98" m63
set_directive_bind_op -op mul -impl fabric "case_98" m64
set_directive_bind_op -op mul -impl fabric "case_98" m65
set_directive_bind_op -op mul -impl fabric "case_98" m66
set_directive_bind_op -op mul -impl fabric "case_98" m67
set_directive_bind_op -op mul -impl fabric "case_98" m68
set_directive_bind_op -op mul -impl fabric "case_98" m69
set_directive_bind_op -op mul -impl fabric "case_98" m70
set_directive_bind_op -op mul -impl fabric "case_98" m71
set_directive_bind_op -op mul -impl fabric "case_98" m72
set_directive_bind_op -op mul -impl fabric "case_98" m73
set_directive_bind_op -op mul -impl fabric "case_98" m74
set_directive_bind_op -op mul -impl fabric "case_98" m75
set_directive_bind_op -op mul -impl fabric "case_98" m76
set_directive_bind_op -op mul -impl fabric "case_98" m77
set_directive_bind_op -op mul -impl fabric "case_98" m78
set_directive_bind_op -op mul -impl fabric "case_98" m79
set_directive_bind_op -op mul -impl fabric "case_98" m80
set_directive_bind_op -op mul -impl fabric "case_98" m81
set_directive_bind_op -op mul -impl fabric "case_98" m82
set_directive_bind_op -op mul -impl fabric "case_98" m83
set_directive_bind_op -op mul -impl fabric "case_98" m84
set_directive_bind_op -op mul -impl fabric "case_98" m85
set_directive_bind_op -op mul -impl fabric "case_98" m86
set_directive_bind_op -op mul -impl fabric "case_98" m87
set_directive_bind_op -op mul -impl fabric "case_98" m88
set_directive_bind_op -op mul -impl fabric "case_98" m89
set_directive_bind_op -op mul -impl fabric "case_98" m90
set_directive_bind_op -op mul -impl fabric "case_98" m91
set_directive_bind_op -op mul -impl fabric "case_98" m92
set_directive_bind_op -op mul -impl fabric "case_98" m93
set_directive_bind_op -op mul -impl fabric "case_98" m94
set_directive_bind_op -op mul -impl fabric "case_98" m95
set_directive_bind_op -op mul -impl fabric "case_98" m96
set_directive_bind_op -op mul -impl fabric "case_98" m97
set_directive_bind_op -op mul -impl fabric "case_98" m98
set_directive_bind_op -op mul -impl fabric "case_98" m99
set_directive_bind_op -op mul -impl fabric "case_98" m100
set_directive_bind_op -op mul -impl fabric "case_98" m101
set_directive_bind_op -op mul -impl fabric "case_98" m102
set_directive_bind_op -op mul -impl fabric "case_98" m103
set_directive_bind_op -op mul -impl fabric "case_98" m104
set_directive_bind_op -op mul -impl fabric "case_98" m105
set_directive_bind_op -op mul -impl fabric "case_98" m106
set_directive_bind_op -op mul -impl fabric "case_98" m107
set_directive_bind_op -op mul -impl fabric "case_98" m108
set_directive_bind_op -op mul -impl fabric "case_98" m109
set_directive_bind_op -op mul -impl fabric "case_98" m110
set_directive_bind_op -op mul -impl fabric "case_98" m111
set_directive_bind_op -op mul -impl fabric "case_98" m112
set_directive_bind_op -op mul -impl fabric "case_98" m113
set_directive_bind_op -op mul -impl fabric "case_98" m114
set_directive_bind_op -op mul -impl fabric "case_98" m115
set_directive_bind_op -op mul -impl fabric "case_98" m116
set_directive_bind_op -op mul -impl fabric "case_98" m117
set_directive_bind_op -op mul -impl fabric "case_98" m118
set_directive_bind_op -op mul -impl fabric "case_98" m119
set_directive_bind_op -op mul -impl fabric "case_98" m120
set_directive_bind_op -op mul -impl fabric "case_98" m121
set_directive_bind_op -op mul -impl fabric "case_98" m122
set_directive_bind_op -op mul -impl fabric "case_98" m123
set_directive_bind_op -op mul -impl fabric "case_98" m124
set_directive_bind_op -op mul -impl fabric "case_98" m125
set_directive_bind_op -op mul -impl fabric "case_98" m126
set_directive_bind_op -op mul -impl fabric "case_98" m127
set_directive_bind_op -op mul -impl fabric "case_98" m128
set_directive_bind_op -op mul -impl fabric "case_98" m129
set_directive_bind_op -op mul -impl fabric "case_98" m130
set_directive_bind_op -op mul -impl fabric "case_98" m131
set_directive_bind_op -op mul -impl fabric "case_98" m132
set_directive_bind_op -op mul -impl fabric "case_98" m133
set_directive_bind_op -op mul -impl fabric "case_98" m134
set_directive_bind_op -op mul -impl fabric "case_98" m135
set_directive_bind_op -op mul -impl fabric "case_98" m136
set_directive_bind_op -op mul -impl fabric "case_98" m137
set_directive_bind_op -op mul -impl fabric "case_98" m138
set_directive_bind_op -op mul -impl fabric "case_98" m139
set_directive_bind_op -op mul -impl fabric "case_98" m140
set_directive_bind_op -op mul -impl fabric "case_98" m141
set_directive_bind_op -op mul -impl fabric "case_98" m142
set_directive_bind_op -op mul -impl fabric "case_98" m143
set_directive_bind_op -op mul -impl fabric "case_98" m144
set_directive_bind_op -op mul -impl fabric "case_98" m145
set_directive_bind_op -op mul -impl fabric "case_98" m146
set_directive_bind_op -op mul -impl fabric "case_98" m147
set_directive_bind_op -op mul -impl fabric "case_98" m148
set_directive_bind_op -op mul -impl fabric "case_98" m149
set_directive_bind_op -op mul -impl fabric "case_98" m150
set_directive_bind_op -op mul -impl fabric "case_98" m151
set_directive_bind_op -op mul -impl fabric "case_98" m152
set_directive_bind_op -op mul -impl fabric "case_98" m153
set_directive_bind_op -op mul -impl fabric "case_98" m154

