set_directive_bind_op -op mul -impl fabric "case_70" m12
set_directive_bind_op -op mul -impl fabric "case_70" m13
set_directive_bind_op -op mul -impl fabric "case_70" m14
set_directive_bind_op -op mul -impl fabric "case_70" m15
set_directive_bind_op -op mul -impl fabric "case_70" m16
set_directive_bind_op -op mul -impl fabric "case_70" m17
set_directive_bind_op -op mul -impl fabric "case_70" m18
set_directive_bind_op -op mul -impl fabric "case_70" m19
set_directive_bind_op -op mul -impl fabric "case_70" m20
set_directive_bind_op -op mul -impl fabric "case_70" m21
set_directive_bind_op -op mul -impl fabric "case_70" m22
set_directive_bind_op -op mul -impl fabric "case_70" m23
set_directive_bind_op -op mul -impl fabric "case_70" m24
set_directive_bind_op -op mul -impl fabric "case_70" m25
set_directive_bind_op -op mul -impl fabric "case_70" m26
set_directive_bind_op -op mul -impl fabric "case_70" m27
set_directive_bind_op -op mul -impl fabric "case_70" m28
set_directive_bind_op -op mul -impl fabric "case_70" m29
set_directive_bind_op -op mul -impl fabric "case_70" m30
set_directive_bind_op -op mul -impl fabric "case_70" m31
set_directive_bind_op -op mul -impl fabric "case_70" m32
set_directive_bind_op -op mul -impl fabric "case_70" m33
set_directive_bind_op -op mul -impl fabric "case_70" m34
set_directive_bind_op -op mul -impl fabric "case_70" m35
set_directive_bind_op -op mul -impl fabric "case_70" m36
set_directive_bind_op -op mul -impl fabric "case_70" m37
set_directive_bind_op -op mul -impl fabric "case_70" m38
set_directive_bind_op -op mul -impl fabric "case_70" m39
set_directive_bind_op -op mul -impl fabric "case_70" m40
set_directive_bind_op -op mul -impl fabric "case_70" m41
set_directive_bind_op -op mul -impl fabric "case_70" m42
set_directive_bind_op -op mul -impl fabric "case_70" m43
set_directive_bind_op -op mul -impl fabric "case_70" m44
set_directive_bind_op -op mul -impl fabric "case_70" m45
set_directive_bind_op -op mul -impl fabric "case_70" m46
set_directive_bind_op -op mul -impl fabric "case_70" m47
set_directive_bind_op -op mul -impl fabric "case_70" m48
set_directive_bind_op -op mul -impl fabric "case_70" m49
set_directive_bind_op -op mul -impl fabric "case_70" m50
set_directive_bind_op -op mul -impl fabric "case_70" m51
set_directive_bind_op -op mul -impl fabric "case_70" m52
set_directive_bind_op -op mul -impl fabric "case_70" m53
set_directive_bind_op -op mul -impl fabric "case_70" m54
set_directive_bind_op -op mul -impl fabric "case_70" m55
set_directive_bind_op -op mul -impl fabric "case_70" m56
set_directive_bind_op -op mul -impl fabric "case_70" m57
set_directive_bind_op -op mul -impl fabric "case_70" m58
set_directive_bind_op -op mul -impl fabric "case_70" m59
set_directive_bind_op -op mul -impl fabric "case_70" m60
set_directive_bind_op -op mul -impl fabric "case_70" m61
set_directive_bind_op -op mul -impl fabric "case_70" m62
set_directive_bind_op -op mul -impl fabric "case_70" m63
set_directive_bind_op -op mul -impl fabric "case_70" m64
set_directive_bind_op -op mul -impl fabric "case_70" m65
set_directive_bind_op -op mul -impl fabric "case_70" m66
set_directive_bind_op -op mul -impl fabric "case_70" m67
set_directive_bind_op -op mul -impl fabric "case_70" m68
set_directive_bind_op -op mul -impl fabric "case_70" m69
set_directive_bind_op -op mul -impl fabric "case_70" m70
set_directive_bind_op -op mul -impl fabric "case_70" m71
set_directive_bind_op -op mul -impl fabric "case_70" m72
set_directive_bind_op -op mul -impl fabric "case_70" m73
set_directive_bind_op -op mul -impl fabric "case_70" m74
set_directive_bind_op -op mul -impl fabric "case_70" m75
set_directive_bind_op -op mul -impl fabric "case_70" m76
set_directive_bind_op -op mul -impl fabric "case_70" m77
set_directive_bind_op -op mul -impl fabric "case_70" m78
set_directive_bind_op -op mul -impl fabric "case_70" m79
set_directive_bind_op -op mul -impl fabric "case_70" m80
set_directive_bind_op -op mul -impl fabric "case_70" m81
set_directive_bind_op -op mul -impl fabric "case_70" m82
set_directive_bind_op -op mul -impl fabric "case_70" m83
set_directive_bind_op -op mul -impl fabric "case_70" m84
set_directive_bind_op -op mul -impl fabric "case_70" m85
set_directive_bind_op -op mul -impl fabric "case_70" m86
set_directive_bind_op -op mul -impl fabric "case_70" m87
set_directive_bind_op -op mul -impl fabric "case_70" m88
set_directive_bind_op -op mul -impl fabric "case_70" m89
set_directive_bind_op -op mul -impl fabric "case_70" m90
set_directive_bind_op -op mul -impl fabric "case_70" m91
set_directive_bind_op -op mul -impl fabric "case_70" m92
set_directive_bind_op -op mul -impl fabric "case_70" m93
set_directive_bind_op -op mul -impl fabric "case_70" m94
set_directive_bind_op -op mul -impl fabric "case_70" m95
set_directive_bind_op -op mul -impl fabric "case_70" m96
set_directive_bind_op -op mul -impl fabric "case_70" m97
set_directive_bind_op -op mul -impl fabric "case_70" m98
set_directive_bind_op -op mul -impl fabric "case_70" m99
set_directive_bind_op -op mul -impl fabric "case_70" m100
set_directive_bind_op -op mul -impl fabric "case_70" m101
set_directive_bind_op -op mul -impl fabric "case_70" m102
set_directive_bind_op -op mul -impl fabric "case_70" m103
set_directive_bind_op -op mul -impl fabric "case_70" m104
set_directive_bind_op -op mul -impl fabric "case_70" m105
set_directive_bind_op -op mul -impl fabric "case_70" m106
set_directive_bind_op -op mul -impl fabric "case_70" m107
set_directive_bind_op -op mul -impl fabric "case_70" m108
set_directive_bind_op -op mul -impl fabric "case_70" m109
set_directive_bind_op -op mul -impl fabric "case_70" m110
set_directive_bind_op -op mul -impl fabric "case_70" m111
set_directive_bind_op -op mul -impl fabric "case_70" m112
set_directive_bind_op -op mul -impl fabric "case_70" m113
set_directive_bind_op -op mul -impl fabric "case_70" m114
set_directive_bind_op -op mul -impl fabric "case_70" m115
set_directive_bind_op -op mul -impl fabric "case_70" m116
set_directive_bind_op -op mul -impl fabric "case_70" m117
set_directive_bind_op -op mul -impl fabric "case_70" m118
set_directive_bind_op -op mul -impl fabric "case_70" m119
set_directive_bind_op -op mul -impl fabric "case_70" m120
set_directive_bind_op -op mul -impl fabric "case_70" m121
set_directive_bind_op -op mul -impl fabric "case_70" m122
set_directive_bind_op -op mul -impl fabric "case_70" m123
set_directive_bind_op -op mul -impl fabric "case_70" m124
set_directive_bind_op -op mul -impl fabric "case_70" m125
set_directive_bind_op -op mul -impl fabric "case_70" m126
set_directive_bind_op -op mul -impl fabric "case_70" m127

