set_directive_bind_op -op mul -impl fabric "case_10" m10
set_directive_bind_op -op mul -impl fabric "case_10" m11
set_directive_bind_op -op mul -impl fabric "case_10" m12
set_directive_bind_op -op mul -impl fabric "case_10" m13
set_directive_bind_op -op mul -impl fabric "case_10" m14
set_directive_bind_op -op mul -impl fabric "case_10" m15
set_directive_bind_op -op mul -impl fabric "case_10" m16
set_directive_bind_op -op mul -impl fabric "case_10" m17
set_directive_bind_op -op mul -impl fabric "case_10" m18
set_directive_bind_op -op mul -impl fabric "case_10" m19
set_directive_bind_op -op mul -impl fabric "case_10" m20
set_directive_bind_op -op mul -impl fabric "case_10" m21
set_directive_bind_op -op mul -impl fabric "case_10" m22
set_directive_bind_op -op mul -impl fabric "case_10" m23
set_directive_bind_op -op mul -impl fabric "case_10" m24
set_directive_bind_op -op mul -impl fabric "case_10" m25
set_directive_bind_op -op mul -impl fabric "case_10" m26
set_directive_bind_op -op mul -impl fabric "case_10" m27
set_directive_bind_op -op mul -impl fabric "case_10" m28
set_directive_bind_op -op mul -impl fabric "case_10" m29
set_directive_bind_op -op mul -impl fabric "case_10" m30
set_directive_bind_op -op mul -impl fabric "case_10" m31
set_directive_bind_op -op mul -impl fabric "case_10" m32
set_directive_bind_op -op mul -impl fabric "case_10" m33
set_directive_bind_op -op mul -impl fabric "case_10" m34
set_directive_bind_op -op mul -impl fabric "case_10" m35
set_directive_bind_op -op mul -impl fabric "case_10" m36
set_directive_bind_op -op mul -impl fabric "case_10" m37
set_directive_bind_op -op mul -impl fabric "case_10" m38
set_directive_bind_op -op mul -impl fabric "case_10" m39
set_directive_bind_op -op mul -impl fabric "case_10" m40
set_directive_bind_op -op mul -impl fabric "case_10" m41
set_directive_bind_op -op mul -impl fabric "case_10" m42
set_directive_bind_op -op mul -impl fabric "case_10" m43
set_directive_bind_op -op mul -impl fabric "case_10" m44
set_directive_bind_op -op mul -impl fabric "case_10" m45
set_directive_bind_op -op mul -impl fabric "case_10" m46
set_directive_bind_op -op mul -impl fabric "case_10" m47
set_directive_bind_op -op mul -impl fabric "case_10" m48
set_directive_bind_op -op mul -impl fabric "case_10" m49
set_directive_bind_op -op mul -impl fabric "case_10" m50
set_directive_bind_op -op mul -impl fabric "case_10" m51
set_directive_bind_op -op mul -impl fabric "case_10" m52
set_directive_bind_op -op mul -impl fabric "case_10" m53
set_directive_bind_op -op mul -impl fabric "case_10" m54
set_directive_bind_op -op mul -impl fabric "case_10" m55
set_directive_bind_op -op mul -impl fabric "case_10" m56
set_directive_bind_op -op mul -impl fabric "case_10" m57
set_directive_bind_op -op mul -impl fabric "case_10" m58
set_directive_bind_op -op mul -impl fabric "case_10" m59
set_directive_bind_op -op mul -impl fabric "case_10" m60
set_directive_bind_op -op mul -impl fabric "case_10" m61
set_directive_bind_op -op mul -impl fabric "case_10" m62
set_directive_bind_op -op mul -impl fabric "case_10" m63
set_directive_bind_op -op mul -impl fabric "case_10" m64
set_directive_bind_op -op mul -impl fabric "case_10" m65
set_directive_bind_op -op mul -impl fabric "case_10" m66
set_directive_bind_op -op mul -impl fabric "case_10" m67
set_directive_bind_op -op mul -impl fabric "case_10" m68
set_directive_bind_op -op mul -impl fabric "case_10" m69
set_directive_bind_op -op mul -impl fabric "case_10" m70
set_directive_bind_op -op mul -impl fabric "case_10" m71
set_directive_bind_op -op mul -impl fabric "case_10" m72
set_directive_bind_op -op mul -impl fabric "case_10" m73
set_directive_bind_op -op mul -impl fabric "case_10" m74
set_directive_bind_op -op mul -impl fabric "case_10" m75
set_directive_bind_op -op mul -impl fabric "case_10" m76
set_directive_bind_op -op mul -impl fabric "case_10" m77
set_directive_bind_op -op mul -impl fabric "case_10" m78
set_directive_bind_op -op mul -impl fabric "case_10" m79
set_directive_bind_op -op mul -impl fabric "case_10" m80
set_directive_bind_op -op mul -impl fabric "case_10" m81
set_directive_bind_op -op mul -impl fabric "case_10" m82
set_directive_bind_op -op mul -impl fabric "case_10" m83
set_directive_bind_op -op mul -impl fabric "case_10" m84
set_directive_bind_op -op mul -impl fabric "case_10" m85
set_directive_bind_op -op mul -impl fabric "case_10" m86
set_directive_bind_op -op mul -impl fabric "case_10" m87
set_directive_bind_op -op mul -impl fabric "case_10" m88
set_directive_bind_op -op mul -impl fabric "case_10" m89
set_directive_bind_op -op mul -impl fabric "case_10" m90
set_directive_bind_op -op mul -impl fabric "case_10" m91
set_directive_bind_op -op mul -impl fabric "case_10" m92
set_directive_bind_op -op mul -impl fabric "case_10" m93
set_directive_bind_op -op mul -impl fabric "case_10" m94
set_directive_bind_op -op mul -impl fabric "case_10" m95
set_directive_bind_op -op mul -impl fabric "case_10" m96
set_directive_bind_op -op mul -impl fabric "case_10" m97
set_directive_bind_op -op mul -impl fabric "case_10" m98
set_directive_bind_op -op mul -impl fabric "case_10" m99
set_directive_bind_op -op mul -impl fabric "case_10" m100
set_directive_bind_op -op mul -impl fabric "case_10" m101
set_directive_bind_op -op mul -impl fabric "case_10" m102
set_directive_bind_op -op mul -impl fabric "case_10" m103
set_directive_bind_op -op mul -impl fabric "case_10" m104
set_directive_bind_op -op mul -impl fabric "case_10" m105
set_directive_bind_op -op mul -impl fabric "case_10" m106
set_directive_bind_op -op mul -impl fabric "case_10" m107
set_directive_bind_op -op mul -impl fabric "case_10" m108
set_directive_bind_op -op mul -impl fabric "case_10" m109
set_directive_bind_op -op mul -impl fabric "case_10" m110
set_directive_bind_op -op mul -impl fabric "case_10" m111
set_directive_bind_op -op mul -impl fabric "case_10" m112
set_directive_bind_op -op mul -impl fabric "case_10" m113
set_directive_bind_op -op mul -impl fabric "case_10" m114
set_directive_bind_op -op mul -impl fabric "case_10" m115
set_directive_bind_op -op mul -impl fabric "case_10" m116

