set_directive_bind_op -op mul -impl fabric "case_27" m31
set_directive_bind_op -op mul -impl fabric "case_27" m32
set_directive_bind_op -op mul -impl fabric "case_27" m33
set_directive_bind_op -op mul -impl fabric "case_27" m34
set_directive_bind_op -op mul -impl fabric "case_27" m35
set_directive_bind_op -op mul -impl fabric "case_27" m36
set_directive_bind_op -op mul -impl fabric "case_27" m37
set_directive_bind_op -op mul -impl fabric "case_27" m38
set_directive_bind_op -op mul -impl fabric "case_27" m39
set_directive_bind_op -op mul -impl fabric "case_27" m40
set_directive_bind_op -op mul -impl fabric "case_27" m41
set_directive_bind_op -op mul -impl fabric "case_27" m42
set_directive_bind_op -op mul -impl fabric "case_27" m43
set_directive_bind_op -op mul -impl fabric "case_27" m44
set_directive_bind_op -op mul -impl fabric "case_27" m45
set_directive_bind_op -op mul -impl fabric "case_27" m46
set_directive_bind_op -op mul -impl fabric "case_27" m47
set_directive_bind_op -op mul -impl fabric "case_27" m48
set_directive_bind_op -op mul -impl fabric "case_27" m49
set_directive_bind_op -op mul -impl fabric "case_27" m50
set_directive_bind_op -op mul -impl fabric "case_27" m51
set_directive_bind_op -op mul -impl fabric "case_27" m52
set_directive_bind_op -op mul -impl fabric "case_27" m53
set_directive_bind_op -op mul -impl fabric "case_27" m54
set_directive_bind_op -op mul -impl fabric "case_27" m55
set_directive_bind_op -op mul -impl fabric "case_27" m56
set_directive_bind_op -op mul -impl fabric "case_27" m57
set_directive_bind_op -op mul -impl fabric "case_27" m58
set_directive_bind_op -op mul -impl fabric "case_27" m59
set_directive_bind_op -op mul -impl fabric "case_27" m60
set_directive_bind_op -op mul -impl fabric "case_27" m61
set_directive_bind_op -op mul -impl fabric "case_27" m62
set_directive_bind_op -op mul -impl fabric "case_27" m63
set_directive_bind_op -op mul -impl fabric "case_27" m64
set_directive_bind_op -op mul -impl fabric "case_27" m65
set_directive_bind_op -op mul -impl fabric "case_27" m66
set_directive_bind_op -op mul -impl fabric "case_27" m67
set_directive_bind_op -op mul -impl fabric "case_27" m68
set_directive_bind_op -op mul -impl fabric "case_27" m69
set_directive_bind_op -op mul -impl fabric "case_27" m70
set_directive_bind_op -op mul -impl fabric "case_27" m71
set_directive_bind_op -op mul -impl fabric "case_27" m72
set_directive_bind_op -op mul -impl fabric "case_27" m73
set_directive_bind_op -op mul -impl fabric "case_27" m74
set_directive_bind_op -op mul -impl fabric "case_27" m75
set_directive_bind_op -op mul -impl fabric "case_27" m76
set_directive_bind_op -op mul -impl fabric "case_27" m77
set_directive_bind_op -op mul -impl fabric "case_27" m78
set_directive_bind_op -op mul -impl fabric "case_27" m79
set_directive_bind_op -op mul -impl fabric "case_27" m80
set_directive_bind_op -op mul -impl fabric "case_27" m81
set_directive_bind_op -op mul -impl fabric "case_27" m82
set_directive_bind_op -op mul -impl fabric "case_27" m83
set_directive_bind_op -op mul -impl fabric "case_27" m84
set_directive_bind_op -op mul -impl fabric "case_27" m85
set_directive_bind_op -op mul -impl fabric "case_27" m86
set_directive_bind_op -op mul -impl fabric "case_27" m87
set_directive_bind_op -op mul -impl fabric "case_27" m88
set_directive_bind_op -op mul -impl fabric "case_27" m89
set_directive_bind_op -op mul -impl fabric "case_27" m90
set_directive_bind_op -op mul -impl fabric "case_27" m91
set_directive_bind_op -op mul -impl fabric "case_27" m92
set_directive_bind_op -op mul -impl fabric "case_27" m93
set_directive_bind_op -op mul -impl fabric "case_27" m94
set_directive_bind_op -op mul -impl fabric "case_27" m95
set_directive_bind_op -op mul -impl fabric "case_27" m96
set_directive_bind_op -op mul -impl fabric "case_27" m97
set_directive_bind_op -op mul -impl fabric "case_27" m98
set_directive_bind_op -op mul -impl fabric "case_27" m99
set_directive_bind_op -op mul -impl fabric "case_27" m100
set_directive_bind_op -op mul -impl fabric "case_27" m101
set_directive_bind_op -op mul -impl fabric "case_27" m102
set_directive_bind_op -op mul -impl fabric "case_27" m103
set_directive_bind_op -op mul -impl fabric "case_27" m104
set_directive_bind_op -op mul -impl fabric "case_27" m105
set_directive_bind_op -op mul -impl fabric "case_27" m106
set_directive_bind_op -op mul -impl fabric "case_27" m107
set_directive_bind_op -op mul -impl fabric "case_27" m108
set_directive_bind_op -op mul -impl fabric "case_27" m109
set_directive_bind_op -op mul -impl fabric "case_27" m110
set_directive_bind_op -op mul -impl fabric "case_27" m111
set_directive_bind_op -op mul -impl fabric "case_27" m112
set_directive_bind_op -op mul -impl fabric "case_27" m113
set_directive_bind_op -op mul -impl fabric "case_27" m114
set_directive_bind_op -op mul -impl fabric "case_27" m115
set_directive_bind_op -op mul -impl fabric "case_27" m116
set_directive_bind_op -op mul -impl fabric "case_27" m117
set_directive_bind_op -op mul -impl fabric "case_27" m118
set_directive_bind_op -op mul -impl fabric "case_27" m119
set_directive_bind_op -op mul -impl fabric "case_27" m120
set_directive_bind_op -op mul -impl fabric "case_27" m121
set_directive_bind_op -op mul -impl fabric "case_27" m122
set_directive_bind_op -op mul -impl fabric "case_27" m123
set_directive_bind_op -op mul -impl fabric "case_27" m124
set_directive_bind_op -op mul -impl fabric "case_27" m125
set_directive_bind_op -op mul -impl fabric "case_27" m126
set_directive_bind_op -op mul -impl fabric "case_27" m127
set_directive_bind_op -op mul -impl fabric "case_27" m128
set_directive_bind_op -op mul -impl fabric "case_27" m129
set_directive_bind_op -op mul -impl fabric "case_27" m130
set_directive_bind_op -op mul -impl fabric "case_27" m131
set_directive_bind_op -op mul -impl fabric "case_27" m132
set_directive_bind_op -op mul -impl fabric "case_27" m133
set_directive_bind_op -op mul -impl fabric "case_27" m134
set_directive_bind_op -op mul -impl fabric "case_27" m135
set_directive_bind_op -op mul -impl fabric "case_27" m136
set_directive_bind_op -op mul -impl fabric "case_27" m137
set_directive_bind_op -op mul -impl fabric "case_27" m138
set_directive_bind_op -op mul -impl fabric "case_27" m139
set_directive_bind_op -op mul -impl fabric "case_27" m140
set_directive_bind_op -op mul -impl fabric "case_27" m141
set_directive_bind_op -op mul -impl fabric "case_27" m142
set_directive_bind_op -op mul -impl fabric "case_27" m143
set_directive_bind_op -op mul -impl fabric "case_27" m144
set_directive_bind_op -op mul -impl fabric "case_27" m145
set_directive_bind_op -op mul -impl fabric "case_27" m146
set_directive_bind_op -op mul -impl fabric "case_27" m147
set_directive_bind_op -op mul -impl fabric "case_27" m148
set_directive_bind_op -op mul -impl fabric "case_27" m149
set_directive_bind_op -op mul -impl fabric "case_27" m150
set_directive_bind_op -op mul -impl fabric "case_27" m151
set_directive_bind_op -op mul -impl fabric "case_27" m152
set_directive_bind_op -op mul -impl fabric "case_27" m153
set_directive_bind_op -op mul -impl fabric "case_27" m154
set_directive_bind_op -op mul -impl fabric "case_27" m155
set_directive_bind_op -op mul -impl fabric "case_27" m156
set_directive_bind_op -op mul -impl fabric "case_27" m157
set_directive_bind_op -op mul -impl fabric "case_27" m158
set_directive_bind_op -op mul -impl fabric "case_27" m159
set_directive_bind_op -op mul -impl fabric "case_27" m160
set_directive_bind_op -op mul -impl fabric "case_27" m161
set_directive_bind_op -op mul -impl fabric "case_27" m162
set_directive_bind_op -op mul -impl fabric "case_27" m163
set_directive_bind_op -op mul -impl fabric "case_27" m164
set_directive_bind_op -op mul -impl fabric "case_27" m165
set_directive_bind_op -op mul -impl fabric "case_27" m166
set_directive_bind_op -op mul -impl fabric "case_27" m167
set_directive_bind_op -op mul -impl fabric "case_27" m168
set_directive_bind_op -op mul -impl fabric "case_27" m169
set_directive_bind_op -op mul -impl fabric "case_27" m170
set_directive_bind_op -op mul -impl fabric "case_27" m171
set_directive_bind_op -op mul -impl fabric "case_27" m172
set_directive_bind_op -op mul -impl fabric "case_27" m173
set_directive_bind_op -op mul -impl fabric "case_27" m174
set_directive_bind_op -op mul -impl fabric "case_27" m175

