set_directive_bind_op -op mul -impl fabric "case_26" m11
set_directive_bind_op -op mul -impl fabric "case_26" m12
set_directive_bind_op -op mul -impl fabric "case_26" m13
set_directive_bind_op -op mul -impl fabric "case_26" m14
set_directive_bind_op -op mul -impl fabric "case_26" m15
set_directive_bind_op -op mul -impl fabric "case_26" m16
set_directive_bind_op -op mul -impl fabric "case_26" m17
set_directive_bind_op -op mul -impl fabric "case_26" m18
set_directive_bind_op -op mul -impl fabric "case_26" m19
set_directive_bind_op -op mul -impl fabric "case_26" m20
set_directive_bind_op -op mul -impl fabric "case_26" m21
set_directive_bind_op -op mul -impl fabric "case_26" m22
set_directive_bind_op -op mul -impl fabric "case_26" m23
set_directive_bind_op -op mul -impl fabric "case_26" m24
set_directive_bind_op -op mul -impl fabric "case_26" m25
set_directive_bind_op -op mul -impl fabric "case_26" m26
set_directive_bind_op -op mul -impl fabric "case_26" m27
set_directive_bind_op -op mul -impl fabric "case_26" m28
set_directive_bind_op -op mul -impl fabric "case_26" m29
set_directive_bind_op -op mul -impl fabric "case_26" m30
set_directive_bind_op -op mul -impl fabric "case_26" m31
set_directive_bind_op -op mul -impl fabric "case_26" m32
set_directive_bind_op -op mul -impl fabric "case_26" m33
set_directive_bind_op -op mul -impl fabric "case_26" m34
set_directive_bind_op -op mul -impl fabric "case_26" m35
set_directive_bind_op -op mul -impl fabric "case_26" m36
set_directive_bind_op -op mul -impl fabric "case_26" m37
set_directive_bind_op -op mul -impl fabric "case_26" m38
set_directive_bind_op -op mul -impl fabric "case_26" m39
set_directive_bind_op -op mul -impl fabric "case_26" m40
set_directive_bind_op -op mul -impl fabric "case_26" m41
set_directive_bind_op -op mul -impl fabric "case_26" m42
set_directive_bind_op -op mul -impl fabric "case_26" m43
set_directive_bind_op -op mul -impl fabric "case_26" m44
set_directive_bind_op -op mul -impl fabric "case_26" m45
set_directive_bind_op -op mul -impl fabric "case_26" m46
set_directive_bind_op -op mul -impl fabric "case_26" m47
set_directive_bind_op -op mul -impl fabric "case_26" m48
set_directive_bind_op -op mul -impl fabric "case_26" m49
set_directive_bind_op -op mul -impl fabric "case_26" m50
set_directive_bind_op -op mul -impl fabric "case_26" m51
set_directive_bind_op -op mul -impl fabric "case_26" m52
set_directive_bind_op -op mul -impl fabric "case_26" m53
set_directive_bind_op -op mul -impl fabric "case_26" m54
set_directive_bind_op -op mul -impl fabric "case_26" m55
set_directive_bind_op -op mul -impl fabric "case_26" m56
set_directive_bind_op -op mul -impl fabric "case_26" m57
set_directive_bind_op -op mul -impl fabric "case_26" m58
set_directive_bind_op -op mul -impl fabric "case_26" m59
set_directive_bind_op -op mul -impl fabric "case_26" m60
set_directive_bind_op -op mul -impl fabric "case_26" m61
set_directive_bind_op -op mul -impl fabric "case_26" m62
set_directive_bind_op -op mul -impl fabric "case_26" m63
set_directive_bind_op -op mul -impl fabric "case_26" m64
set_directive_bind_op -op mul -impl fabric "case_26" m65
set_directive_bind_op -op mul -impl fabric "case_26" m66
set_directive_bind_op -op mul -impl fabric "case_26" m67
set_directive_bind_op -op mul -impl fabric "case_26" m68
set_directive_bind_op -op mul -impl fabric "case_26" m69
set_directive_bind_op -op mul -impl fabric "case_26" m70
set_directive_bind_op -op mul -impl fabric "case_26" m71
set_directive_bind_op -op mul -impl fabric "case_26" m72
set_directive_bind_op -op mul -impl fabric "case_26" m73
set_directive_bind_op -op mul -impl fabric "case_26" m74
set_directive_bind_op -op mul -impl fabric "case_26" m75
set_directive_bind_op -op mul -impl fabric "case_26" m76
set_directive_bind_op -op mul -impl fabric "case_26" m77
set_directive_bind_op -op mul -impl fabric "case_26" m78
set_directive_bind_op -op mul -impl fabric "case_26" m79
set_directive_bind_op -op mul -impl fabric "case_26" m80
set_directive_bind_op -op mul -impl fabric "case_26" m81
set_directive_bind_op -op mul -impl fabric "case_26" m82
set_directive_bind_op -op mul -impl fabric "case_26" m83
set_directive_bind_op -op mul -impl fabric "case_26" m84
set_directive_bind_op -op mul -impl fabric "case_26" m85
set_directive_bind_op -op mul -impl fabric "case_26" m86
set_directive_bind_op -op mul -impl fabric "case_26" m87
set_directive_bind_op -op mul -impl fabric "case_26" m88
set_directive_bind_op -op mul -impl fabric "case_26" m89
set_directive_bind_op -op mul -impl fabric "case_26" m90
set_directive_bind_op -op mul -impl fabric "case_26" m91
set_directive_bind_op -op mul -impl fabric "case_26" m92
set_directive_bind_op -op mul -impl fabric "case_26" m93
set_directive_bind_op -op mul -impl fabric "case_26" m94
set_directive_bind_op -op mul -impl fabric "case_26" m95
set_directive_bind_op -op mul -impl fabric "case_26" m96
set_directive_bind_op -op mul -impl fabric "case_26" m97
set_directive_bind_op -op mul -impl fabric "case_26" m98
set_directive_bind_op -op mul -impl fabric "case_26" m99
set_directive_bind_op -op mul -impl fabric "case_26" m100
set_directive_bind_op -op mul -impl fabric "case_26" m101
set_directive_bind_op -op mul -impl fabric "case_26" m102
set_directive_bind_op -op mul -impl fabric "case_26" m103
set_directive_bind_op -op mul -impl fabric "case_26" m104
set_directive_bind_op -op mul -impl fabric "case_26" m105
set_directive_bind_op -op mul -impl fabric "case_26" m106
set_directive_bind_op -op mul -impl fabric "case_26" m107
set_directive_bind_op -op mul -impl fabric "case_26" m108
set_directive_bind_op -op mul -impl fabric "case_26" m109
set_directive_bind_op -op mul -impl fabric "case_26" m110
set_directive_bind_op -op mul -impl fabric "case_26" m111
set_directive_bind_op -op mul -impl fabric "case_26" m112
set_directive_bind_op -op mul -impl fabric "case_26" m113
set_directive_bind_op -op mul -impl fabric "case_26" m114
set_directive_bind_op -op mul -impl fabric "case_26" m115
set_directive_bind_op -op mul -impl fabric "case_26" m116
set_directive_bind_op -op mul -impl fabric "case_26" m117
set_directive_bind_op -op mul -impl fabric "case_26" m118
set_directive_bind_op -op mul -impl fabric "case_26" m119
set_directive_bind_op -op mul -impl fabric "case_26" m120
set_directive_bind_op -op mul -impl fabric "case_26" m121
set_directive_bind_op -op mul -impl fabric "case_26" m122
set_directive_bind_op -op mul -impl fabric "case_26" m123
set_directive_bind_op -op mul -impl fabric "case_26" m124
set_directive_bind_op -op mul -impl fabric "case_26" m125
set_directive_bind_op -op mul -impl fabric "case_26" m126
set_directive_bind_op -op mul -impl fabric "case_26" m127
set_directive_bind_op -op mul -impl fabric "case_26" m128
set_directive_bind_op -op mul -impl fabric "case_26" m129
set_directive_bind_op -op mul -impl fabric "case_26" m130
set_directive_bind_op -op mul -impl fabric "case_26" m131
set_directive_bind_op -op mul -impl fabric "case_26" m132
set_directive_bind_op -op mul -impl fabric "case_26" m133
set_directive_bind_op -op mul -impl fabric "case_26" m134
set_directive_bind_op -op mul -impl fabric "case_26" m135
set_directive_bind_op -op mul -impl fabric "case_26" m136
set_directive_bind_op -op mul -impl fabric "case_26" m137
set_directive_bind_op -op mul -impl fabric "case_26" m138
set_directive_bind_op -op mul -impl fabric "case_26" m139
set_directive_bind_op -op mul -impl fabric "case_26" m140
set_directive_bind_op -op mul -impl fabric "case_26" m141

