set_directive_bind_op -op mul -impl fabric "case_94" m23
set_directive_bind_op -op mul -impl fabric "case_94" m24
set_directive_bind_op -op mul -impl fabric "case_94" m25
set_directive_bind_op -op mul -impl fabric "case_94" m26
set_directive_bind_op -op mul -impl fabric "case_94" m27
set_directive_bind_op -op mul -impl fabric "case_94" m28
set_directive_bind_op -op mul -impl fabric "case_94" m29
set_directive_bind_op -op mul -impl fabric "case_94" m30
set_directive_bind_op -op mul -impl fabric "case_94" m31
set_directive_bind_op -op mul -impl fabric "case_94" m32
set_directive_bind_op -op mul -impl fabric "case_94" m33
set_directive_bind_op -op mul -impl fabric "case_94" m34
set_directive_bind_op -op mul -impl fabric "case_94" m35
set_directive_bind_op -op mul -impl fabric "case_94" m36
set_directive_bind_op -op mul -impl fabric "case_94" m37
set_directive_bind_op -op mul -impl fabric "case_94" m38
set_directive_bind_op -op mul -impl fabric "case_94" m39
set_directive_bind_op -op mul -impl fabric "case_94" m40
set_directive_bind_op -op mul -impl fabric "case_94" m41
set_directive_bind_op -op mul -impl fabric "case_94" m42
set_directive_bind_op -op mul -impl fabric "case_94" m43
set_directive_bind_op -op mul -impl fabric "case_94" m44
set_directive_bind_op -op mul -impl fabric "case_94" m45
set_directive_bind_op -op mul -impl fabric "case_94" m46
set_directive_bind_op -op mul -impl fabric "case_94" m47
set_directive_bind_op -op mul -impl fabric "case_94" m48
set_directive_bind_op -op mul -impl fabric "case_94" m49
set_directive_bind_op -op mul -impl fabric "case_94" m50
set_directive_bind_op -op mul -impl fabric "case_94" m51
set_directive_bind_op -op mul -impl fabric "case_94" m52
set_directive_bind_op -op mul -impl fabric "case_94" m53
set_directive_bind_op -op mul -impl fabric "case_94" m54
set_directive_bind_op -op mul -impl fabric "case_94" m55
set_directive_bind_op -op mul -impl fabric "case_94" m56
set_directive_bind_op -op mul -impl fabric "case_94" m57
set_directive_bind_op -op mul -impl fabric "case_94" m58
set_directive_bind_op -op mul -impl fabric "case_94" m59
set_directive_bind_op -op mul -impl fabric "case_94" m60
set_directive_bind_op -op mul -impl fabric "case_94" m61
set_directive_bind_op -op mul -impl fabric "case_94" m62
set_directive_bind_op -op mul -impl fabric "case_94" m63
set_directive_bind_op -op mul -impl fabric "case_94" m64
set_directive_bind_op -op mul -impl fabric "case_94" m65
set_directive_bind_op -op mul -impl fabric "case_94" m66
set_directive_bind_op -op mul -impl fabric "case_94" m67
set_directive_bind_op -op mul -impl fabric "case_94" m68
set_directive_bind_op -op mul -impl fabric "case_94" m69
set_directive_bind_op -op mul -impl fabric "case_94" m70
set_directive_bind_op -op mul -impl fabric "case_94" m71
set_directive_bind_op -op mul -impl fabric "case_94" m72
set_directive_bind_op -op mul -impl fabric "case_94" m73
set_directive_bind_op -op mul -impl fabric "case_94" m74
set_directive_bind_op -op mul -impl fabric "case_94" m75
set_directive_bind_op -op mul -impl fabric "case_94" m76
set_directive_bind_op -op mul -impl fabric "case_94" m77
set_directive_bind_op -op mul -impl fabric "case_94" m78
set_directive_bind_op -op mul -impl fabric "case_94" m79
set_directive_bind_op -op mul -impl fabric "case_94" m80
set_directive_bind_op -op mul -impl fabric "case_94" m81
set_directive_bind_op -op mul -impl fabric "case_94" m82
set_directive_bind_op -op mul -impl fabric "case_94" m83
set_directive_bind_op -op mul -impl fabric "case_94" m84
set_directive_bind_op -op mul -impl fabric "case_94" m85
set_directive_bind_op -op mul -impl fabric "case_94" m86
set_directive_bind_op -op mul -impl fabric "case_94" m87
set_directive_bind_op -op mul -impl fabric "case_94" m88
set_directive_bind_op -op mul -impl fabric "case_94" m89
set_directive_bind_op -op mul -impl fabric "case_94" m90
set_directive_bind_op -op mul -impl fabric "case_94" m91

