set_directive_bind_op -op mul -impl fabric "case_22" m23
set_directive_bind_op -op mul -impl fabric "case_22" m24
set_directive_bind_op -op mul -impl fabric "case_22" m25
set_directive_bind_op -op mul -impl fabric "case_22" m26
set_directive_bind_op -op mul -impl fabric "case_22" m27
set_directive_bind_op -op mul -impl fabric "case_22" m28
set_directive_bind_op -op mul -impl fabric "case_22" m29
set_directive_bind_op -op mul -impl fabric "case_22" m30
set_directive_bind_op -op mul -impl fabric "case_22" m31
set_directive_bind_op -op mul -impl fabric "case_22" m32
set_directive_bind_op -op mul -impl fabric "case_22" m33
set_directive_bind_op -op mul -impl fabric "case_22" m34
set_directive_bind_op -op mul -impl fabric "case_22" m35
set_directive_bind_op -op mul -impl fabric "case_22" m36
set_directive_bind_op -op mul -impl fabric "case_22" m37
set_directive_bind_op -op mul -impl fabric "case_22" m38
set_directive_bind_op -op mul -impl fabric "case_22" m39
set_directive_bind_op -op mul -impl fabric "case_22" m40
set_directive_bind_op -op mul -impl fabric "case_22" m41
set_directive_bind_op -op mul -impl fabric "case_22" m42
set_directive_bind_op -op mul -impl fabric "case_22" m43
set_directive_bind_op -op mul -impl fabric "case_22" m44
set_directive_bind_op -op mul -impl fabric "case_22" m45
set_directive_bind_op -op mul -impl fabric "case_22" m46
set_directive_bind_op -op mul -impl fabric "case_22" m47
set_directive_bind_op -op mul -impl fabric "case_22" m48
set_directive_bind_op -op mul -impl fabric "case_22" m49
set_directive_bind_op -op mul -impl fabric "case_22" m50
set_directive_bind_op -op mul -impl fabric "case_22" m51
set_directive_bind_op -op mul -impl fabric "case_22" m52
set_directive_bind_op -op mul -impl fabric "case_22" m53
set_directive_bind_op -op mul -impl fabric "case_22" m54
set_directive_bind_op -op mul -impl fabric "case_22" m55
set_directive_bind_op -op mul -impl fabric "case_22" m56
set_directive_bind_op -op mul -impl fabric "case_22" m57
set_directive_bind_op -op mul -impl fabric "case_22" m58
set_directive_bind_op -op mul -impl fabric "case_22" m59
set_directive_bind_op -op mul -impl fabric "case_22" m60
set_directive_bind_op -op mul -impl fabric "case_22" m61
set_directive_bind_op -op mul -impl fabric "case_22" m62
set_directive_bind_op -op mul -impl fabric "case_22" m63
set_directive_bind_op -op mul -impl fabric "case_22" m64
set_directive_bind_op -op mul -impl fabric "case_22" m65
set_directive_bind_op -op mul -impl fabric "case_22" m66
set_directive_bind_op -op mul -impl fabric "case_22" m67
set_directive_bind_op -op mul -impl fabric "case_22" m68
set_directive_bind_op -op mul -impl fabric "case_22" m69
set_directive_bind_op -op mul -impl fabric "case_22" m70
set_directive_bind_op -op mul -impl fabric "case_22" m71
set_directive_bind_op -op mul -impl fabric "case_22" m72
set_directive_bind_op -op mul -impl fabric "case_22" m73
set_directive_bind_op -op mul -impl fabric "case_22" m74
set_directive_bind_op -op mul -impl fabric "case_22" m75
set_directive_bind_op -op mul -impl fabric "case_22" m76
set_directive_bind_op -op mul -impl fabric "case_22" m77
set_directive_bind_op -op mul -impl fabric "case_22" m78
set_directive_bind_op -op mul -impl fabric "case_22" m79
set_directive_bind_op -op mul -impl fabric "case_22" m80
set_directive_bind_op -op mul -impl fabric "case_22" m81
set_directive_bind_op -op mul -impl fabric "case_22" m82
set_directive_bind_op -op mul -impl fabric "case_22" m83
set_directive_bind_op -op mul -impl fabric "case_22" m84
set_directive_bind_op -op mul -impl fabric "case_22" m85
set_directive_bind_op -op mul -impl fabric "case_22" m86
set_directive_bind_op -op mul -impl fabric "case_22" m87
set_directive_bind_op -op mul -impl fabric "case_22" m88
set_directive_bind_op -op mul -impl fabric "case_22" m89
set_directive_bind_op -op mul -impl fabric "case_22" m90
set_directive_bind_op -op mul -impl fabric "case_22" m91
set_directive_bind_op -op mul -impl fabric "case_22" m92
set_directive_bind_op -op mul -impl fabric "case_22" m93
set_directive_bind_op -op mul -impl fabric "case_22" m94
set_directive_bind_op -op mul -impl fabric "case_22" m95
set_directive_bind_op -op mul -impl fabric "case_22" m96
set_directive_bind_op -op mul -impl fabric "case_22" m97
set_directive_bind_op -op mul -impl fabric "case_22" m98
set_directive_bind_op -op mul -impl fabric "case_22" m99
set_directive_bind_op -op mul -impl fabric "case_22" m100
set_directive_bind_op -op mul -impl fabric "case_22" m101
set_directive_bind_op -op mul -impl fabric "case_22" m102
set_directive_bind_op -op mul -impl fabric "case_22" m103
set_directive_bind_op -op mul -impl fabric "case_22" m104
set_directive_bind_op -op mul -impl fabric "case_22" m105
set_directive_bind_op -op mul -impl fabric "case_22" m106
set_directive_bind_op -op mul -impl fabric "case_22" m107
set_directive_bind_op -op mul -impl fabric "case_22" m108
set_directive_bind_op -op mul -impl fabric "case_22" m109
set_directive_bind_op -op mul -impl fabric "case_22" m110
set_directive_bind_op -op mul -impl fabric "case_22" m111
set_directive_bind_op -op mul -impl fabric "case_22" m112
set_directive_bind_op -op mul -impl fabric "case_22" m113
set_directive_bind_op -op mul -impl fabric "case_22" m114
set_directive_bind_op -op mul -impl fabric "case_22" m115
set_directive_bind_op -op mul -impl fabric "case_22" m116
set_directive_bind_op -op mul -impl fabric "case_22" m117
set_directive_bind_op -op mul -impl fabric "case_22" m118
set_directive_bind_op -op mul -impl fabric "case_22" m119
set_directive_bind_op -op mul -impl fabric "case_22" m120
set_directive_bind_op -op mul -impl fabric "case_22" m121
set_directive_bind_op -op mul -impl fabric "case_22" m122
set_directive_bind_op -op mul -impl fabric "case_22" m123
set_directive_bind_op -op mul -impl fabric "case_22" m124
set_directive_bind_op -op mul -impl fabric "case_22" m125
set_directive_bind_op -op mul -impl fabric "case_22" m126
set_directive_bind_op -op mul -impl fabric "case_22" m127
set_directive_bind_op -op mul -impl fabric "case_22" m128
set_directive_bind_op -op mul -impl fabric "case_22" m129
set_directive_bind_op -op mul -impl fabric "case_22" m130
set_directive_bind_op -op mul -impl fabric "case_22" m131
set_directive_bind_op -op mul -impl fabric "case_22" m132
set_directive_bind_op -op mul -impl fabric "case_22" m133
set_directive_bind_op -op mul -impl fabric "case_22" m134
set_directive_bind_op -op mul -impl fabric "case_22" m135
set_directive_bind_op -op mul -impl fabric "case_22" m136
set_directive_bind_op -op mul -impl fabric "case_22" m137
set_directive_bind_op -op mul -impl fabric "case_22" m138
set_directive_bind_op -op mul -impl fabric "case_22" m139
set_directive_bind_op -op mul -impl fabric "case_22" m140
set_directive_bind_op -op mul -impl fabric "case_22" m141
set_directive_bind_op -op mul -impl fabric "case_22" m142
set_directive_bind_op -op mul -impl fabric "case_22" m143
set_directive_bind_op -op mul -impl fabric "case_22" m144
set_directive_bind_op -op mul -impl fabric "case_22" m145
set_directive_bind_op -op mul -impl fabric "case_22" m146
set_directive_bind_op -op mul -impl fabric "case_22" m147
set_directive_bind_op -op mul -impl fabric "case_22" m148
set_directive_bind_op -op mul -impl fabric "case_22" m149
set_directive_bind_op -op mul -impl fabric "case_22" m150
set_directive_bind_op -op mul -impl fabric "case_22" m151
set_directive_bind_op -op mul -impl fabric "case_22" m152
set_directive_bind_op -op mul -impl fabric "case_22" m153
set_directive_bind_op -op mul -impl fabric "case_22" m154
set_directive_bind_op -op mul -impl fabric "case_22" m155
set_directive_bind_op -op mul -impl fabric "case_22" m156
set_directive_bind_op -op mul -impl fabric "case_22" m157
set_directive_bind_op -op mul -impl fabric "case_22" m158
set_directive_bind_op -op mul -impl fabric "case_22" m159
set_directive_bind_op -op mul -impl fabric "case_22" m160
set_directive_bind_op -op mul -impl fabric "case_22" m161
set_directive_bind_op -op mul -impl fabric "case_22" m162
set_directive_bind_op -op mul -impl fabric "case_22" m163
set_directive_bind_op -op mul -impl fabric "case_22" m164
set_directive_bind_op -op mul -impl fabric "case_22" m165
set_directive_bind_op -op mul -impl fabric "case_22" m166
set_directive_bind_op -op mul -impl fabric "case_22" m167
set_directive_bind_op -op mul -impl fabric "case_22" m168
set_directive_bind_op -op mul -impl fabric "case_22" m169
set_directive_bind_op -op mul -impl fabric "case_22" m170
set_directive_bind_op -op mul -impl fabric "case_22" m171
set_directive_bind_op -op mul -impl fabric "case_22" m172
set_directive_bind_op -op mul -impl fabric "case_22" m173
set_directive_bind_op -op mul -impl fabric "case_22" m174
set_directive_bind_op -op mul -impl fabric "case_22" m175
set_directive_bind_op -op mul -impl fabric "case_22" m176
set_directive_bind_op -op mul -impl fabric "case_22" m177
set_directive_bind_op -op mul -impl fabric "case_22" m178
set_directive_bind_op -op mul -impl fabric "case_22" m179
set_directive_bind_op -op mul -impl fabric "case_22" m180
set_directive_bind_op -op mul -impl fabric "case_22" m181
set_directive_bind_op -op mul -impl fabric "case_22" m182
set_directive_bind_op -op mul -impl fabric "case_22" m183
set_directive_bind_op -op mul -impl fabric "case_22" m184
set_directive_bind_op -op mul -impl fabric "case_22" m185
set_directive_bind_op -op mul -impl fabric "case_22" m186
set_directive_bind_op -op mul -impl fabric "case_22" m187
set_directive_bind_op -op mul -impl fabric "case_22" m188
set_directive_bind_op -op mul -impl fabric "case_22" m189
set_directive_bind_op -op mul -impl fabric "case_22" m190
set_directive_bind_op -op mul -impl fabric "case_22" m191
set_directive_bind_op -op mul -impl fabric "case_22" m192
set_directive_bind_op -op mul -impl fabric "case_22" m193
set_directive_bind_op -op mul -impl fabric "case_22" m194
set_directive_bind_op -op mul -impl fabric "case_22" m195
set_directive_bind_op -op mul -impl fabric "case_22" m196

