set_directive_bind_op -op mul -impl fabric "case_9" m16
set_directive_bind_op -op mul -impl fabric "case_9" m17
set_directive_bind_op -op mul -impl fabric "case_9" m18
set_directive_bind_op -op mul -impl fabric "case_9" m19
set_directive_bind_op -op mul -impl fabric "case_9" m20
set_directive_bind_op -op mul -impl fabric "case_9" m21
set_directive_bind_op -op mul -impl fabric "case_9" m22
set_directive_bind_op -op mul -impl fabric "case_9" m23
set_directive_bind_op -op mul -impl fabric "case_9" m24
set_directive_bind_op -op mul -impl fabric "case_9" m25
set_directive_bind_op -op mul -impl fabric "case_9" m26
set_directive_bind_op -op mul -impl fabric "case_9" m27
set_directive_bind_op -op mul -impl fabric "case_9" m28
set_directive_bind_op -op mul -impl fabric "case_9" m29
set_directive_bind_op -op mul -impl fabric "case_9" m30
set_directive_bind_op -op mul -impl fabric "case_9" m31
set_directive_bind_op -op mul -impl fabric "case_9" m32
set_directive_bind_op -op mul -impl fabric "case_9" m33
set_directive_bind_op -op mul -impl fabric "case_9" m34
set_directive_bind_op -op mul -impl fabric "case_9" m35
set_directive_bind_op -op mul -impl fabric "case_9" m36
set_directive_bind_op -op mul -impl fabric "case_9" m37
set_directive_bind_op -op mul -impl fabric "case_9" m38
set_directive_bind_op -op mul -impl fabric "case_9" m39
set_directive_bind_op -op mul -impl fabric "case_9" m40
set_directive_bind_op -op mul -impl fabric "case_9" m41
set_directive_bind_op -op mul -impl fabric "case_9" m42
set_directive_bind_op -op mul -impl fabric "case_9" m43
set_directive_bind_op -op mul -impl fabric "case_9" m44
set_directive_bind_op -op mul -impl fabric "case_9" m45
set_directive_bind_op -op mul -impl fabric "case_9" m46
set_directive_bind_op -op mul -impl fabric "case_9" m47
set_directive_bind_op -op mul -impl fabric "case_9" m48
set_directive_bind_op -op mul -impl fabric "case_9" m49
set_directive_bind_op -op mul -impl fabric "case_9" m50
set_directive_bind_op -op mul -impl fabric "case_9" m51
set_directive_bind_op -op mul -impl fabric "case_9" m52
set_directive_bind_op -op mul -impl fabric "case_9" m53
set_directive_bind_op -op mul -impl fabric "case_9" m54
set_directive_bind_op -op mul -impl fabric "case_9" m55
set_directive_bind_op -op mul -impl fabric "case_9" m56
set_directive_bind_op -op mul -impl fabric "case_9" m57
set_directive_bind_op -op mul -impl fabric "case_9" m58
set_directive_bind_op -op mul -impl fabric "case_9" m59
set_directive_bind_op -op mul -impl fabric "case_9" m60
set_directive_bind_op -op mul -impl fabric "case_9" m61
set_directive_bind_op -op mul -impl fabric "case_9" m62
set_directive_bind_op -op mul -impl fabric "case_9" m63
set_directive_bind_op -op mul -impl fabric "case_9" m64
set_directive_bind_op -op mul -impl fabric "case_9" m65
set_directive_bind_op -op mul -impl fabric "case_9" m66
set_directive_bind_op -op mul -impl fabric "case_9" m67
set_directive_bind_op -op mul -impl fabric "case_9" m68
set_directive_bind_op -op mul -impl fabric "case_9" m69
set_directive_bind_op -op mul -impl fabric "case_9" m70
set_directive_bind_op -op mul -impl fabric "case_9" m71
set_directive_bind_op -op mul -impl fabric "case_9" m72
set_directive_bind_op -op mul -impl fabric "case_9" m73
set_directive_bind_op -op mul -impl fabric "case_9" m74
set_directive_bind_op -op mul -impl fabric "case_9" m75
set_directive_bind_op -op mul -impl fabric "case_9" m76
set_directive_bind_op -op mul -impl fabric "case_9" m77
set_directive_bind_op -op mul -impl fabric "case_9" m78
set_directive_bind_op -op mul -impl fabric "case_9" m79
set_directive_bind_op -op mul -impl fabric "case_9" m80
set_directive_bind_op -op mul -impl fabric "case_9" m81
set_directive_bind_op -op mul -impl fabric "case_9" m82

