set_directive_bind_op -op mul -impl fabric "case_96" m12
set_directive_bind_op -op mul -impl fabric "case_96" m13
set_directive_bind_op -op mul -impl fabric "case_96" m14
set_directive_bind_op -op mul -impl fabric "case_96" m15
set_directive_bind_op -op mul -impl fabric "case_96" m16
set_directive_bind_op -op mul -impl fabric "case_96" m17
set_directive_bind_op -op mul -impl fabric "case_96" m18
set_directive_bind_op -op mul -impl fabric "case_96" m19
set_directive_bind_op -op mul -impl fabric "case_96" m20
set_directive_bind_op -op mul -impl fabric "case_96" m21
set_directive_bind_op -op mul -impl fabric "case_96" m22
set_directive_bind_op -op mul -impl fabric "case_96" m23
set_directive_bind_op -op mul -impl fabric "case_96" m24
set_directive_bind_op -op mul -impl fabric "case_96" m25
set_directive_bind_op -op mul -impl fabric "case_96" m26
set_directive_bind_op -op mul -impl fabric "case_96" m27
set_directive_bind_op -op mul -impl fabric "case_96" m28
set_directive_bind_op -op mul -impl fabric "case_96" m29
set_directive_bind_op -op mul -impl fabric "case_96" m30
set_directive_bind_op -op mul -impl fabric "case_96" m31
set_directive_bind_op -op mul -impl fabric "case_96" m32
set_directive_bind_op -op mul -impl fabric "case_96" m33
set_directive_bind_op -op mul -impl fabric "case_96" m34
set_directive_bind_op -op mul -impl fabric "case_96" m35
set_directive_bind_op -op mul -impl fabric "case_96" m36
set_directive_bind_op -op mul -impl fabric "case_96" m37
set_directive_bind_op -op mul -impl fabric "case_96" m38
set_directive_bind_op -op mul -impl fabric "case_96" m39
set_directive_bind_op -op mul -impl fabric "case_96" m40
set_directive_bind_op -op mul -impl fabric "case_96" m41
set_directive_bind_op -op mul -impl fabric "case_96" m42
set_directive_bind_op -op mul -impl fabric "case_96" m43
set_directive_bind_op -op mul -impl fabric "case_96" m44
set_directive_bind_op -op mul -impl fabric "case_96" m45
set_directive_bind_op -op mul -impl fabric "case_96" m46
set_directive_bind_op -op mul -impl fabric "case_96" m47
set_directive_bind_op -op mul -impl fabric "case_96" m48
set_directive_bind_op -op mul -impl fabric "case_96" m49
set_directive_bind_op -op mul -impl fabric "case_96" m50
set_directive_bind_op -op mul -impl fabric "case_96" m51
set_directive_bind_op -op mul -impl fabric "case_96" m52
set_directive_bind_op -op mul -impl fabric "case_96" m53
set_directive_bind_op -op mul -impl fabric "case_96" m54
set_directive_bind_op -op mul -impl fabric "case_96" m55
set_directive_bind_op -op mul -impl fabric "case_96" m56
set_directive_bind_op -op mul -impl fabric "case_96" m57
set_directive_bind_op -op mul -impl fabric "case_96" m58
set_directive_bind_op -op mul -impl fabric "case_96" m59
set_directive_bind_op -op mul -impl fabric "case_96" m60
set_directive_bind_op -op mul -impl fabric "case_96" m61
set_directive_bind_op -op mul -impl fabric "case_96" m62
set_directive_bind_op -op mul -impl fabric "case_96" m63
set_directive_bind_op -op mul -impl fabric "case_96" m64
set_directive_bind_op -op mul -impl fabric "case_96" m65
set_directive_bind_op -op mul -impl fabric "case_96" m66
set_directive_bind_op -op mul -impl fabric "case_96" m67
set_directive_bind_op -op mul -impl fabric "case_96" m68
set_directive_bind_op -op mul -impl fabric "case_96" m69
set_directive_bind_op -op mul -impl fabric "case_96" m70
set_directive_bind_op -op mul -impl fabric "case_96" m71
set_directive_bind_op -op mul -impl fabric "case_96" m72
set_directive_bind_op -op mul -impl fabric "case_96" m73
set_directive_bind_op -op mul -impl fabric "case_96" m74
set_directive_bind_op -op mul -impl fabric "case_96" m75
set_directive_bind_op -op mul -impl fabric "case_96" m76
set_directive_bind_op -op mul -impl fabric "case_96" m77

