set_directive_bind_op -op mul -impl fabric "case_36" m18
set_directive_bind_op -op mul -impl fabric "case_36" m19
set_directive_bind_op -op mul -impl fabric "case_36" m20
set_directive_bind_op -op mul -impl fabric "case_36" m21
set_directive_bind_op -op mul -impl fabric "case_36" m22
set_directive_bind_op -op mul -impl fabric "case_36" m23
set_directive_bind_op -op mul -impl fabric "case_36" m24
set_directive_bind_op -op mul -impl fabric "case_36" m25
set_directive_bind_op -op mul -impl fabric "case_36" m26
set_directive_bind_op -op mul -impl fabric "case_36" m27
set_directive_bind_op -op mul -impl fabric "case_36" m28
set_directive_bind_op -op mul -impl fabric "case_36" m29
set_directive_bind_op -op mul -impl fabric "case_36" m30
set_directive_bind_op -op mul -impl fabric "case_36" m31
set_directive_bind_op -op mul -impl fabric "case_36" m32
set_directive_bind_op -op mul -impl fabric "case_36" m33
set_directive_bind_op -op mul -impl fabric "case_36" m34
set_directive_bind_op -op mul -impl fabric "case_36" m35
set_directive_bind_op -op mul -impl fabric "case_36" m36
set_directive_bind_op -op mul -impl fabric "case_36" m37
set_directive_bind_op -op mul -impl fabric "case_36" m38
set_directive_bind_op -op mul -impl fabric "case_36" m39
set_directive_bind_op -op mul -impl fabric "case_36" m40
set_directive_bind_op -op mul -impl fabric "case_36" m41
set_directive_bind_op -op mul -impl fabric "case_36" m42
set_directive_bind_op -op mul -impl fabric "case_36" m43
set_directive_bind_op -op mul -impl fabric "case_36" m44
set_directive_bind_op -op mul -impl fabric "case_36" m45
set_directive_bind_op -op mul -impl fabric "case_36" m46
set_directive_bind_op -op mul -impl fabric "case_36" m47
set_directive_bind_op -op mul -impl fabric "case_36" m48
set_directive_bind_op -op mul -impl fabric "case_36" m49
set_directive_bind_op -op mul -impl fabric "case_36" m50
set_directive_bind_op -op mul -impl fabric "case_36" m51
set_directive_bind_op -op mul -impl fabric "case_36" m52
set_directive_bind_op -op mul -impl fabric "case_36" m53
set_directive_bind_op -op mul -impl fabric "case_36" m54
set_directive_bind_op -op mul -impl fabric "case_36" m55
set_directive_bind_op -op mul -impl fabric "case_36" m56
set_directive_bind_op -op mul -impl fabric "case_36" m57
set_directive_bind_op -op mul -impl fabric "case_36" m58
set_directive_bind_op -op mul -impl fabric "case_36" m59
set_directive_bind_op -op mul -impl fabric "case_36" m60
set_directive_bind_op -op mul -impl fabric "case_36" m61
set_directive_bind_op -op mul -impl fabric "case_36" m62
set_directive_bind_op -op mul -impl fabric "case_36" m63
set_directive_bind_op -op mul -impl fabric "case_36" m64
set_directive_bind_op -op mul -impl fabric "case_36" m65
set_directive_bind_op -op mul -impl fabric "case_36" m66
set_directive_bind_op -op mul -impl fabric "case_36" m67
set_directive_bind_op -op mul -impl fabric "case_36" m68
set_directive_bind_op -op mul -impl fabric "case_36" m69
set_directive_bind_op -op mul -impl fabric "case_36" m70
set_directive_bind_op -op mul -impl fabric "case_36" m71
set_directive_bind_op -op mul -impl fabric "case_36" m72
set_directive_bind_op -op mul -impl fabric "case_36" m73
set_directive_bind_op -op mul -impl fabric "case_36" m74
set_directive_bind_op -op mul -impl fabric "case_36" m75
set_directive_bind_op -op mul -impl fabric "case_36" m76
set_directive_bind_op -op mul -impl fabric "case_36" m77
set_directive_bind_op -op mul -impl fabric "case_36" m78
set_directive_bind_op -op mul -impl fabric "case_36" m79
set_directive_bind_op -op mul -impl fabric "case_36" m80
set_directive_bind_op -op mul -impl fabric "case_36" m81
set_directive_bind_op -op mul -impl fabric "case_36" m82
set_directive_bind_op -op mul -impl fabric "case_36" m83
set_directive_bind_op -op mul -impl fabric "case_36" m84
set_directive_bind_op -op mul -impl fabric "case_36" m85
set_directive_bind_op -op mul -impl fabric "case_36" m86
set_directive_bind_op -op mul -impl fabric "case_36" m87
set_directive_bind_op -op mul -impl fabric "case_36" m88
set_directive_bind_op -op mul -impl fabric "case_36" m89
set_directive_bind_op -op mul -impl fabric "case_36" m90
set_directive_bind_op -op mul -impl fabric "case_36" m91
set_directive_bind_op -op mul -impl fabric "case_36" m92
set_directive_bind_op -op mul -impl fabric "case_36" m93
set_directive_bind_op -op mul -impl fabric "case_36" m94
set_directive_bind_op -op mul -impl fabric "case_36" m95
set_directive_bind_op -op mul -impl fabric "case_36" m96
set_directive_bind_op -op mul -impl fabric "case_36" m97
set_directive_bind_op -op mul -impl fabric "case_36" m98
set_directive_bind_op -op mul -impl fabric "case_36" m99
set_directive_bind_op -op mul -impl fabric "case_36" m100
set_directive_bind_op -op mul -impl fabric "case_36" m101
set_directive_bind_op -op mul -impl fabric "case_36" m102
set_directive_bind_op -op mul -impl fabric "case_36" m103
set_directive_bind_op -op mul -impl fabric "case_36" m104
set_directive_bind_op -op mul -impl fabric "case_36" m105
set_directive_bind_op -op mul -impl fabric "case_36" m106
set_directive_bind_op -op mul -impl fabric "case_36" m107
set_directive_bind_op -op mul -impl fabric "case_36" m108
set_directive_bind_op -op mul -impl fabric "case_36" m109
set_directive_bind_op -op mul -impl fabric "case_36" m110
set_directive_bind_op -op mul -impl fabric "case_36" m111
set_directive_bind_op -op mul -impl fabric "case_36" m112
set_directive_bind_op -op mul -impl fabric "case_36" m113
set_directive_bind_op -op mul -impl fabric "case_36" m114
set_directive_bind_op -op mul -impl fabric "case_36" m115
set_directive_bind_op -op mul -impl fabric "case_36" m116
set_directive_bind_op -op mul -impl fabric "case_36" m117
set_directive_bind_op -op mul -impl fabric "case_36" m118
set_directive_bind_op -op mul -impl fabric "case_36" m119
set_directive_bind_op -op mul -impl fabric "case_36" m120
set_directive_bind_op -op mul -impl fabric "case_36" m121
set_directive_bind_op -op mul -impl fabric "case_36" m122
set_directive_bind_op -op mul -impl fabric "case_36" m123
set_directive_bind_op -op mul -impl fabric "case_36" m124
set_directive_bind_op -op mul -impl fabric "case_36" m125
set_directive_bind_op -op mul -impl fabric "case_36" m126
set_directive_bind_op -op mul -impl fabric "case_36" m127
set_directive_bind_op -op mul -impl fabric "case_36" m128
set_directive_bind_op -op mul -impl fabric "case_36" m129
set_directive_bind_op -op mul -impl fabric "case_36" m130
set_directive_bind_op -op mul -impl fabric "case_36" m131
set_directive_bind_op -op mul -impl fabric "case_36" m132
set_directive_bind_op -op mul -impl fabric "case_36" m133
set_directive_bind_op -op mul -impl fabric "case_36" m134
set_directive_bind_op -op mul -impl fabric "case_36" m135
set_directive_bind_op -op mul -impl fabric "case_36" m136

