set_directive_bind_op -op mul -impl fabric "case_64" m21
set_directive_bind_op -op mul -impl fabric "case_64" m22
set_directive_bind_op -op mul -impl fabric "case_64" m23
set_directive_bind_op -op mul -impl fabric "case_64" m24
set_directive_bind_op -op mul -impl fabric "case_64" m25
set_directive_bind_op -op mul -impl fabric "case_64" m26
set_directive_bind_op -op mul -impl fabric "case_64" m27
set_directive_bind_op -op mul -impl fabric "case_64" m28
set_directive_bind_op -op mul -impl fabric "case_64" m29
set_directive_bind_op -op mul -impl fabric "case_64" m30
set_directive_bind_op -op mul -impl fabric "case_64" m31
set_directive_bind_op -op mul -impl fabric "case_64" m32
set_directive_bind_op -op mul -impl fabric "case_64" m33
set_directive_bind_op -op mul -impl fabric "case_64" m34
set_directive_bind_op -op mul -impl fabric "case_64" m35
set_directive_bind_op -op mul -impl fabric "case_64" m36
set_directive_bind_op -op mul -impl fabric "case_64" m37
set_directive_bind_op -op mul -impl fabric "case_64" m38
set_directive_bind_op -op mul -impl fabric "case_64" m39
set_directive_bind_op -op mul -impl fabric "case_64" m40
set_directive_bind_op -op mul -impl fabric "case_64" m41
set_directive_bind_op -op mul -impl fabric "case_64" m42
set_directive_bind_op -op mul -impl fabric "case_64" m43
set_directive_bind_op -op mul -impl fabric "case_64" m44
set_directive_bind_op -op mul -impl fabric "case_64" m45
set_directive_bind_op -op mul -impl fabric "case_64" m46
set_directive_bind_op -op mul -impl fabric "case_64" m47
set_directive_bind_op -op mul -impl fabric "case_64" m48
set_directive_bind_op -op mul -impl fabric "case_64" m49
set_directive_bind_op -op mul -impl fabric "case_64" m50
set_directive_bind_op -op mul -impl fabric "case_64" m51
set_directive_bind_op -op mul -impl fabric "case_64" m52
set_directive_bind_op -op mul -impl fabric "case_64" m53
set_directive_bind_op -op mul -impl fabric "case_64" m54
set_directive_bind_op -op mul -impl fabric "case_64" m55
set_directive_bind_op -op mul -impl fabric "case_64" m56
set_directive_bind_op -op mul -impl fabric "case_64" m57
set_directive_bind_op -op mul -impl fabric "case_64" m58
set_directive_bind_op -op mul -impl fabric "case_64" m59
set_directive_bind_op -op mul -impl fabric "case_64" m60
set_directive_bind_op -op mul -impl fabric "case_64" m61
set_directive_bind_op -op mul -impl fabric "case_64" m62
set_directive_bind_op -op mul -impl fabric "case_64" m63
set_directive_bind_op -op mul -impl fabric "case_64" m64
set_directive_bind_op -op mul -impl fabric "case_64" m65
set_directive_bind_op -op mul -impl fabric "case_64" m66

