set_directive_bind_op -op mul -impl fabric "case_30" m21
set_directive_bind_op -op mul -impl fabric "case_30" m22
set_directive_bind_op -op mul -impl fabric "case_30" m23
set_directive_bind_op -op mul -impl fabric "case_30" m24
set_directive_bind_op -op mul -impl fabric "case_30" m25
set_directive_bind_op -op mul -impl fabric "case_30" m26
set_directive_bind_op -op mul -impl fabric "case_30" m27
set_directive_bind_op -op mul -impl fabric "case_30" m28
set_directive_bind_op -op mul -impl fabric "case_30" m29
set_directive_bind_op -op mul -impl fabric "case_30" m30
set_directive_bind_op -op mul -impl fabric "case_30" m31
set_directive_bind_op -op mul -impl fabric "case_30" m32
set_directive_bind_op -op mul -impl fabric "case_30" m33
set_directive_bind_op -op mul -impl fabric "case_30" m34
set_directive_bind_op -op mul -impl fabric "case_30" m35
set_directive_bind_op -op mul -impl fabric "case_30" m36
set_directive_bind_op -op mul -impl fabric "case_30" m37
set_directive_bind_op -op mul -impl fabric "case_30" m38
set_directive_bind_op -op mul -impl fabric "case_30" m39
set_directive_bind_op -op mul -impl fabric "case_30" m40
set_directive_bind_op -op mul -impl fabric "case_30" m41
set_directive_bind_op -op mul -impl fabric "case_30" m42
set_directive_bind_op -op mul -impl fabric "case_30" m43
set_directive_bind_op -op mul -impl fabric "case_30" m44
set_directive_bind_op -op mul -impl fabric "case_30" m45
set_directive_bind_op -op mul -impl fabric "case_30" m46
set_directive_bind_op -op mul -impl fabric "case_30" m47
set_directive_bind_op -op mul -impl fabric "case_30" m48
set_directive_bind_op -op mul -impl fabric "case_30" m49
set_directive_bind_op -op mul -impl fabric "case_30" m50
set_directive_bind_op -op mul -impl fabric "case_30" m51
set_directive_bind_op -op mul -impl fabric "case_30" m52
set_directive_bind_op -op mul -impl fabric "case_30" m53
set_directive_bind_op -op mul -impl fabric "case_30" m54
set_directive_bind_op -op mul -impl fabric "case_30" m55
set_directive_bind_op -op mul -impl fabric "case_30" m56
set_directive_bind_op -op mul -impl fabric "case_30" m57
set_directive_bind_op -op mul -impl fabric "case_30" m58
set_directive_bind_op -op mul -impl fabric "case_30" m59
set_directive_bind_op -op mul -impl fabric "case_30" m60
set_directive_bind_op -op mul -impl fabric "case_30" m61
set_directive_bind_op -op mul -impl fabric "case_30" m62
set_directive_bind_op -op mul -impl fabric "case_30" m63
set_directive_bind_op -op mul -impl fabric "case_30" m64
set_directive_bind_op -op mul -impl fabric "case_30" m65
set_directive_bind_op -op mul -impl fabric "case_30" m66
set_directive_bind_op -op mul -impl fabric "case_30" m67
set_directive_bind_op -op mul -impl fabric "case_30" m68
set_directive_bind_op -op mul -impl fabric "case_30" m69
set_directive_bind_op -op mul -impl fabric "case_30" m70
set_directive_bind_op -op mul -impl fabric "case_30" m71
set_directive_bind_op -op mul -impl fabric "case_30" m72
set_directive_bind_op -op mul -impl fabric "case_30" m73
set_directive_bind_op -op mul -impl fabric "case_30" m74
set_directive_bind_op -op mul -impl fabric "case_30" m75
set_directive_bind_op -op mul -impl fabric "case_30" m76
set_directive_bind_op -op mul -impl fabric "case_30" m77
set_directive_bind_op -op mul -impl fabric "case_30" m78
set_directive_bind_op -op mul -impl fabric "case_30" m79
set_directive_bind_op -op mul -impl fabric "case_30" m80
set_directive_bind_op -op mul -impl fabric "case_30" m81
set_directive_bind_op -op mul -impl fabric "case_30" m82
set_directive_bind_op -op mul -impl fabric "case_30" m83
set_directive_bind_op -op mul -impl fabric "case_30" m84
set_directive_bind_op -op mul -impl fabric "case_30" m85
set_directive_bind_op -op mul -impl fabric "case_30" m86
set_directive_bind_op -op mul -impl fabric "case_30" m87
set_directive_bind_op -op mul -impl fabric "case_30" m88
set_directive_bind_op -op mul -impl fabric "case_30" m89
set_directive_bind_op -op mul -impl fabric "case_30" m90
set_directive_bind_op -op mul -impl fabric "case_30" m91
set_directive_bind_op -op mul -impl fabric "case_30" m92
set_directive_bind_op -op mul -impl fabric "case_30" m93
set_directive_bind_op -op mul -impl fabric "case_30" m94
set_directive_bind_op -op mul -impl fabric "case_30" m95
set_directive_bind_op -op mul -impl fabric "case_30" m96
set_directive_bind_op -op mul -impl fabric "case_30" m97
set_directive_bind_op -op mul -impl fabric "case_30" m98
set_directive_bind_op -op mul -impl fabric "case_30" m99
set_directive_bind_op -op mul -impl fabric "case_30" m100

