set_directive_bind_op -op mul -impl fabric "case_40" m31
set_directive_bind_op -op mul -impl fabric "case_40" m32
set_directive_bind_op -op mul -impl fabric "case_40" m33
set_directive_bind_op -op mul -impl fabric "case_40" m34
set_directive_bind_op -op mul -impl fabric "case_40" m35
set_directive_bind_op -op mul -impl fabric "case_40" m36
set_directive_bind_op -op mul -impl fabric "case_40" m37
set_directive_bind_op -op mul -impl fabric "case_40" m38
set_directive_bind_op -op mul -impl fabric "case_40" m39
set_directive_bind_op -op mul -impl fabric "case_40" m40
set_directive_bind_op -op mul -impl fabric "case_40" m41
set_directive_bind_op -op mul -impl fabric "case_40" m42
set_directive_bind_op -op mul -impl fabric "case_40" m43
set_directive_bind_op -op mul -impl fabric "case_40" m44
set_directive_bind_op -op mul -impl fabric "case_40" m45
set_directive_bind_op -op mul -impl fabric "case_40" m46
set_directive_bind_op -op mul -impl fabric "case_40" m47
set_directive_bind_op -op mul -impl fabric "case_40" m48
set_directive_bind_op -op mul -impl fabric "case_40" m49
set_directive_bind_op -op mul -impl fabric "case_40" m50
set_directive_bind_op -op mul -impl fabric "case_40" m51
set_directive_bind_op -op mul -impl fabric "case_40" m52
set_directive_bind_op -op mul -impl fabric "case_40" m53
set_directive_bind_op -op mul -impl fabric "case_40" m54
set_directive_bind_op -op mul -impl fabric "case_40" m55
set_directive_bind_op -op mul -impl fabric "case_40" m56
set_directive_bind_op -op mul -impl fabric "case_40" m57
set_directive_bind_op -op mul -impl fabric "case_40" m58
set_directive_bind_op -op mul -impl fabric "case_40" m59
set_directive_bind_op -op mul -impl fabric "case_40" m60
set_directive_bind_op -op mul -impl fabric "case_40" m61
set_directive_bind_op -op mul -impl fabric "case_40" m62
set_directive_bind_op -op mul -impl fabric "case_40" m63
set_directive_bind_op -op mul -impl fabric "case_40" m64
set_directive_bind_op -op mul -impl fabric "case_40" m65
set_directive_bind_op -op mul -impl fabric "case_40" m66
set_directive_bind_op -op mul -impl fabric "case_40" m67
set_directive_bind_op -op mul -impl fabric "case_40" m68
set_directive_bind_op -op mul -impl fabric "case_40" m69
set_directive_bind_op -op mul -impl fabric "case_40" m70
set_directive_bind_op -op mul -impl fabric "case_40" m71
set_directive_bind_op -op mul -impl fabric "case_40" m72
set_directive_bind_op -op mul -impl fabric "case_40" m73
set_directive_bind_op -op mul -impl fabric "case_40" m74
set_directive_bind_op -op mul -impl fabric "case_40" m75
set_directive_bind_op -op mul -impl fabric "case_40" m76
set_directive_bind_op -op mul -impl fabric "case_40" m77
set_directive_bind_op -op mul -impl fabric "case_40" m78
set_directive_bind_op -op mul -impl fabric "case_40" m79
set_directive_bind_op -op mul -impl fabric "case_40" m80
set_directive_bind_op -op mul -impl fabric "case_40" m81
set_directive_bind_op -op mul -impl fabric "case_40" m82
set_directive_bind_op -op mul -impl fabric "case_40" m83
set_directive_bind_op -op mul -impl fabric "case_40" m84
set_directive_bind_op -op mul -impl fabric "case_40" m85
set_directive_bind_op -op mul -impl fabric "case_40" m86
set_directive_bind_op -op mul -impl fabric "case_40" m87
set_directive_bind_op -op mul -impl fabric "case_40" m88
set_directive_bind_op -op mul -impl fabric "case_40" m89
set_directive_bind_op -op mul -impl fabric "case_40" m90
set_directive_bind_op -op mul -impl fabric "case_40" m91
set_directive_bind_op -op mul -impl fabric "case_40" m92
set_directive_bind_op -op mul -impl fabric "case_40" m93
set_directive_bind_op -op mul -impl fabric "case_40" m94
set_directive_bind_op -op mul -impl fabric "case_40" m95
set_directive_bind_op -op mul -impl fabric "case_40" m96
set_directive_bind_op -op mul -impl fabric "case_40" m97
set_directive_bind_op -op mul -impl fabric "case_40" m98
set_directive_bind_op -op mul -impl fabric "case_40" m99
set_directive_bind_op -op mul -impl fabric "case_40" m100
set_directive_bind_op -op mul -impl fabric "case_40" m101
set_directive_bind_op -op mul -impl fabric "case_40" m102
set_directive_bind_op -op mul -impl fabric "case_40" m103
set_directive_bind_op -op mul -impl fabric "case_40" m104
set_directive_bind_op -op mul -impl fabric "case_40" m105
set_directive_bind_op -op mul -impl fabric "case_40" m106
set_directive_bind_op -op mul -impl fabric "case_40" m107
set_directive_bind_op -op mul -impl fabric "case_40" m108
set_directive_bind_op -op mul -impl fabric "case_40" m109
set_directive_bind_op -op mul -impl fabric "case_40" m110
set_directive_bind_op -op mul -impl fabric "case_40" m111
set_directive_bind_op -op mul -impl fabric "case_40" m112
set_directive_bind_op -op mul -impl fabric "case_40" m113
set_directive_bind_op -op mul -impl fabric "case_40" m114
set_directive_bind_op -op mul -impl fabric "case_40" m115
set_directive_bind_op -op mul -impl fabric "case_40" m116
set_directive_bind_op -op mul -impl fabric "case_40" m117
set_directive_bind_op -op mul -impl fabric "case_40" m118
set_directive_bind_op -op mul -impl fabric "case_40" m119
set_directive_bind_op -op mul -impl fabric "case_40" m120
set_directive_bind_op -op mul -impl fabric "case_40" m121
set_directive_bind_op -op mul -impl fabric "case_40" m122
set_directive_bind_op -op mul -impl fabric "case_40" m123
set_directive_bind_op -op mul -impl fabric "case_40" m124
set_directive_bind_op -op mul -impl fabric "case_40" m125
set_directive_bind_op -op mul -impl fabric "case_40" m126
set_directive_bind_op -op mul -impl fabric "case_40" m127
set_directive_bind_op -op mul -impl fabric "case_40" m128
set_directive_bind_op -op mul -impl fabric "case_40" m129
set_directive_bind_op -op mul -impl fabric "case_40" m130
set_directive_bind_op -op mul -impl fabric "case_40" m131
set_directive_bind_op -op mul -impl fabric "case_40" m132
set_directive_bind_op -op mul -impl fabric "case_40" m133
set_directive_bind_op -op mul -impl fabric "case_40" m134
set_directive_bind_op -op mul -impl fabric "case_40" m135
set_directive_bind_op -op mul -impl fabric "case_40" m136
set_directive_bind_op -op mul -impl fabric "case_40" m137

