set_directive_bind_op -op mul -impl fabric "case_82" m10
set_directive_bind_op -op mul -impl fabric "case_82" m11
set_directive_bind_op -op mul -impl fabric "case_82" m12
set_directive_bind_op -op mul -impl fabric "case_82" m13
set_directive_bind_op -op mul -impl fabric "case_82" m14
set_directive_bind_op -op mul -impl fabric "case_82" m15
set_directive_bind_op -op mul -impl fabric "case_82" m16
set_directive_bind_op -op mul -impl fabric "case_82" m17
set_directive_bind_op -op mul -impl fabric "case_82" m18
set_directive_bind_op -op mul -impl fabric "case_82" m19
set_directive_bind_op -op mul -impl fabric "case_82" m20
set_directive_bind_op -op mul -impl fabric "case_82" m21
set_directive_bind_op -op mul -impl fabric "case_82" m22
set_directive_bind_op -op mul -impl fabric "case_82" m23
set_directive_bind_op -op mul -impl fabric "case_82" m24
set_directive_bind_op -op mul -impl fabric "case_82" m25
set_directive_bind_op -op mul -impl fabric "case_82" m26
set_directive_bind_op -op mul -impl fabric "case_82" m27
set_directive_bind_op -op mul -impl fabric "case_82" m28
set_directive_bind_op -op mul -impl fabric "case_82" m29
set_directive_bind_op -op mul -impl fabric "case_82" m30
set_directive_bind_op -op mul -impl fabric "case_82" m31
set_directive_bind_op -op mul -impl fabric "case_82" m32
set_directive_bind_op -op mul -impl fabric "case_82" m33
set_directive_bind_op -op mul -impl fabric "case_82" m34
set_directive_bind_op -op mul -impl fabric "case_82" m35
set_directive_bind_op -op mul -impl fabric "case_82" m36
set_directive_bind_op -op mul -impl fabric "case_82" m37
set_directive_bind_op -op mul -impl fabric "case_82" m38
set_directive_bind_op -op mul -impl fabric "case_82" m39
set_directive_bind_op -op mul -impl fabric "case_82" m40
set_directive_bind_op -op mul -impl fabric "case_82" m41
set_directive_bind_op -op mul -impl fabric "case_82" m42
set_directive_bind_op -op mul -impl fabric "case_82" m43
set_directive_bind_op -op mul -impl fabric "case_82" m44
set_directive_bind_op -op mul -impl fabric "case_82" m45
set_directive_bind_op -op mul -impl fabric "case_82" m46
set_directive_bind_op -op mul -impl fabric "case_82" m47
set_directive_bind_op -op mul -impl fabric "case_82" m48
set_directive_bind_op -op mul -impl fabric "case_82" m49
set_directive_bind_op -op mul -impl fabric "case_82" m50
set_directive_bind_op -op mul -impl fabric "case_82" m51
set_directive_bind_op -op mul -impl fabric "case_82" m52
set_directive_bind_op -op mul -impl fabric "case_82" m53
set_directive_bind_op -op mul -impl fabric "case_82" m54
set_directive_bind_op -op mul -impl fabric "case_82" m55
set_directive_bind_op -op mul -impl fabric "case_82" m56
set_directive_bind_op -op mul -impl fabric "case_82" m57
set_directive_bind_op -op mul -impl fabric "case_82" m58
set_directive_bind_op -op mul -impl fabric "case_82" m59
set_directive_bind_op -op mul -impl fabric "case_82" m60
set_directive_bind_op -op mul -impl fabric "case_82" m61
set_directive_bind_op -op mul -impl fabric "case_82" m62
set_directive_bind_op -op mul -impl fabric "case_82" m63
set_directive_bind_op -op mul -impl fabric "case_82" m64
set_directive_bind_op -op mul -impl fabric "case_82" m65
set_directive_bind_op -op mul -impl fabric "case_82" m66
set_directive_bind_op -op mul -impl fabric "case_82" m67
set_directive_bind_op -op mul -impl fabric "case_82" m68
set_directive_bind_op -op mul -impl fabric "case_82" m69
set_directive_bind_op -op mul -impl fabric "case_82" m70
set_directive_bind_op -op mul -impl fabric "case_82" m71

