set_directive_bind_op -op mul -impl fabric "case_32" m9
set_directive_bind_op -op mul -impl fabric "case_32" m10
set_directive_bind_op -op mul -impl fabric "case_32" m11
set_directive_bind_op -op mul -impl fabric "case_32" m12
set_directive_bind_op -op mul -impl fabric "case_32" m13
set_directive_bind_op -op mul -impl fabric "case_32" m14
set_directive_bind_op -op mul -impl fabric "case_32" m15
set_directive_bind_op -op mul -impl fabric "case_32" m16
set_directive_bind_op -op mul -impl fabric "case_32" m17
set_directive_bind_op -op mul -impl fabric "case_32" m18
set_directive_bind_op -op mul -impl fabric "case_32" m19
set_directive_bind_op -op mul -impl fabric "case_32" m20
set_directive_bind_op -op mul -impl fabric "case_32" m21
set_directive_bind_op -op mul -impl fabric "case_32" m22
set_directive_bind_op -op mul -impl fabric "case_32" m23
set_directive_bind_op -op mul -impl fabric "case_32" m24
set_directive_bind_op -op mul -impl fabric "case_32" m25
set_directive_bind_op -op mul -impl fabric "case_32" m26
set_directive_bind_op -op mul -impl fabric "case_32" m27
set_directive_bind_op -op mul -impl fabric "case_32" m28
set_directive_bind_op -op mul -impl fabric "case_32" m29
set_directive_bind_op -op mul -impl fabric "case_32" m30
set_directive_bind_op -op mul -impl fabric "case_32" m31
set_directive_bind_op -op mul -impl fabric "case_32" m32
set_directive_bind_op -op mul -impl fabric "case_32" m33
set_directive_bind_op -op mul -impl fabric "case_32" m34
set_directive_bind_op -op mul -impl fabric "case_32" m35
set_directive_bind_op -op mul -impl fabric "case_32" m36
set_directive_bind_op -op mul -impl fabric "case_32" m37
set_directive_bind_op -op mul -impl fabric "case_32" m38
set_directive_bind_op -op mul -impl fabric "case_32" m39
set_directive_bind_op -op mul -impl fabric "case_32" m40
set_directive_bind_op -op mul -impl fabric "case_32" m41
set_directive_bind_op -op mul -impl fabric "case_32" m42
set_directive_bind_op -op mul -impl fabric "case_32" m43
set_directive_bind_op -op mul -impl fabric "case_32" m44
set_directive_bind_op -op mul -impl fabric "case_32" m45
set_directive_bind_op -op mul -impl fabric "case_32" m46
set_directive_bind_op -op mul -impl fabric "case_32" m47
set_directive_bind_op -op mul -impl fabric "case_32" m48
set_directive_bind_op -op mul -impl fabric "case_32" m49
set_directive_bind_op -op mul -impl fabric "case_32" m50
set_directive_bind_op -op mul -impl fabric "case_32" m51
set_directive_bind_op -op mul -impl fabric "case_32" m52
set_directive_bind_op -op mul -impl fabric "case_32" m53
set_directive_bind_op -op mul -impl fabric "case_32" m54
set_directive_bind_op -op mul -impl fabric "case_32" m55
set_directive_bind_op -op mul -impl fabric "case_32" m56
set_directive_bind_op -op mul -impl fabric "case_32" m57
set_directive_bind_op -op mul -impl fabric "case_32" m58
set_directive_bind_op -op mul -impl fabric "case_32" m59
set_directive_bind_op -op mul -impl fabric "case_32" m60
set_directive_bind_op -op mul -impl fabric "case_32" m61
set_directive_bind_op -op mul -impl fabric "case_32" m62
set_directive_bind_op -op mul -impl fabric "case_32" m63
set_directive_bind_op -op mul -impl fabric "case_32" m64
set_directive_bind_op -op mul -impl fabric "case_32" m65
set_directive_bind_op -op mul -impl fabric "case_32" m66
set_directive_bind_op -op mul -impl fabric "case_32" m67
set_directive_bind_op -op mul -impl fabric "case_32" m68
set_directive_bind_op -op mul -impl fabric "case_32" m69
set_directive_bind_op -op mul -impl fabric "case_32" m70
set_directive_bind_op -op mul -impl fabric "case_32" m71
set_directive_bind_op -op mul -impl fabric "case_32" m72
set_directive_bind_op -op mul -impl fabric "case_32" m73
set_directive_bind_op -op mul -impl fabric "case_32" m74
set_directive_bind_op -op mul -impl fabric "case_32" m75
set_directive_bind_op -op mul -impl fabric "case_32" m76
set_directive_bind_op -op mul -impl fabric "case_32" m77
set_directive_bind_op -op mul -impl fabric "case_32" m78
set_directive_bind_op -op mul -impl fabric "case_32" m79
set_directive_bind_op -op mul -impl fabric "case_32" m80
set_directive_bind_op -op mul -impl fabric "case_32" m81
set_directive_bind_op -op mul -impl fabric "case_32" m82
set_directive_bind_op -op mul -impl fabric "case_32" m83
set_directive_bind_op -op mul -impl fabric "case_32" m84
set_directive_bind_op -op mul -impl fabric "case_32" m85
set_directive_bind_op -op mul -impl fabric "case_32" m86
set_directive_bind_op -op mul -impl fabric "case_32" m87
set_directive_bind_op -op mul -impl fabric "case_32" m88
set_directive_bind_op -op mul -impl fabric "case_32" m89
set_directive_bind_op -op mul -impl fabric "case_32" m90
set_directive_bind_op -op mul -impl fabric "case_32" m91
set_directive_bind_op -op mul -impl fabric "case_32" m92
set_directive_bind_op -op mul -impl fabric "case_32" m93
set_directive_bind_op -op mul -impl fabric "case_32" m94
set_directive_bind_op -op mul -impl fabric "case_32" m95
set_directive_bind_op -op mul -impl fabric "case_32" m96
set_directive_bind_op -op mul -impl fabric "case_32" m97
set_directive_bind_op -op mul -impl fabric "case_32" m98
set_directive_bind_op -op mul -impl fabric "case_32" m99
set_directive_bind_op -op mul -impl fabric "case_32" m100
set_directive_bind_op -op mul -impl fabric "case_32" m101
set_directive_bind_op -op mul -impl fabric "case_32" m102
set_directive_bind_op -op mul -impl fabric "case_32" m103
set_directive_bind_op -op mul -impl fabric "case_32" m104
set_directive_bind_op -op mul -impl fabric "case_32" m105
set_directive_bind_op -op mul -impl fabric "case_32" m106
set_directive_bind_op -op mul -impl fabric "case_32" m107
set_directive_bind_op -op mul -impl fabric "case_32" m108
set_directive_bind_op -op mul -impl fabric "case_32" m109
set_directive_bind_op -op mul -impl fabric "case_32" m110
set_directive_bind_op -op mul -impl fabric "case_32" m111
set_directive_bind_op -op mul -impl fabric "case_32" m112
set_directive_bind_op -op mul -impl fabric "case_32" m113
set_directive_bind_op -op mul -impl fabric "case_32" m114
set_directive_bind_op -op mul -impl fabric "case_32" m115
set_directive_bind_op -op mul -impl fabric "case_32" m116
set_directive_bind_op -op mul -impl fabric "case_32" m117
set_directive_bind_op -op mul -impl fabric "case_32" m118
set_directive_bind_op -op mul -impl fabric "case_32" m119
set_directive_bind_op -op mul -impl fabric "case_32" m120
set_directive_bind_op -op mul -impl fabric "case_32" m121
set_directive_bind_op -op mul -impl fabric "case_32" m122
set_directive_bind_op -op mul -impl fabric "case_32" m123
set_directive_bind_op -op mul -impl fabric "case_32" m124
set_directive_bind_op -op mul -impl fabric "case_32" m125
set_directive_bind_op -op mul -impl fabric "case_32" m126
set_directive_bind_op -op mul -impl fabric "case_32" m127
set_directive_bind_op -op mul -impl fabric "case_32" m128
set_directive_bind_op -op mul -impl fabric "case_32" m129
set_directive_bind_op -op mul -impl fabric "case_32" m130
set_directive_bind_op -op mul -impl fabric "case_32" m131
set_directive_bind_op -op mul -impl fabric "case_32" m132
set_directive_bind_op -op mul -impl fabric "case_32" m133
set_directive_bind_op -op mul -impl fabric "case_32" m134
set_directive_bind_op -op mul -impl fabric "case_32" m135
set_directive_bind_op -op mul -impl fabric "case_32" m136
set_directive_bind_op -op mul -impl fabric "case_32" m137
set_directive_bind_op -op mul -impl fabric "case_32" m138
set_directive_bind_op -op mul -impl fabric "case_32" m139
set_directive_bind_op -op mul -impl fabric "case_32" m140
set_directive_bind_op -op mul -impl fabric "case_32" m141
set_directive_bind_op -op mul -impl fabric "case_32" m142
set_directive_bind_op -op mul -impl fabric "case_32" m143
set_directive_bind_op -op mul -impl fabric "case_32" m144
set_directive_bind_op -op mul -impl fabric "case_32" m145
set_directive_bind_op -op mul -impl fabric "case_32" m146
set_directive_bind_op -op mul -impl fabric "case_32" m147
set_directive_bind_op -op mul -impl fabric "case_32" m148
set_directive_bind_op -op mul -impl fabric "case_32" m149
set_directive_bind_op -op mul -impl fabric "case_32" m150
set_directive_bind_op -op mul -impl fabric "case_32" m151
set_directive_bind_op -op mul -impl fabric "case_32" m152
set_directive_bind_op -op mul -impl fabric "case_32" m153
set_directive_bind_op -op mul -impl fabric "case_32" m154
set_directive_bind_op -op mul -impl fabric "case_32" m155
set_directive_bind_op -op mul -impl fabric "case_32" m156
set_directive_bind_op -op mul -impl fabric "case_32" m157
set_directive_bind_op -op mul -impl fabric "case_32" m158
set_directive_bind_op -op mul -impl fabric "case_32" m159
set_directive_bind_op -op mul -impl fabric "case_32" m160
set_directive_bind_op -op mul -impl fabric "case_32" m161
set_directive_bind_op -op mul -impl fabric "case_32" m162
set_directive_bind_op -op mul -impl fabric "case_32" m163
set_directive_bind_op -op mul -impl fabric "case_32" m164
set_directive_bind_op -op mul -impl fabric "case_32" m165
set_directive_bind_op -op mul -impl fabric "case_32" m166
set_directive_bind_op -op mul -impl fabric "case_32" m167
set_directive_bind_op -op mul -impl fabric "case_32" m168
set_directive_bind_op -op mul -impl fabric "case_32" m169
set_directive_bind_op -op mul -impl fabric "case_32" m170
set_directive_bind_op -op mul -impl fabric "case_32" m171
set_directive_bind_op -op mul -impl fabric "case_32" m172
set_directive_bind_op -op mul -impl fabric "case_32" m173
set_directive_bind_op -op mul -impl fabric "case_32" m174
set_directive_bind_op -op mul -impl fabric "case_32" m175
set_directive_bind_op -op mul -impl fabric "case_32" m176
set_directive_bind_op -op mul -impl fabric "case_32" m177
set_directive_bind_op -op mul -impl fabric "case_32" m178
set_directive_bind_op -op mul -impl fabric "case_32" m179
set_directive_bind_op -op mul -impl fabric "case_32" m180
set_directive_bind_op -op mul -impl fabric "case_32" m181
set_directive_bind_op -op mul -impl fabric "case_32" m182
set_directive_bind_op -op mul -impl fabric "case_32" m183
set_directive_bind_op -op mul -impl fabric "case_32" m184
set_directive_bind_op -op mul -impl fabric "case_32" m185
set_directive_bind_op -op mul -impl fabric "case_32" m186
set_directive_bind_op -op mul -impl fabric "case_32" m187
set_directive_bind_op -op mul -impl fabric "case_32" m188
set_directive_bind_op -op mul -impl fabric "case_32" m189
set_directive_bind_op -op mul -impl fabric "case_32" m190
set_directive_bind_op -op mul -impl fabric "case_32" m191
set_directive_bind_op -op mul -impl fabric "case_32" m192

