set_directive_bind_op -op mul -impl fabric "case_29" m8
set_directive_bind_op -op mul -impl fabric "case_29" m9
set_directive_bind_op -op mul -impl fabric "case_29" m10
set_directive_bind_op -op mul -impl fabric "case_29" m11
set_directive_bind_op -op mul -impl fabric "case_29" m12
set_directive_bind_op -op mul -impl fabric "case_29" m13
set_directive_bind_op -op mul -impl fabric "case_29" m14
set_directive_bind_op -op mul -impl fabric "case_29" m15
set_directive_bind_op -op mul -impl fabric "case_29" m16
set_directive_bind_op -op mul -impl fabric "case_29" m17
set_directive_bind_op -op mul -impl fabric "case_29" m18
set_directive_bind_op -op mul -impl fabric "case_29" m19
set_directive_bind_op -op mul -impl fabric "case_29" m20
set_directive_bind_op -op mul -impl fabric "case_29" m21
set_directive_bind_op -op mul -impl fabric "case_29" m22
set_directive_bind_op -op mul -impl fabric "case_29" m23
set_directive_bind_op -op mul -impl fabric "case_29" m24
set_directive_bind_op -op mul -impl fabric "case_29" m25
set_directive_bind_op -op mul -impl fabric "case_29" m26
set_directive_bind_op -op mul -impl fabric "case_29" m27
set_directive_bind_op -op mul -impl fabric "case_29" m28
set_directive_bind_op -op mul -impl fabric "case_29" m29
set_directive_bind_op -op mul -impl fabric "case_29" m30
set_directive_bind_op -op mul -impl fabric "case_29" m31
set_directive_bind_op -op mul -impl fabric "case_29" m32
set_directive_bind_op -op mul -impl fabric "case_29" m33
set_directive_bind_op -op mul -impl fabric "case_29" m34
set_directive_bind_op -op mul -impl fabric "case_29" m35
set_directive_bind_op -op mul -impl fabric "case_29" m36
set_directive_bind_op -op mul -impl fabric "case_29" m37
set_directive_bind_op -op mul -impl fabric "case_29" m38
set_directive_bind_op -op mul -impl fabric "case_29" m39
set_directive_bind_op -op mul -impl fabric "case_29" m40
set_directive_bind_op -op mul -impl fabric "case_29" m41
set_directive_bind_op -op mul -impl fabric "case_29" m42
set_directive_bind_op -op mul -impl fabric "case_29" m43
set_directive_bind_op -op mul -impl fabric "case_29" m44
set_directive_bind_op -op mul -impl fabric "case_29" m45
set_directive_bind_op -op mul -impl fabric "case_29" m46
set_directive_bind_op -op mul -impl fabric "case_29" m47
set_directive_bind_op -op mul -impl fabric "case_29" m48
set_directive_bind_op -op mul -impl fabric "case_29" m49
set_directive_bind_op -op mul -impl fabric "case_29" m50
set_directive_bind_op -op mul -impl fabric "case_29" m51
set_directive_bind_op -op mul -impl fabric "case_29" m52
set_directive_bind_op -op mul -impl fabric "case_29" m53
set_directive_bind_op -op mul -impl fabric "case_29" m54
set_directive_bind_op -op mul -impl fabric "case_29" m55
set_directive_bind_op -op mul -impl fabric "case_29" m56
set_directive_bind_op -op mul -impl fabric "case_29" m57
set_directive_bind_op -op mul -impl fabric "case_29" m58
set_directive_bind_op -op mul -impl fabric "case_29" m59
set_directive_bind_op -op mul -impl fabric "case_29" m60
set_directive_bind_op -op mul -impl fabric "case_29" m61
set_directive_bind_op -op mul -impl fabric "case_29" m62
set_directive_bind_op -op mul -impl fabric "case_29" m63

