set_directive_bind_op -op mul -impl fabric "case_56" m14
set_directive_bind_op -op mul -impl fabric "case_56" m15
set_directive_bind_op -op mul -impl fabric "case_56" m16
set_directive_bind_op -op mul -impl fabric "case_56" m17
set_directive_bind_op -op mul -impl fabric "case_56" m18
set_directive_bind_op -op mul -impl fabric "case_56" m19
set_directive_bind_op -op mul -impl fabric "case_56" m20
set_directive_bind_op -op mul -impl fabric "case_56" m21
set_directive_bind_op -op mul -impl fabric "case_56" m22
set_directive_bind_op -op mul -impl fabric "case_56" m23
set_directive_bind_op -op mul -impl fabric "case_56" m24
set_directive_bind_op -op mul -impl fabric "case_56" m25
set_directive_bind_op -op mul -impl fabric "case_56" m26
set_directive_bind_op -op mul -impl fabric "case_56" m27
set_directive_bind_op -op mul -impl fabric "case_56" m28
set_directive_bind_op -op mul -impl fabric "case_56" m29
set_directive_bind_op -op mul -impl fabric "case_56" m30
set_directive_bind_op -op mul -impl fabric "case_56" m31
set_directive_bind_op -op mul -impl fabric "case_56" m32
set_directive_bind_op -op mul -impl fabric "case_56" m33
set_directive_bind_op -op mul -impl fabric "case_56" m34
set_directive_bind_op -op mul -impl fabric "case_56" m35
set_directive_bind_op -op mul -impl fabric "case_56" m36
set_directive_bind_op -op mul -impl fabric "case_56" m37
set_directive_bind_op -op mul -impl fabric "case_56" m38
set_directive_bind_op -op mul -impl fabric "case_56" m39
set_directive_bind_op -op mul -impl fabric "case_56" m40
set_directive_bind_op -op mul -impl fabric "case_56" m41
set_directive_bind_op -op mul -impl fabric "case_56" m42
set_directive_bind_op -op mul -impl fabric "case_56" m43
set_directive_bind_op -op mul -impl fabric "case_56" m44
set_directive_bind_op -op mul -impl fabric "case_56" m45
set_directive_bind_op -op mul -impl fabric "case_56" m46
set_directive_bind_op -op mul -impl fabric "case_56" m47
set_directive_bind_op -op mul -impl fabric "case_56" m48
set_directive_bind_op -op mul -impl fabric "case_56" m49
set_directive_bind_op -op mul -impl fabric "case_56" m50
set_directive_bind_op -op mul -impl fabric "case_56" m51
set_directive_bind_op -op mul -impl fabric "case_56" m52
set_directive_bind_op -op mul -impl fabric "case_56" m53
set_directive_bind_op -op mul -impl fabric "case_56" m54
set_directive_bind_op -op mul -impl fabric "case_56" m55
set_directive_bind_op -op mul -impl fabric "case_56" m56
set_directive_bind_op -op mul -impl fabric "case_56" m57
set_directive_bind_op -op mul -impl fabric "case_56" m58
set_directive_bind_op -op mul -impl fabric "case_56" m59
set_directive_bind_op -op mul -impl fabric "case_56" m60
set_directive_bind_op -op mul -impl fabric "case_56" m61
set_directive_bind_op -op mul -impl fabric "case_56" m62
set_directive_bind_op -op mul -impl fabric "case_56" m63
set_directive_bind_op -op mul -impl fabric "case_56" m64
set_directive_bind_op -op mul -impl fabric "case_56" m65
set_directive_bind_op -op mul -impl fabric "case_56" m66
set_directive_bind_op -op mul -impl fabric "case_56" m67
set_directive_bind_op -op mul -impl fabric "case_56" m68
set_directive_bind_op -op mul -impl fabric "case_56" m69
set_directive_bind_op -op mul -impl fabric "case_56" m70
set_directive_bind_op -op mul -impl fabric "case_56" m71
set_directive_bind_op -op mul -impl fabric "case_56" m72
set_directive_bind_op -op mul -impl fabric "case_56" m73
set_directive_bind_op -op mul -impl fabric "case_56" m74
set_directive_bind_op -op mul -impl fabric "case_56" m75
set_directive_bind_op -op mul -impl fabric "case_56" m76
set_directive_bind_op -op mul -impl fabric "case_56" m77
set_directive_bind_op -op mul -impl fabric "case_56" m78
set_directive_bind_op -op mul -impl fabric "case_56" m79
set_directive_bind_op -op mul -impl fabric "case_56" m80
set_directive_bind_op -op mul -impl fabric "case_56" m81
set_directive_bind_op -op mul -impl fabric "case_56" m82
set_directive_bind_op -op mul -impl fabric "case_56" m83
set_directive_bind_op -op mul -impl fabric "case_56" m84
set_directive_bind_op -op mul -impl fabric "case_56" m85
set_directive_bind_op -op mul -impl fabric "case_56" m86
set_directive_bind_op -op mul -impl fabric "case_56" m87
set_directive_bind_op -op mul -impl fabric "case_56" m88
set_directive_bind_op -op mul -impl fabric "case_56" m89
set_directive_bind_op -op mul -impl fabric "case_56" m90
set_directive_bind_op -op mul -impl fabric "case_56" m91
set_directive_bind_op -op mul -impl fabric "case_56" m92
set_directive_bind_op -op mul -impl fabric "case_56" m93
set_directive_bind_op -op mul -impl fabric "case_56" m94
set_directive_bind_op -op mul -impl fabric "case_56" m95
set_directive_bind_op -op mul -impl fabric "case_56" m96
set_directive_bind_op -op mul -impl fabric "case_56" m97
set_directive_bind_op -op mul -impl fabric "case_56" m98
set_directive_bind_op -op mul -impl fabric "case_56" m99
set_directive_bind_op -op mul -impl fabric "case_56" m100
set_directive_bind_op -op mul -impl fabric "case_56" m101
set_directive_bind_op -op mul -impl fabric "case_56" m102
set_directive_bind_op -op mul -impl fabric "case_56" m103
set_directive_bind_op -op mul -impl fabric "case_56" m104
set_directive_bind_op -op mul -impl fabric "case_56" m105
set_directive_bind_op -op mul -impl fabric "case_56" m106
set_directive_bind_op -op mul -impl fabric "case_56" m107
set_directive_bind_op -op mul -impl fabric "case_56" m108
set_directive_bind_op -op mul -impl fabric "case_56" m109
set_directive_bind_op -op mul -impl fabric "case_56" m110
set_directive_bind_op -op mul -impl fabric "case_56" m111
set_directive_bind_op -op mul -impl fabric "case_56" m112
set_directive_bind_op -op mul -impl fabric "case_56" m113
set_directive_bind_op -op mul -impl fabric "case_56" m114
set_directive_bind_op -op mul -impl fabric "case_56" m115
set_directive_bind_op -op mul -impl fabric "case_56" m116
set_directive_bind_op -op mul -impl fabric "case_56" m117
set_directive_bind_op -op mul -impl fabric "case_56" m118
set_directive_bind_op -op mul -impl fabric "case_56" m119
set_directive_bind_op -op mul -impl fabric "case_56" m120
set_directive_bind_op -op mul -impl fabric "case_56" m121
set_directive_bind_op -op mul -impl fabric "case_56" m122
set_directive_bind_op -op mul -impl fabric "case_56" m123
set_directive_bind_op -op mul -impl fabric "case_56" m124
set_directive_bind_op -op mul -impl fabric "case_56" m125
set_directive_bind_op -op mul -impl fabric "case_56" m126
set_directive_bind_op -op mul -impl fabric "case_56" m127
set_directive_bind_op -op mul -impl fabric "case_56" m128
set_directive_bind_op -op mul -impl fabric "case_56" m129
set_directive_bind_op -op mul -impl fabric "case_56" m130
set_directive_bind_op -op mul -impl fabric "case_56" m131
set_directive_bind_op -op mul -impl fabric "case_56" m132
set_directive_bind_op -op mul -impl fabric "case_56" m133
set_directive_bind_op -op mul -impl fabric "case_56" m134
set_directive_bind_op -op mul -impl fabric "case_56" m135
set_directive_bind_op -op mul -impl fabric "case_56" m136
set_directive_bind_op -op mul -impl fabric "case_56" m137
set_directive_bind_op -op mul -impl fabric "case_56" m138
set_directive_bind_op -op mul -impl fabric "case_56" m139
set_directive_bind_op -op mul -impl fabric "case_56" m140
set_directive_bind_op -op mul -impl fabric "case_56" m141
set_directive_bind_op -op mul -impl fabric "case_56" m142
set_directive_bind_op -op mul -impl fabric "case_56" m143
set_directive_bind_op -op mul -impl fabric "case_56" m144
set_directive_bind_op -op mul -impl fabric "case_56" m145
set_directive_bind_op -op mul -impl fabric "case_56" m146
set_directive_bind_op -op mul -impl fabric "case_56" m147
set_directive_bind_op -op mul -impl fabric "case_56" m148
set_directive_bind_op -op mul -impl fabric "case_56" m149
set_directive_bind_op -op mul -impl fabric "case_56" m150
set_directive_bind_op -op mul -impl fabric "case_56" m151
set_directive_bind_op -op mul -impl fabric "case_56" m152
set_directive_bind_op -op mul -impl fabric "case_56" m153
set_directive_bind_op -op mul -impl fabric "case_56" m154
set_directive_bind_op -op mul -impl fabric "case_56" m155
set_directive_bind_op -op mul -impl fabric "case_56" m156
set_directive_bind_op -op mul -impl fabric "case_56" m157
set_directive_bind_op -op mul -impl fabric "case_56" m158
set_directive_bind_op -op mul -impl fabric "case_56" m159
set_directive_bind_op -op mul -impl fabric "case_56" m160
set_directive_bind_op -op mul -impl fabric "case_56" m161
set_directive_bind_op -op mul -impl fabric "case_56" m162
set_directive_bind_op -op mul -impl fabric "case_56" m163

