set_directive_bind_op -op mul -impl fabric "case_28" m9
set_directive_bind_op -op mul -impl fabric "case_28" m10
set_directive_bind_op -op mul -impl fabric "case_28" m11
set_directive_bind_op -op mul -impl fabric "case_28" m12
set_directive_bind_op -op mul -impl fabric "case_28" m13
set_directive_bind_op -op mul -impl fabric "case_28" m14
set_directive_bind_op -op mul -impl fabric "case_28" m15
set_directive_bind_op -op mul -impl fabric "case_28" m16
set_directive_bind_op -op mul -impl fabric "case_28" m17
set_directive_bind_op -op mul -impl fabric "case_28" m18
set_directive_bind_op -op mul -impl fabric "case_28" m19
set_directive_bind_op -op mul -impl fabric "case_28" m20
set_directive_bind_op -op mul -impl fabric "case_28" m21
set_directive_bind_op -op mul -impl fabric "case_28" m22
set_directive_bind_op -op mul -impl fabric "case_28" m23
set_directive_bind_op -op mul -impl fabric "case_28" m24
set_directive_bind_op -op mul -impl fabric "case_28" m25
set_directive_bind_op -op mul -impl fabric "case_28" m26
set_directive_bind_op -op mul -impl fabric "case_28" m27
set_directive_bind_op -op mul -impl fabric "case_28" m28
set_directive_bind_op -op mul -impl fabric "case_28" m29
set_directive_bind_op -op mul -impl fabric "case_28" m30
set_directive_bind_op -op mul -impl fabric "case_28" m31
set_directive_bind_op -op mul -impl fabric "case_28" m32
set_directive_bind_op -op mul -impl fabric "case_28" m33
set_directive_bind_op -op mul -impl fabric "case_28" m34
set_directive_bind_op -op mul -impl fabric "case_28" m35
set_directive_bind_op -op mul -impl fabric "case_28" m36
set_directive_bind_op -op mul -impl fabric "case_28" m37
set_directive_bind_op -op mul -impl fabric "case_28" m38
set_directive_bind_op -op mul -impl fabric "case_28" m39
set_directive_bind_op -op mul -impl fabric "case_28" m40
set_directive_bind_op -op mul -impl fabric "case_28" m41
set_directive_bind_op -op mul -impl fabric "case_28" m42
set_directive_bind_op -op mul -impl fabric "case_28" m43
set_directive_bind_op -op mul -impl fabric "case_28" m44
set_directive_bind_op -op mul -impl fabric "case_28" m45
set_directive_bind_op -op mul -impl fabric "case_28" m46
set_directive_bind_op -op mul -impl fabric "case_28" m47
set_directive_bind_op -op mul -impl fabric "case_28" m48
set_directive_bind_op -op mul -impl fabric "case_28" m49
set_directive_bind_op -op mul -impl fabric "case_28" m50
set_directive_bind_op -op mul -impl fabric "case_28" m51
set_directive_bind_op -op mul -impl fabric "case_28" m52
set_directive_bind_op -op mul -impl fabric "case_28" m53
set_directive_bind_op -op mul -impl fabric "case_28" m54
set_directive_bind_op -op mul -impl fabric "case_28" m55
set_directive_bind_op -op mul -impl fabric "case_28" m56
set_directive_bind_op -op mul -impl fabric "case_28" m57
set_directive_bind_op -op mul -impl fabric "case_28" m58
set_directive_bind_op -op mul -impl fabric "case_28" m59
set_directive_bind_op -op mul -impl fabric "case_28" m60
set_directive_bind_op -op mul -impl fabric "case_28" m61
set_directive_bind_op -op mul -impl fabric "case_28" m62
set_directive_bind_op -op mul -impl fabric "case_28" m63
set_directive_bind_op -op mul -impl fabric "case_28" m64
set_directive_bind_op -op mul -impl fabric "case_28" m65
set_directive_bind_op -op mul -impl fabric "case_28" m66
set_directive_bind_op -op mul -impl fabric "case_28" m67
set_directive_bind_op -op mul -impl fabric "case_28" m68
set_directive_bind_op -op mul -impl fabric "case_28" m69
set_directive_bind_op -op mul -impl fabric "case_28" m70
set_directive_bind_op -op mul -impl fabric "case_28" m71
set_directive_bind_op -op mul -impl fabric "case_28" m72
set_directive_bind_op -op mul -impl fabric "case_28" m73
set_directive_bind_op -op mul -impl fabric "case_28" m74
set_directive_bind_op -op mul -impl fabric "case_28" m75
set_directive_bind_op -op mul -impl fabric "case_28" m76
set_directive_bind_op -op mul -impl fabric "case_28" m77
set_directive_bind_op -op mul -impl fabric "case_28" m78
set_directive_bind_op -op mul -impl fabric "case_28" m79
set_directive_bind_op -op mul -impl fabric "case_28" m80
set_directive_bind_op -op mul -impl fabric "case_28" m81
set_directive_bind_op -op mul -impl fabric "case_28" m82
set_directive_bind_op -op mul -impl fabric "case_28" m83
set_directive_bind_op -op mul -impl fabric "case_28" m84
set_directive_bind_op -op mul -impl fabric "case_28" m85
set_directive_bind_op -op mul -impl fabric "case_28" m86
set_directive_bind_op -op mul -impl fabric "case_28" m87
set_directive_bind_op -op mul -impl fabric "case_28" m88
set_directive_bind_op -op mul -impl fabric "case_28" m89
set_directive_bind_op -op mul -impl fabric "case_28" m90
set_directive_bind_op -op mul -impl fabric "case_28" m91
set_directive_bind_op -op mul -impl fabric "case_28" m92
set_directive_bind_op -op mul -impl fabric "case_28" m93
set_directive_bind_op -op mul -impl fabric "case_28" m94
set_directive_bind_op -op mul -impl fabric "case_28" m95
set_directive_bind_op -op mul -impl fabric "case_28" m96
set_directive_bind_op -op mul -impl fabric "case_28" m97
set_directive_bind_op -op mul -impl fabric "case_28" m98
set_directive_bind_op -op mul -impl fabric "case_28" m99
set_directive_bind_op -op mul -impl fabric "case_28" m100
set_directive_bind_op -op mul -impl fabric "case_28" m101
set_directive_bind_op -op mul -impl fabric "case_28" m102
set_directive_bind_op -op mul -impl fabric "case_28" m103
set_directive_bind_op -op mul -impl fabric "case_28" m104
set_directive_bind_op -op mul -impl fabric "case_28" m105
set_directive_bind_op -op mul -impl fabric "case_28" m106
set_directive_bind_op -op mul -impl fabric "case_28" m107
set_directive_bind_op -op mul -impl fabric "case_28" m108
set_directive_bind_op -op mul -impl fabric "case_28" m109
set_directive_bind_op -op mul -impl fabric "case_28" m110
set_directive_bind_op -op mul -impl fabric "case_28" m111
set_directive_bind_op -op mul -impl fabric "case_28" m112
set_directive_bind_op -op mul -impl fabric "case_28" m113
set_directive_bind_op -op mul -impl fabric "case_28" m114
set_directive_bind_op -op mul -impl fabric "case_28" m115
set_directive_bind_op -op mul -impl fabric "case_28" m116
set_directive_bind_op -op mul -impl fabric "case_28" m117

