set_directive_bind_op -op mul -impl fabric "case_34" m6
set_directive_bind_op -op mul -impl fabric "case_34" m7
set_directive_bind_op -op mul -impl fabric "case_34" m8
set_directive_bind_op -op mul -impl fabric "case_34" m9
set_directive_bind_op -op mul -impl fabric "case_34" m10
set_directive_bind_op -op mul -impl fabric "case_34" m11
set_directive_bind_op -op mul -impl fabric "case_34" m12
set_directive_bind_op -op mul -impl fabric "case_34" m13
set_directive_bind_op -op mul -impl fabric "case_34" m14
set_directive_bind_op -op mul -impl fabric "case_34" m15
set_directive_bind_op -op mul -impl fabric "case_34" m16
set_directive_bind_op -op mul -impl fabric "case_34" m17
set_directive_bind_op -op mul -impl fabric "case_34" m18
set_directive_bind_op -op mul -impl fabric "case_34" m19
set_directive_bind_op -op mul -impl fabric "case_34" m20
set_directive_bind_op -op mul -impl fabric "case_34" m21
set_directive_bind_op -op mul -impl fabric "case_34" m22
set_directive_bind_op -op mul -impl fabric "case_34" m23
set_directive_bind_op -op mul -impl fabric "case_34" m24
set_directive_bind_op -op mul -impl fabric "case_34" m25
set_directive_bind_op -op mul -impl fabric "case_34" m26
set_directive_bind_op -op mul -impl fabric "case_34" m27
set_directive_bind_op -op mul -impl fabric "case_34" m28
set_directive_bind_op -op mul -impl fabric "case_34" m29
set_directive_bind_op -op mul -impl fabric "case_34" m30
set_directive_bind_op -op mul -impl fabric "case_34" m31
set_directive_bind_op -op mul -impl fabric "case_34" m32
set_directive_bind_op -op mul -impl fabric "case_34" m33
set_directive_bind_op -op mul -impl fabric "case_34" m34
set_directive_bind_op -op mul -impl fabric "case_34" m35
set_directive_bind_op -op mul -impl fabric "case_34" m36
set_directive_bind_op -op mul -impl fabric "case_34" m37
set_directive_bind_op -op mul -impl fabric "case_34" m38
set_directive_bind_op -op mul -impl fabric "case_34" m39
set_directive_bind_op -op mul -impl fabric "case_34" m40
set_directive_bind_op -op mul -impl fabric "case_34" m41
set_directive_bind_op -op mul -impl fabric "case_34" m42
set_directive_bind_op -op mul -impl fabric "case_34" m43
set_directive_bind_op -op mul -impl fabric "case_34" m44
set_directive_bind_op -op mul -impl fabric "case_34" m45
set_directive_bind_op -op mul -impl fabric "case_34" m46
set_directive_bind_op -op mul -impl fabric "case_34" m47
set_directive_bind_op -op mul -impl fabric "case_34" m48
set_directive_bind_op -op mul -impl fabric "case_34" m49
set_directive_bind_op -op mul -impl fabric "case_34" m50
set_directive_bind_op -op mul -impl fabric "case_34" m51
set_directive_bind_op -op mul -impl fabric "case_34" m52
set_directive_bind_op -op mul -impl fabric "case_34" m53
set_directive_bind_op -op mul -impl fabric "case_34" m54
set_directive_bind_op -op mul -impl fabric "case_34" m55

