set_directive_bind_op -op mul -impl fabric "case_99" m22
set_directive_bind_op -op mul -impl fabric "case_99" m23
set_directive_bind_op -op mul -impl fabric "case_99" m24
set_directive_bind_op -op mul -impl fabric "case_99" m25
set_directive_bind_op -op mul -impl fabric "case_99" m26
set_directive_bind_op -op mul -impl fabric "case_99" m27
set_directive_bind_op -op mul -impl fabric "case_99" m28
set_directive_bind_op -op mul -impl fabric "case_99" m29
set_directive_bind_op -op mul -impl fabric "case_99" m30
set_directive_bind_op -op mul -impl fabric "case_99" m31
set_directive_bind_op -op mul -impl fabric "case_99" m32
set_directive_bind_op -op mul -impl fabric "case_99" m33
set_directive_bind_op -op mul -impl fabric "case_99" m34
set_directive_bind_op -op mul -impl fabric "case_99" m35
set_directive_bind_op -op mul -impl fabric "case_99" m36
set_directive_bind_op -op mul -impl fabric "case_99" m37
set_directive_bind_op -op mul -impl fabric "case_99" m38
set_directive_bind_op -op mul -impl fabric "case_99" m39
set_directive_bind_op -op mul -impl fabric "case_99" m40
set_directive_bind_op -op mul -impl fabric "case_99" m41
set_directive_bind_op -op mul -impl fabric "case_99" m42
set_directive_bind_op -op mul -impl fabric "case_99" m43
set_directive_bind_op -op mul -impl fabric "case_99" m44
set_directive_bind_op -op mul -impl fabric "case_99" m45
set_directive_bind_op -op mul -impl fabric "case_99" m46
set_directive_bind_op -op mul -impl fabric "case_99" m47
set_directive_bind_op -op mul -impl fabric "case_99" m48
set_directive_bind_op -op mul -impl fabric "case_99" m49
set_directive_bind_op -op mul -impl fabric "case_99" m50
set_directive_bind_op -op mul -impl fabric "case_99" m51
set_directive_bind_op -op mul -impl fabric "case_99" m52
set_directive_bind_op -op mul -impl fabric "case_99" m53
set_directive_bind_op -op mul -impl fabric "case_99" m54
set_directive_bind_op -op mul -impl fabric "case_99" m55
set_directive_bind_op -op mul -impl fabric "case_99" m56
set_directive_bind_op -op mul -impl fabric "case_99" m57
set_directive_bind_op -op mul -impl fabric "case_99" m58
set_directive_bind_op -op mul -impl fabric "case_99" m59
set_directive_bind_op -op mul -impl fabric "case_99" m60
set_directive_bind_op -op mul -impl fabric "case_99" m61
set_directive_bind_op -op mul -impl fabric "case_99" m62
set_directive_bind_op -op mul -impl fabric "case_99" m63
set_directive_bind_op -op mul -impl fabric "case_99" m64
set_directive_bind_op -op mul -impl fabric "case_99" m65
set_directive_bind_op -op mul -impl fabric "case_99" m66
set_directive_bind_op -op mul -impl fabric "case_99" m67
set_directive_bind_op -op mul -impl fabric "case_99" m68
set_directive_bind_op -op mul -impl fabric "case_99" m69
set_directive_bind_op -op mul -impl fabric "case_99" m70
set_directive_bind_op -op mul -impl fabric "case_99" m71
set_directive_bind_op -op mul -impl fabric "case_99" m72
set_directive_bind_op -op mul -impl fabric "case_99" m73
set_directive_bind_op -op mul -impl fabric "case_99" m74
set_directive_bind_op -op mul -impl fabric "case_99" m75
set_directive_bind_op -op mul -impl fabric "case_99" m76
set_directive_bind_op -op mul -impl fabric "case_99" m77
set_directive_bind_op -op mul -impl fabric "case_99" m78
set_directive_bind_op -op mul -impl fabric "case_99" m79
set_directive_bind_op -op mul -impl fabric "case_99" m80
set_directive_bind_op -op mul -impl fabric "case_99" m81
set_directive_bind_op -op mul -impl fabric "case_99" m82
set_directive_bind_op -op mul -impl fabric "case_99" m83
set_directive_bind_op -op mul -impl fabric "case_99" m84
set_directive_bind_op -op mul -impl fabric "case_99" m85
set_directive_bind_op -op mul -impl fabric "case_99" m86
set_directive_bind_op -op mul -impl fabric "case_99" m87
set_directive_bind_op -op mul -impl fabric "case_99" m88
set_directive_bind_op -op mul -impl fabric "case_99" m89
set_directive_bind_op -op mul -impl fabric "case_99" m90
set_directive_bind_op -op mul -impl fabric "case_99" m91
set_directive_bind_op -op mul -impl fabric "case_99" m92
set_directive_bind_op -op mul -impl fabric "case_99" m93
set_directive_bind_op -op mul -impl fabric "case_99" m94
set_directive_bind_op -op mul -impl fabric "case_99" m95
set_directive_bind_op -op mul -impl fabric "case_99" m96
set_directive_bind_op -op mul -impl fabric "case_99" m97
set_directive_bind_op -op mul -impl fabric "case_99" m98
set_directive_bind_op -op mul -impl fabric "case_99" m99
set_directive_bind_op -op mul -impl fabric "case_99" m100
set_directive_bind_op -op mul -impl fabric "case_99" m101
set_directive_bind_op -op mul -impl fabric "case_99" m102
set_directive_bind_op -op mul -impl fabric "case_99" m103
set_directive_bind_op -op mul -impl fabric "case_99" m104
set_directive_bind_op -op mul -impl fabric "case_99" m105
set_directive_bind_op -op mul -impl fabric "case_99" m106
set_directive_bind_op -op mul -impl fabric "case_99" m107
set_directive_bind_op -op mul -impl fabric "case_99" m108
set_directive_bind_op -op mul -impl fabric "case_99" m109
set_directive_bind_op -op mul -impl fabric "case_99" m110
set_directive_bind_op -op mul -impl fabric "case_99" m111
set_directive_bind_op -op mul -impl fabric "case_99" m112
set_directive_bind_op -op mul -impl fabric "case_99" m113
set_directive_bind_op -op mul -impl fabric "case_99" m114
set_directive_bind_op -op mul -impl fabric "case_99" m115
set_directive_bind_op -op mul -impl fabric "case_99" m116
set_directive_bind_op -op mul -impl fabric "case_99" m117
set_directive_bind_op -op mul -impl fabric "case_99" m118
set_directive_bind_op -op mul -impl fabric "case_99" m119
set_directive_bind_op -op mul -impl fabric "case_99" m120
set_directive_bind_op -op mul -impl fabric "case_99" m121
set_directive_bind_op -op mul -impl fabric "case_99" m122
set_directive_bind_op -op mul -impl fabric "case_99" m123
set_directive_bind_op -op mul -impl fabric "case_99" m124
set_directive_bind_op -op mul -impl fabric "case_99" m125
set_directive_bind_op -op mul -impl fabric "case_99" m126
set_directive_bind_op -op mul -impl fabric "case_99" m127

