set_directive_resource -core Mul_LUT "case_7" m28
set_directive_resource -core Mul_LUT "case_7" m29
set_directive_resource -core Mul_LUT "case_7" m30
set_directive_resource -core Mul_LUT "case_7" m31
set_directive_resource -core Mul_LUT "case_7" m32
set_directive_resource -core Mul_LUT "case_7" m33
set_directive_resource -core Mul_LUT "case_7" m34
set_directive_resource -core Mul_LUT "case_7" m35
set_directive_resource -core Mul_LUT "case_7" m36
set_directive_resource -core Mul_LUT "case_7" m37
set_directive_resource -core Mul_LUT "case_7" m38
set_directive_resource -core Mul_LUT "case_7" m39
set_directive_resource -core Mul_LUT "case_7" m40
set_directive_resource -core Mul_LUT "case_7" m41
set_directive_resource -core Mul_LUT "case_7" m42
set_directive_resource -core Mul_LUT "case_7" m43
set_directive_resource -core Mul_LUT "case_7" m44
set_directive_resource -core Mul_LUT "case_7" m45
set_directive_resource -core Mul_LUT "case_7" m46
set_directive_resource -core Mul_LUT "case_7" m47
set_directive_resource -core Mul_LUT "case_7" m48
set_directive_resource -core Mul_LUT "case_7" m49
set_directive_resource -core Mul_LUT "case_7" m50
set_directive_resource -core Mul_LUT "case_7" m51
set_directive_resource -core Mul_LUT "case_7" m52
set_directive_resource -core Mul_LUT "case_7" m53
set_directive_resource -core Mul_LUT "case_7" m54
set_directive_resource -core Mul_LUT "case_7" m55
set_directive_resource -core Mul_LUT "case_7" m56
set_directive_resource -core Mul_LUT "case_7" m57
set_directive_resource -core Mul_LUT "case_7" m58
set_directive_resource -core Mul_LUT "case_7" m59
set_directive_resource -core Mul_LUT "case_7" m60
set_directive_resource -core Mul_LUT "case_7" m61
set_directive_resource -core Mul_LUT "case_7" m62
set_directive_resource -core Mul_LUT "case_7" m63
set_directive_resource -core Mul_LUT "case_7" m64
set_directive_resource -core Mul_LUT "case_7" m65
set_directive_resource -core Mul_LUT "case_7" m66
set_directive_resource -core Mul_LUT "case_7" m67
set_directive_resource -core Mul_LUT "case_7" m68
set_directive_resource -core Mul_LUT "case_7" m69
set_directive_resource -core Mul_LUT "case_7" m70
set_directive_resource -core Mul_LUT "case_7" m71
set_directive_resource -core Mul_LUT "case_7" m72
set_directive_resource -core Mul_LUT "case_7" m73
set_directive_resource -core Mul_LUT "case_7" m74
set_directive_resource -core Mul_LUT "case_7" m75
set_directive_resource -core Mul_LUT "case_7" m76
set_directive_resource -core Mul_LUT "case_7" m77
set_directive_resource -core Mul_LUT "case_7" m78
set_directive_resource -core Mul_LUT "case_7" m79
set_directive_resource -core Mul_LUT "case_7" m80
set_directive_resource -core Mul_LUT "case_7" m81
set_directive_resource -core Mul_LUT "case_7" m82
set_directive_resource -core Mul_LUT "case_7" m83
set_directive_resource -core Mul_LUT "case_7" m84
set_directive_resource -core Mul_LUT "case_7" m85
set_directive_resource -core Mul_LUT "case_7" m86
set_directive_resource -core Mul_LUT "case_7" m87
set_directive_resource -core Mul_LUT "case_7" m88
set_directive_resource -core Mul_LUT "case_7" m89
set_directive_resource -core Mul_LUT "case_7" m90
set_directive_resource -core Mul_LUT "case_7" m91
set_directive_resource -core Mul_LUT "case_7" m92
set_directive_resource -core Mul_LUT "case_7" m93
set_directive_resource -core Mul_LUT "case_7" m94
set_directive_resource -core Mul_LUT "case_7" m95
set_directive_resource -core Mul_LUT "case_7" m96
set_directive_resource -core Mul_LUT "case_7" m97
set_directive_resource -core Mul_LUT "case_7" m98
set_directive_resource -core Mul_LUT "case_7" m99
set_directive_resource -core Mul_LUT "case_7" m100
set_directive_resource -core Mul_LUT "case_7" m101
set_directive_resource -core Mul_LUT "case_7" m102
set_directive_resource -core Mul_LUT "case_7" m103
set_directive_resource -core Mul_LUT "case_7" m104
set_directive_resource -core Mul_LUT "case_7" m105
set_directive_resource -core Mul_LUT "case_7" m106
set_directive_resource -core Mul_LUT "case_7" m107
set_directive_resource -core Mul_LUT "case_7" m108
set_directive_resource -core Mul_LUT "case_7" m109
set_directive_resource -core Mul_LUT "case_7" m110
set_directive_resource -core Mul_LUT "case_7" m111
set_directive_resource -core Mul_LUT "case_7" m112
set_directive_resource -core Mul_LUT "case_7" m113
set_directive_resource -core Mul_LUT "case_7" m114
set_directive_resource -core Mul_LUT "case_7" m115
set_directive_resource -core Mul_LUT "case_7" m116
set_directive_resource -core Mul_LUT "case_7" m117
set_directive_resource -core Mul_LUT "case_7" m118
set_directive_resource -core Mul_LUT "case_7" m119
set_directive_resource -core Mul_LUT "case_7" m120
set_directive_resource -core Mul_LUT "case_7" m121
set_directive_resource -core Mul_LUT "case_7" m122
set_directive_resource -core Mul_LUT "case_7" m123
set_directive_resource -core Mul_LUT "case_7" m124
set_directive_resource -core Mul_LUT "case_7" m125
set_directive_resource -core Mul_LUT "case_7" m126
set_directive_resource -core Mul_LUT "case_7" m127
set_directive_resource -core Mul_LUT "case_7" m128
set_directive_resource -core Mul_LUT "case_7" m129
set_directive_resource -core Mul_LUT "case_7" m130
set_directive_resource -core Mul_LUT "case_7" m131
set_directive_resource -core Mul_LUT "case_7" m132
set_directive_resource -core Mul_LUT "case_7" m133
set_directive_resource -core Mul_LUT "case_7" m134
set_directive_resource -core Mul_LUT "case_7" m135
set_directive_resource -core Mul_LUT "case_7" m136
set_directive_resource -core Mul_LUT "case_7" m137
set_directive_resource -core Mul_LUT "case_7" m138
set_directive_resource -core Mul_LUT "case_7" m139
set_directive_resource -core Mul_LUT "case_7" m140
set_directive_resource -core Mul_LUT "case_7" m141
set_directive_resource -core Mul_LUT "case_7" m142
set_directive_resource -core Mul_LUT "case_7" m143
set_directive_resource -core Mul_LUT "case_7" m144
set_directive_resource -core Mul_LUT "case_7" m145
set_directive_resource -core Mul_LUT "case_7" m146
set_directive_resource -core Mul_LUT "case_7" m147
set_directive_resource -core Mul_LUT "case_7" m148
set_directive_resource -core Mul_LUT "case_7" m149
set_directive_resource -core Mul_LUT "case_7" m150
set_directive_resource -core Mul_LUT "case_7" m151
set_directive_resource -core Mul_LUT "case_7" m152
set_directive_resource -core Mul_LUT "case_7" m153
set_directive_resource -core Mul_LUT "case_7" m154
set_directive_resource -core Mul_LUT "case_7" m155
set_directive_resource -core Mul_LUT "case_7" m156
set_directive_resource -core Mul_LUT "case_7" m157
set_directive_resource -core Mul_LUT "case_7" m158
set_directive_resource -core Mul_LUT "case_7" m159
set_directive_resource -core Mul_LUT "case_7" m160
set_directive_resource -core Mul_LUT "case_7" m161
set_directive_resource -core Mul_LUT "case_7" m162
set_directive_resource -core Mul_LUT "case_7" m163
set_directive_resource -core Mul_LUT "case_7" m164
set_directive_resource -core Mul_LUT "case_7" m165
set_directive_resource -core Mul_LUT "case_7" m166
set_directive_resource -core Mul_LUT "case_7" m167
set_directive_resource -core Mul_LUT "case_7" m168
set_directive_resource -core Mul_LUT "case_7" m169
set_directive_resource -core Mul_LUT "case_7" m170
set_directive_resource -core Mul_LUT "case_7" m171
set_directive_resource -core Mul_LUT "case_7" m172
set_directive_resource -core Mul_LUT "case_7" m173
set_directive_resource -core Mul_LUT "case_7" m174
set_directive_resource -core Mul_LUT "case_7" m175
set_directive_resource -core Mul_LUT "case_7" m176
set_directive_resource -core Mul_LUT "case_7" m177
set_directive_resource -core Mul_LUT "case_7" m178
set_directive_resource -core Mul_LUT "case_7" m179
set_directive_resource -core Mul_LUT "case_7" m180
set_directive_resource -core Mul_LUT "case_7" m181
set_directive_resource -core Mul_LUT "case_7" m182
set_directive_resource -core Mul_LUT "case_7" m183
set_directive_resource -core Mul_LUT "case_7" m184
set_directive_resource -core Mul_LUT "case_7" m185
set_directive_resource -core Mul_LUT "case_7" m186
set_directive_resource -core Mul_LUT "case_7" m187
set_directive_resource -core Mul_LUT "case_7" m188
set_directive_resource -core Mul_LUT "case_7" m189
set_directive_resource -core Mul_LUT "case_7" m190
set_directive_resource -core Mul_LUT "case_7" m191
set_directive_resource -core Mul_LUT "case_7" m192
set_directive_resource -core Mul_LUT "case_7" m193
set_directive_resource -core Mul_LUT "case_7" m194
set_directive_resource -core Mul_LUT "case_7" m195
set_directive_resource -core Mul_LUT "case_7" m196
set_directive_resource -core Mul_LUT "case_7" m197
set_directive_resource -core Mul_LUT "case_7" m198
set_directive_resource -core Mul_LUT "case_7" m199
set_directive_resource -core Mul_LUT "case_7" m200
set_directive_resource -core Mul_LUT "case_7" m201
set_directive_resource -core Mul_LUT "case_7" m202
set_directive_resource -core Mul_LUT "case_7" m203
set_directive_resource -core Mul_LUT "case_7" m204
set_directive_resource -core Mul_LUT "case_7" m205
set_directive_resource -core Mul_LUT "case_7" m206
set_directive_resource -core Mul_LUT "case_7" m207
set_directive_resource -core Mul_LUT "case_7" m208
set_directive_resource -core Mul_LUT "case_7" m209
set_directive_resource -core Mul_LUT "case_7" m210
set_directive_resource -core Mul_LUT "case_7" m211
set_directive_resource -core Mul_LUT "case_7" m212
set_directive_resource -core Mul_LUT "case_7" m213

