set_directive_bind_op -op mul -impl fabric "case_13" m14
set_directive_bind_op -op mul -impl fabric "case_13" m15
set_directive_bind_op -op mul -impl fabric "case_13" m16
set_directive_bind_op -op mul -impl fabric "case_13" m17
set_directive_bind_op -op mul -impl fabric "case_13" m18
set_directive_bind_op -op mul -impl fabric "case_13" m19
set_directive_bind_op -op mul -impl fabric "case_13" m20
set_directive_bind_op -op mul -impl fabric "case_13" m21
set_directive_bind_op -op mul -impl fabric "case_13" m22
set_directive_bind_op -op mul -impl fabric "case_13" m23
set_directive_bind_op -op mul -impl fabric "case_13" m24
set_directive_bind_op -op mul -impl fabric "case_13" m25
set_directive_bind_op -op mul -impl fabric "case_13" m26
set_directive_bind_op -op mul -impl fabric "case_13" m27
set_directive_bind_op -op mul -impl fabric "case_13" m28
set_directive_bind_op -op mul -impl fabric "case_13" m29
set_directive_bind_op -op mul -impl fabric "case_13" m30
set_directive_bind_op -op mul -impl fabric "case_13" m31
set_directive_bind_op -op mul -impl fabric "case_13" m32
set_directive_bind_op -op mul -impl fabric "case_13" m33
set_directive_bind_op -op mul -impl fabric "case_13" m34
set_directive_bind_op -op mul -impl fabric "case_13" m35
set_directive_bind_op -op mul -impl fabric "case_13" m36
set_directive_bind_op -op mul -impl fabric "case_13" m37
set_directive_bind_op -op mul -impl fabric "case_13" m38
set_directive_bind_op -op mul -impl fabric "case_13" m39
set_directive_bind_op -op mul -impl fabric "case_13" m40
set_directive_bind_op -op mul -impl fabric "case_13" m41
set_directive_bind_op -op mul -impl fabric "case_13" m42
set_directive_bind_op -op mul -impl fabric "case_13" m43
set_directive_bind_op -op mul -impl fabric "case_13" m44
set_directive_bind_op -op mul -impl fabric "case_13" m45
set_directive_bind_op -op mul -impl fabric "case_13" m46
set_directive_bind_op -op mul -impl fabric "case_13" m47
set_directive_bind_op -op mul -impl fabric "case_13" m48
set_directive_bind_op -op mul -impl fabric "case_13" m49
set_directive_bind_op -op mul -impl fabric "case_13" m50
set_directive_bind_op -op mul -impl fabric "case_13" m51
set_directive_bind_op -op mul -impl fabric "case_13" m52
set_directive_bind_op -op mul -impl fabric "case_13" m53
set_directive_bind_op -op mul -impl fabric "case_13" m54
set_directive_bind_op -op mul -impl fabric "case_13" m55
set_directive_bind_op -op mul -impl fabric "case_13" m56
set_directive_bind_op -op mul -impl fabric "case_13" m57

