-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_data_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_data_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_0_ap_vld : OUT STD_LOGIC;
    out_data_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_1_ap_vld : OUT STD_LOGIC;
    out_data_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_2_ap_vld : OUT STD_LOGIC;
    out_data_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_3_ap_vld : OUT STD_LOGIC;
    out_data_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_4_ap_vld : OUT STD_LOGIC;
    out_data_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_5_ap_vld : OUT STD_LOGIC;
    out_data_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_6_ap_vld : OUT STD_LOGIC;
    out_data_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_7_ap_vld : OUT STD_LOGIC;
    out_data_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_8_ap_vld : OUT STD_LOGIC;
    out_data_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_9_ap_vld : OUT STD_LOGIC;
    out_data_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_10_ap_vld : OUT STD_LOGIC;
    out_data_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_11_ap_vld : OUT STD_LOGIC;
    out_data_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_12_ap_vld : OUT STD_LOGIC;
    out_data_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_13_ap_vld : OUT STD_LOGIC;
    out_data_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_14_ap_vld : OUT STD_LOGIC;
    out_data_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_15_ap_vld : OUT STD_LOGIC;
    out_data_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_16_ap_vld : OUT STD_LOGIC;
    out_data_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_17_ap_vld : OUT STD_LOGIC );
end;


architecture behav of case_3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "case_3_case_3,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.620000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=95,HLS_SYN_LUT=500,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in5_fu_221_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal in5_reg_357 : STD_LOGIC_VECTOR (5 downto 0);
    signal m6_fu_229_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal m6_reg_362 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln221_fu_243_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln221_reg_377 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln227_fu_250_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln227_reg_382 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln227_1_fu_258_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln227_1_reg_387 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln225_fu_271_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln225_reg_398 : STD_LOGIC_VECTOR (8 downto 0);
    signal m13_fu_286_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m13_reg_403 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal m14_fu_292_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal m14_reg_409 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln228_fu_296_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln228_reg_414 : STD_LOGIC_VECTOR (5 downto 0);
    signal m15_fu_305_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m15_reg_420 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal m16_fu_309_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m16_reg_426 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal trunc_ln219_fu_225_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal m10_fu_263_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_347_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln226_fu_283_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal m12_fu_278_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal m17_fu_319_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal m19_fu_336_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_347_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_3_mul_9s_9s_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component case_3_mul_10s_9s_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component case_3_mul_10s_6s_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component case_3_mul_9s_7s_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component case_3_mul_6s_6s_6_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component case_3_mul_10s_10s_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component case_3_mul_6s_6s_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component case_3_mul_10s_6s_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component case_3_mac_muladd_7s_6s_5s_7_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    mul_9s_9s_9_1_1_U1 : component case_3_mul_9s_9s_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 9)
    port map (
        din0 => trunc_ln219_fu_225_p1,
        din1 => trunc_ln219_fu_225_p1,
        dout => m6_fu_229_p2);

    mul_10s_9s_10_1_1_U2 : component case_3_mul_10s_9s_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 9,
        dout_WIDTH => 10)
    port map (
        din0 => trunc_ln221_reg_377,
        din1 => m6_reg_362,
        dout => mul_ln227_fu_250_p2);

    mul_10s_6s_10_1_1_U3 : component case_3_mul_10s_6s_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 6,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln227_reg_382,
        din1 => in5_reg_357,
        dout => mul_ln227_1_fu_258_p2);

    mul_9s_7s_9_1_1_U4 : component case_3_mul_9s_7s_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 7,
        dout_WIDTH => 9)
    port map (
        din0 => trunc_ln225_reg_398,
        din1 => grp_fu_347_p3,
        dout => m12_fu_278_p2);

    mul_6s_6s_6_1_1_U5 : component case_3_mul_6s_6s_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 6)
    port map (
        din0 => trunc_ln226_fu_283_p1,
        din1 => trunc_ln226_fu_283_p1,
        dout => m13_fu_286_p2);

    mul_10s_10s_10_1_1_U6 : component case_3_mul_10s_10s_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln227_1_reg_387,
        din1 => mul_ln227_1_reg_387,
        dout => m14_fu_292_p2);

    mul_6s_6s_6_1_1_U7 : component case_3_mul_6s_6s_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 6)
    port map (
        din0 => m13_reg_403,
        din1 => trunc_ln228_reg_414,
        dout => m15_fu_305_p2);

    mul_6s_6s_6_1_1_U8 : component case_3_mul_6s_6s_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 6)
    port map (
        din0 => m15_reg_420,
        din1 => trunc_ln228_reg_414,
        dout => m16_fu_309_p2);

    mul_6s_6s_7_1_1_U9 : component case_3_mul_6s_6s_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 7)
    port map (
        din0 => m15_reg_420,
        din1 => m13_reg_403,
        dout => m17_fu_319_p2);

    mul_10s_6s_11_1_1_U10 : component case_3_mul_10s_6s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        din0 => m14_reg_409,
        din1 => m16_reg_426,
        dout => m19_fu_336_p2);

    mac_muladd_7s_6s_5s_7_4_1_U11 : component case_3_mac_muladd_7s_6s_5s_7_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 6,
        din2_WIDTH => 5,
        dout_WIDTH => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_347_p0,
        din1 => in5_fu_221_p1,
        din2 => m10_fu_263_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_347_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                in5_reg_357 <= in5_fu_221_p1;
                m6_reg_362 <= m6_fu_229_p2;
                trunc_ln221_reg_377 <= trunc_ln221_fu_243_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                m13_reg_403 <= m13_fu_286_p2;
                m14_reg_409 <= m14_fu_292_p2;
                trunc_ln228_reg_414 <= trunc_ln228_fu_296_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                m15_reg_420 <= m15_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                m16_reg_426 <= m16_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln227_1_reg_387 <= mul_ln227_1_fu_258_p2;
                trunc_ln225_reg_398 <= trunc_ln225_fu_271_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                mul_ln227_reg_382 <= mul_ln227_fu_250_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_347_p0 <= in_data_2(7 - 1 downto 0);
    in5_fu_221_p1 <= in_data_4(6 - 1 downto 0);
    m10_fu_263_p1 <= mul_ln227_1_fu_258_p2(5 - 1 downto 0);
        out_data_0 <= std_logic_vector(IEEE.numeric_std.resize(signed(m12_fu_278_p2),16));


    out_data_0_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_data_0_ap_vld <= ap_const_logic_1;
        else 
            out_data_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        out_data_1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m17_fu_319_p2),16));

    out_data_10 <= ap_const_lv16_0;

    out_data_10_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_10_ap_vld <= ap_const_logic_1;
        else 
            out_data_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_11 <= ap_const_lv16_0;

    out_data_11_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_11_ap_vld <= ap_const_logic_1;
        else 
            out_data_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_12 <= ap_const_lv16_0;

    out_data_12_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_12_ap_vld <= ap_const_logic_1;
        else 
            out_data_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_13 <= ap_const_lv16_0;

    out_data_13_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_13_ap_vld <= ap_const_logic_1;
        else 
            out_data_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_14 <= ap_const_lv16_0;

    out_data_14_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_14_ap_vld <= ap_const_logic_1;
        else 
            out_data_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_15 <= ap_const_lv16_0;

    out_data_15_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_15_ap_vld <= ap_const_logic_1;
        else 
            out_data_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_16 <= ap_const_lv16_0;

    out_data_16_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_16_ap_vld <= ap_const_logic_1;
        else 
            out_data_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_17 <= ap_const_lv16_0;

    out_data_17_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_17_ap_vld <= ap_const_logic_1;
        else 
            out_data_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    out_data_1_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_data_1_ap_vld <= ap_const_logic_1;
        else 
            out_data_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        out_data_2 <= std_logic_vector(IEEE.numeric_std.resize(signed(m19_fu_336_p2),16));


    out_data_2_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_2_ap_vld <= ap_const_logic_1;
        else 
            out_data_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_3 <= ap_const_lv16_0;

    out_data_3_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_3_ap_vld <= ap_const_logic_1;
        else 
            out_data_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_4 <= ap_const_lv16_0;

    out_data_4_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_4_ap_vld <= ap_const_logic_1;
        else 
            out_data_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_5 <= ap_const_lv16_0;

    out_data_5_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_5_ap_vld <= ap_const_logic_1;
        else 
            out_data_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_6 <= ap_const_lv16_0;

    out_data_6_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_6_ap_vld <= ap_const_logic_1;
        else 
            out_data_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_7 <= ap_const_lv16_0;

    out_data_7_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_7_ap_vld <= ap_const_logic_1;
        else 
            out_data_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_8 <= ap_const_lv16_0;

    out_data_8_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_8_ap_vld <= ap_const_logic_1;
        else 
            out_data_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_9 <= ap_const_lv16_0;

    out_data_9_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_9_ap_vld <= ap_const_logic_1;
        else 
            out_data_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln219_fu_225_p1 <= in_data_2(9 - 1 downto 0);
    trunc_ln221_fu_243_p1 <= in_data_2(10 - 1 downto 0);
    trunc_ln225_fu_271_p1 <= mul_ln227_1_fu_258_p2(9 - 1 downto 0);
    trunc_ln226_fu_283_p1 <= grp_fu_347_p3(6 - 1 downto 0);
    trunc_ln228_fu_296_p1 <= m14_fu_292_p2(6 - 1 downto 0);
end behav;
