set_directive_bind_op -op mul -impl fabric "case_9" m7
set_directive_bind_op -op mul -impl fabric "case_9" m8
set_directive_bind_op -op mul -impl fabric "case_9" m9
set_directive_bind_op -op mul -impl fabric "case_9" m10
set_directive_bind_op -op mul -impl fabric "case_9" m11
set_directive_bind_op -op mul -impl fabric "case_9" m12
set_directive_bind_op -op mul -impl fabric "case_9" m13
set_directive_bind_op -op mul -impl fabric "case_9" m14
set_directive_bind_op -op mul -impl fabric "case_9" m15
set_directive_bind_op -op mul -impl fabric "case_9" m16
set_directive_bind_op -op mul -impl fabric "case_9" m17
set_directive_bind_op -op mul -impl fabric "case_9" m18
set_directive_bind_op -op mul -impl fabric "case_9" m19
set_directive_bind_op -op mul -impl fabric "case_9" m20
set_directive_bind_op -op mul -impl fabric "case_9" m21
set_directive_bind_op -op mul -impl fabric "case_9" m22
set_directive_bind_op -op mul -impl fabric "case_9" m23
set_directive_bind_op -op mul -impl fabric "case_9" m24
set_directive_bind_op -op mul -impl fabric "case_9" m25

