set_directive_bind_op -op mul -impl fabric "case_24" m26
set_directive_bind_op -op mul -impl fabric "case_24" m27
set_directive_bind_op -op mul -impl fabric "case_24" m28
set_directive_bind_op -op mul -impl fabric "case_24" m29
set_directive_bind_op -op mul -impl fabric "case_24" m30
set_directive_bind_op -op mul -impl fabric "case_24" m31
set_directive_bind_op -op mul -impl fabric "case_24" m32
set_directive_bind_op -op mul -impl fabric "case_24" m33
set_directive_bind_op -op mul -impl fabric "case_24" m34
set_directive_bind_op -op mul -impl fabric "case_24" m35
set_directive_bind_op -op mul -impl fabric "case_24" m36
set_directive_bind_op -op mul -impl fabric "case_24" m37
set_directive_bind_op -op mul -impl fabric "case_24" m38
set_directive_bind_op -op mul -impl fabric "case_24" m39
set_directive_bind_op -op mul -impl fabric "case_24" m40
set_directive_bind_op -op mul -impl fabric "case_24" m41
set_directive_bind_op -op mul -impl fabric "case_24" m42
set_directive_bind_op -op mul -impl fabric "case_24" m43
set_directive_bind_op -op mul -impl fabric "case_24" m44
set_directive_bind_op -op mul -impl fabric "case_24" m45
set_directive_bind_op -op mul -impl fabric "case_24" m46
set_directive_bind_op -op mul -impl fabric "case_24" m47
set_directive_bind_op -op mul -impl fabric "case_24" m48
set_directive_bind_op -op mul -impl fabric "case_24" m49
set_directive_bind_op -op mul -impl fabric "case_24" m50
set_directive_bind_op -op mul -impl fabric "case_24" m51
set_directive_bind_op -op mul -impl fabric "case_24" m52
set_directive_bind_op -op mul -impl fabric "case_24" m53
set_directive_bind_op -op mul -impl fabric "case_24" m54
set_directive_bind_op -op mul -impl fabric "case_24" m55
set_directive_bind_op -op mul -impl fabric "case_24" m56
set_directive_bind_op -op mul -impl fabric "case_24" m57
set_directive_bind_op -op mul -impl fabric "case_24" m58
set_directive_bind_op -op mul -impl fabric "case_24" m59
set_directive_bind_op -op mul -impl fabric "case_24" m60
set_directive_bind_op -op mul -impl fabric "case_24" m61
set_directive_bind_op -op mul -impl fabric "case_24" m62
set_directive_bind_op -op mul -impl fabric "case_24" m63
set_directive_bind_op -op mul -impl fabric "case_24" m64
set_directive_bind_op -op mul -impl fabric "case_24" m65
set_directive_bind_op -op mul -impl fabric "case_24" m66
set_directive_bind_op -op mul -impl fabric "case_24" m67
set_directive_bind_op -op mul -impl fabric "case_24" m68
set_directive_bind_op -op mul -impl fabric "case_24" m69
set_directive_bind_op -op mul -impl fabric "case_24" m70
set_directive_bind_op -op mul -impl fabric "case_24" m71
set_directive_bind_op -op mul -impl fabric "case_24" m72
set_directive_bind_op -op mul -impl fabric "case_24" m73
set_directive_bind_op -op mul -impl fabric "case_24" m74
set_directive_bind_op -op mul -impl fabric "case_24" m75
set_directive_bind_op -op mul -impl fabric "case_24" m76
set_directive_bind_op -op mul -impl fabric "case_24" m77
set_directive_bind_op -op mul -impl fabric "case_24" m78
set_directive_bind_op -op mul -impl fabric "case_24" m79
set_directive_bind_op -op mul -impl fabric "case_24" m80
set_directive_bind_op -op mul -impl fabric "case_24" m81
set_directive_bind_op -op mul -impl fabric "case_24" m82
set_directive_bind_op -op mul -impl fabric "case_24" m83
set_directive_bind_op -op mul -impl fabric "case_24" m84
set_directive_bind_op -op mul -impl fabric "case_24" m85
set_directive_bind_op -op mul -impl fabric "case_24" m86
set_directive_bind_op -op mul -impl fabric "case_24" m87
set_directive_bind_op -op mul -impl fabric "case_24" m88
set_directive_bind_op -op mul -impl fabric "case_24" m89
set_directive_bind_op -op mul -impl fabric "case_24" m90
set_directive_bind_op -op mul -impl fabric "case_24" m91
set_directive_bind_op -op mul -impl fabric "case_24" m92
set_directive_bind_op -op mul -impl fabric "case_24" m93
set_directive_bind_op -op mul -impl fabric "case_24" m94
set_directive_bind_op -op mul -impl fabric "case_24" m95
set_directive_bind_op -op mul -impl fabric "case_24" m96
set_directive_bind_op -op mul -impl fabric "case_24" m97
set_directive_bind_op -op mul -impl fabric "case_24" m98
set_directive_bind_op -op mul -impl fabric "case_24" m99
set_directive_bind_op -op mul -impl fabric "case_24" m100
set_directive_bind_op -op mul -impl fabric "case_24" m101
set_directive_bind_op -op mul -impl fabric "case_24" m102
set_directive_bind_op -op mul -impl fabric "case_24" m103
set_directive_bind_op -op mul -impl fabric "case_24" m104
set_directive_bind_op -op mul -impl fabric "case_24" m105
set_directive_bind_op -op mul -impl fabric "case_24" m106
set_directive_bind_op -op mul -impl fabric "case_24" m107
set_directive_bind_op -op mul -impl fabric "case_24" m108
set_directive_bind_op -op mul -impl fabric "case_24" m109
set_directive_bind_op -op mul -impl fabric "case_24" m110
set_directive_bind_op -op mul -impl fabric "case_24" m111
set_directive_bind_op -op mul -impl fabric "case_24" m112
set_directive_bind_op -op mul -impl fabric "case_24" m113
set_directive_bind_op -op mul -impl fabric "case_24" m114
set_directive_bind_op -op mul -impl fabric "case_24" m115
set_directive_bind_op -op mul -impl fabric "case_24" m116
set_directive_bind_op -op mul -impl fabric "case_24" m117
set_directive_bind_op -op mul -impl fabric "case_24" m118
set_directive_bind_op -op mul -impl fabric "case_24" m119
set_directive_bind_op -op mul -impl fabric "case_24" m120
set_directive_bind_op -op mul -impl fabric "case_24" m121
set_directive_bind_op -op mul -impl fabric "case_24" m122
set_directive_bind_op -op mul -impl fabric "case_24" m123
set_directive_bind_op -op mul -impl fabric "case_24" m124
set_directive_bind_op -op mul -impl fabric "case_24" m125
set_directive_bind_op -op mul -impl fabric "case_24" m126
set_directive_bind_op -op mul -impl fabric "case_24" m127
set_directive_bind_op -op mul -impl fabric "case_24" m128
set_directive_bind_op -op mul -impl fabric "case_24" m129
set_directive_bind_op -op mul -impl fabric "case_24" m130
set_directive_bind_op -op mul -impl fabric "case_24" m131
set_directive_bind_op -op mul -impl fabric "case_24" m132
set_directive_bind_op -op mul -impl fabric "case_24" m133
set_directive_bind_op -op mul -impl fabric "case_24" m134
set_directive_bind_op -op mul -impl fabric "case_24" m135
set_directive_bind_op -op mul -impl fabric "case_24" m136

