set_directive_bind_op -op mul -impl fabric "case_60" m13
set_directive_bind_op -op mul -impl fabric "case_60" m14
set_directive_bind_op -op mul -impl fabric "case_60" m15
set_directive_bind_op -op mul -impl fabric "case_60" m16
set_directive_bind_op -op mul -impl fabric "case_60" m17
set_directive_bind_op -op mul -impl fabric "case_60" m18
set_directive_bind_op -op mul -impl fabric "case_60" m19
set_directive_bind_op -op mul -impl fabric "case_60" m20
set_directive_bind_op -op mul -impl fabric "case_60" m21
set_directive_bind_op -op mul -impl fabric "case_60" m22
set_directive_bind_op -op mul -impl fabric "case_60" m23
set_directive_bind_op -op mul -impl fabric "case_60" m24
set_directive_bind_op -op mul -impl fabric "case_60" m25
set_directive_bind_op -op mul -impl fabric "case_60" m26
set_directive_bind_op -op mul -impl fabric "case_60" m27
set_directive_bind_op -op mul -impl fabric "case_60" m28
set_directive_bind_op -op mul -impl fabric "case_60" m29
set_directive_bind_op -op mul -impl fabric "case_60" m30
set_directive_bind_op -op mul -impl fabric "case_60" m31
set_directive_bind_op -op mul -impl fabric "case_60" m32
set_directive_bind_op -op mul -impl fabric "case_60" m33
set_directive_bind_op -op mul -impl fabric "case_60" m34
set_directive_bind_op -op mul -impl fabric "case_60" m35
set_directive_bind_op -op mul -impl fabric "case_60" m36
set_directive_bind_op -op mul -impl fabric "case_60" m37
set_directive_bind_op -op mul -impl fabric "case_60" m38
set_directive_bind_op -op mul -impl fabric "case_60" m39
set_directive_bind_op -op mul -impl fabric "case_60" m40
set_directive_bind_op -op mul -impl fabric "case_60" m41
set_directive_bind_op -op mul -impl fabric "case_60" m42
set_directive_bind_op -op mul -impl fabric "case_60" m43
set_directive_bind_op -op mul -impl fabric "case_60" m44
set_directive_bind_op -op mul -impl fabric "case_60" m45
set_directive_bind_op -op mul -impl fabric "case_60" m46
set_directive_bind_op -op mul -impl fabric "case_60" m47
set_directive_bind_op -op mul -impl fabric "case_60" m48
set_directive_bind_op -op mul -impl fabric "case_60" m49
set_directive_bind_op -op mul -impl fabric "case_60" m50
set_directive_bind_op -op mul -impl fabric "case_60" m51
set_directive_bind_op -op mul -impl fabric "case_60" m52
set_directive_bind_op -op mul -impl fabric "case_60" m53
set_directive_bind_op -op mul -impl fabric "case_60" m54
set_directive_bind_op -op mul -impl fabric "case_60" m55
set_directive_bind_op -op mul -impl fabric "case_60" m56
set_directive_bind_op -op mul -impl fabric "case_60" m57
set_directive_bind_op -op mul -impl fabric "case_60" m58
set_directive_bind_op -op mul -impl fabric "case_60" m59

