set_directive_bind_op -op mul -impl fabric "case_100" m22
set_directive_bind_op -op mul -impl fabric "case_100" m23
set_directive_bind_op -op mul -impl fabric "case_100" m24
set_directive_bind_op -op mul -impl fabric "case_100" m25
set_directive_bind_op -op mul -impl fabric "case_100" m26
set_directive_bind_op -op mul -impl fabric "case_100" m27
set_directive_bind_op -op mul -impl fabric "case_100" m28
set_directive_bind_op -op mul -impl fabric "case_100" m29
set_directive_bind_op -op mul -impl fabric "case_100" m30
set_directive_bind_op -op mul -impl fabric "case_100" m31
set_directive_bind_op -op mul -impl fabric "case_100" m32
set_directive_bind_op -op mul -impl fabric "case_100" m33
set_directive_bind_op -op mul -impl fabric "case_100" m34
set_directive_bind_op -op mul -impl fabric "case_100" m35
set_directive_bind_op -op mul -impl fabric "case_100" m36
set_directive_bind_op -op mul -impl fabric "case_100" m37
set_directive_bind_op -op mul -impl fabric "case_100" m38
set_directive_bind_op -op mul -impl fabric "case_100" m39
set_directive_bind_op -op mul -impl fabric "case_100" m40
set_directive_bind_op -op mul -impl fabric "case_100" m41
set_directive_bind_op -op mul -impl fabric "case_100" m42
set_directive_bind_op -op mul -impl fabric "case_100" m43
set_directive_bind_op -op mul -impl fabric "case_100" m44
set_directive_bind_op -op mul -impl fabric "case_100" m45
set_directive_bind_op -op mul -impl fabric "case_100" m46
set_directive_bind_op -op mul -impl fabric "case_100" m47
set_directive_bind_op -op mul -impl fabric "case_100" m48
set_directive_bind_op -op mul -impl fabric "case_100" m49
set_directive_bind_op -op mul -impl fabric "case_100" m50
set_directive_bind_op -op mul -impl fabric "case_100" m51
set_directive_bind_op -op mul -impl fabric "case_100" m52
set_directive_bind_op -op mul -impl fabric "case_100" m53
set_directive_bind_op -op mul -impl fabric "case_100" m54
set_directive_bind_op -op mul -impl fabric "case_100" m55
set_directive_bind_op -op mul -impl fabric "case_100" m56
set_directive_bind_op -op mul -impl fabric "case_100" m57
set_directive_bind_op -op mul -impl fabric "case_100" m58
set_directive_bind_op -op mul -impl fabric "case_100" m59
set_directive_bind_op -op mul -impl fabric "case_100" m60
set_directive_bind_op -op mul -impl fabric "case_100" m61
set_directive_bind_op -op mul -impl fabric "case_100" m62
set_directive_bind_op -op mul -impl fabric "case_100" m63
set_directive_bind_op -op mul -impl fabric "case_100" m64
set_directive_bind_op -op mul -impl fabric "case_100" m65
set_directive_bind_op -op mul -impl fabric "case_100" m66
set_directive_bind_op -op mul -impl fabric "case_100" m67
set_directive_bind_op -op mul -impl fabric "case_100" m68
set_directive_bind_op -op mul -impl fabric "case_100" m69
set_directive_bind_op -op mul -impl fabric "case_100" m70
set_directive_bind_op -op mul -impl fabric "case_100" m71
set_directive_bind_op -op mul -impl fabric "case_100" m72
set_directive_bind_op -op mul -impl fabric "case_100" m73
set_directive_bind_op -op mul -impl fabric "case_100" m74
set_directive_bind_op -op mul -impl fabric "case_100" m75
set_directive_bind_op -op mul -impl fabric "case_100" m76
set_directive_bind_op -op mul -impl fabric "case_100" m77
set_directive_bind_op -op mul -impl fabric "case_100" m78
set_directive_bind_op -op mul -impl fabric "case_100" m79
set_directive_bind_op -op mul -impl fabric "case_100" m80
set_directive_bind_op -op mul -impl fabric "case_100" m81
set_directive_bind_op -op mul -impl fabric "case_100" m82
set_directive_bind_op -op mul -impl fabric "case_100" m83
set_directive_bind_op -op mul -impl fabric "case_100" m84
set_directive_bind_op -op mul -impl fabric "case_100" m85
set_directive_bind_op -op mul -impl fabric "case_100" m86
set_directive_bind_op -op mul -impl fabric "case_100" m87
set_directive_bind_op -op mul -impl fabric "case_100" m88
set_directive_bind_op -op mul -impl fabric "case_100" m89
set_directive_bind_op -op mul -impl fabric "case_100" m90
set_directive_bind_op -op mul -impl fabric "case_100" m91
set_directive_bind_op -op mul -impl fabric "case_100" m92
set_directive_bind_op -op mul -impl fabric "case_100" m93
set_directive_bind_op -op mul -impl fabric "case_100" m94
set_directive_bind_op -op mul -impl fabric "case_100" m95
set_directive_bind_op -op mul -impl fabric "case_100" m96
set_directive_bind_op -op mul -impl fabric "case_100" m97
set_directive_bind_op -op mul -impl fabric "case_100" m98

