set_directive_bind_op -op mul -impl fabric "case_8" m7
set_directive_bind_op -op mul -impl fabric "case_8" m8
set_directive_bind_op -op mul -impl fabric "case_8" m9
set_directive_bind_op -op mul -impl fabric "case_8" m10
set_directive_bind_op -op mul -impl fabric "case_8" m11
set_directive_bind_op -op mul -impl fabric "case_8" m12
set_directive_bind_op -op mul -impl fabric "case_8" m13
set_directive_bind_op -op mul -impl fabric "case_8" m14
set_directive_bind_op -op mul -impl fabric "case_8" m15
set_directive_bind_op -op mul -impl fabric "case_8" m16
set_directive_bind_op -op mul -impl fabric "case_8" m17
set_directive_bind_op -op mul -impl fabric "case_8" m18
set_directive_bind_op -op mul -impl fabric "case_8" m19
set_directive_bind_op -op mul -impl fabric "case_8" m20
set_directive_bind_op -op mul -impl fabric "case_8" m21
set_directive_bind_op -op mul -impl fabric "case_8" m22
set_directive_bind_op -op mul -impl fabric "case_8" m23
set_directive_bind_op -op mul -impl fabric "case_8" m24
set_directive_bind_op -op mul -impl fabric "case_8" m25
set_directive_bind_op -op mul -impl fabric "case_8" m26
set_directive_bind_op -op mul -impl fabric "case_8" m27
set_directive_bind_op -op mul -impl fabric "case_8" m28
set_directive_bind_op -op mul -impl fabric "case_8" m29
set_directive_bind_op -op mul -impl fabric "case_8" m30
set_directive_bind_op -op mul -impl fabric "case_8" m31
set_directive_bind_op -op mul -impl fabric "case_8" m32
set_directive_bind_op -op mul -impl fabric "case_8" m33
set_directive_bind_op -op mul -impl fabric "case_8" m34
set_directive_bind_op -op mul -impl fabric "case_8" m35
set_directive_bind_op -op mul -impl fabric "case_8" m36
set_directive_bind_op -op mul -impl fabric "case_8" m37
set_directive_bind_op -op mul -impl fabric "case_8" m38
set_directive_bind_op -op mul -impl fabric "case_8" m39
set_directive_bind_op -op mul -impl fabric "case_8" m40
set_directive_bind_op -op mul -impl fabric "case_8" m41
set_directive_bind_op -op mul -impl fabric "case_8" m42
set_directive_bind_op -op mul -impl fabric "case_8" m43
set_directive_bind_op -op mul -impl fabric "case_8" m44
set_directive_bind_op -op mul -impl fabric "case_8" m45

