set_directive_bind_op -op mul -impl fabric "case_41" m20
set_directive_bind_op -op mul -impl fabric "case_41" m21
set_directive_bind_op -op mul -impl fabric "case_41" m22
set_directive_bind_op -op mul -impl fabric "case_41" m23
set_directive_bind_op -op mul -impl fabric "case_41" m24
set_directive_bind_op -op mul -impl fabric "case_41" m25
set_directive_bind_op -op mul -impl fabric "case_41" m26
set_directive_bind_op -op mul -impl fabric "case_41" m27
set_directive_bind_op -op mul -impl fabric "case_41" m28
set_directive_bind_op -op mul -impl fabric "case_41" m29
set_directive_bind_op -op mul -impl fabric "case_41" m30
set_directive_bind_op -op mul -impl fabric "case_41" m31
set_directive_bind_op -op mul -impl fabric "case_41" m32
set_directive_bind_op -op mul -impl fabric "case_41" m33
set_directive_bind_op -op mul -impl fabric "case_41" m34
set_directive_bind_op -op mul -impl fabric "case_41" m35
set_directive_bind_op -op mul -impl fabric "case_41" m36
set_directive_bind_op -op mul -impl fabric "case_41" m37
set_directive_bind_op -op mul -impl fabric "case_41" m38
set_directive_bind_op -op mul -impl fabric "case_41" m39
set_directive_bind_op -op mul -impl fabric "case_41" m40
set_directive_bind_op -op mul -impl fabric "case_41" m41
set_directive_bind_op -op mul -impl fabric "case_41" m42
set_directive_bind_op -op mul -impl fabric "case_41" m43
set_directive_bind_op -op mul -impl fabric "case_41" m44
set_directive_bind_op -op mul -impl fabric "case_41" m45
set_directive_bind_op -op mul -impl fabric "case_41" m46
set_directive_bind_op -op mul -impl fabric "case_41" m47
set_directive_bind_op -op mul -impl fabric "case_41" m48
set_directive_bind_op -op mul -impl fabric "case_41" m49
set_directive_bind_op -op mul -impl fabric "case_41" m50
set_directive_bind_op -op mul -impl fabric "case_41" m51
set_directive_bind_op -op mul -impl fabric "case_41" m52
set_directive_bind_op -op mul -impl fabric "case_41" m53
set_directive_bind_op -op mul -impl fabric "case_41" m54
set_directive_bind_op -op mul -impl fabric "case_41" m55
set_directive_bind_op -op mul -impl fabric "case_41" m56
set_directive_bind_op -op mul -impl fabric "case_41" m57
set_directive_bind_op -op mul -impl fabric "case_41" m58
set_directive_bind_op -op mul -impl fabric "case_41" m59
set_directive_bind_op -op mul -impl fabric "case_41" m60
set_directive_bind_op -op mul -impl fabric "case_41" m61
set_directive_bind_op -op mul -impl fabric "case_41" m62
set_directive_bind_op -op mul -impl fabric "case_41" m63
set_directive_bind_op -op mul -impl fabric "case_41" m64
set_directive_bind_op -op mul -impl fabric "case_41" m65
set_directive_bind_op -op mul -impl fabric "case_41" m66
set_directive_bind_op -op mul -impl fabric "case_41" m67
set_directive_bind_op -op mul -impl fabric "case_41" m68
set_directive_bind_op -op mul -impl fabric "case_41" m69
set_directive_bind_op -op mul -impl fabric "case_41" m70
set_directive_bind_op -op mul -impl fabric "case_41" m71
set_directive_bind_op -op mul -impl fabric "case_41" m72
set_directive_bind_op -op mul -impl fabric "case_41" m73
set_directive_bind_op -op mul -impl fabric "case_41" m74
set_directive_bind_op -op mul -impl fabric "case_41" m75
set_directive_bind_op -op mul -impl fabric "case_41" m76
set_directive_bind_op -op mul -impl fabric "case_41" m77
set_directive_bind_op -op mul -impl fabric "case_41" m78
set_directive_bind_op -op mul -impl fabric "case_41" m79

