set_directive_bind_op -op mul -impl fabric "case_6" m12
set_directive_bind_op -op mul -impl fabric "case_6" m13
set_directive_bind_op -op mul -impl fabric "case_6" m14
set_directive_bind_op -op mul -impl fabric "case_6" m15
set_directive_bind_op -op mul -impl fabric "case_6" m16
set_directive_bind_op -op mul -impl fabric "case_6" m17
set_directive_bind_op -op mul -impl fabric "case_6" m18
set_directive_bind_op -op mul -impl fabric "case_6" m19
set_directive_bind_op -op mul -impl fabric "case_6" m20
set_directive_bind_op -op mul -impl fabric "case_6" m21
set_directive_bind_op -op mul -impl fabric "case_6" m22
set_directive_bind_op -op mul -impl fabric "case_6" m23
set_directive_bind_op -op mul -impl fabric "case_6" m24
set_directive_bind_op -op mul -impl fabric "case_6" m25
set_directive_bind_op -op mul -impl fabric "case_6" m26
set_directive_bind_op -op mul -impl fabric "case_6" m27
set_directive_bind_op -op mul -impl fabric "case_6" m28
set_directive_bind_op -op mul -impl fabric "case_6" m29
set_directive_bind_op -op mul -impl fabric "case_6" m30
set_directive_bind_op -op mul -impl fabric "case_6" m31
set_directive_bind_op -op mul -impl fabric "case_6" m32
set_directive_bind_op -op mul -impl fabric "case_6" m33
set_directive_bind_op -op mul -impl fabric "case_6" m34
set_directive_bind_op -op mul -impl fabric "case_6" m35
set_directive_bind_op -op mul -impl fabric "case_6" m36
set_directive_bind_op -op mul -impl fabric "case_6" m37
set_directive_bind_op -op mul -impl fabric "case_6" m38
set_directive_bind_op -op mul -impl fabric "case_6" m39
set_directive_bind_op -op mul -impl fabric "case_6" m40
set_directive_bind_op -op mul -impl fabric "case_6" m41
set_directive_bind_op -op mul -impl fabric "case_6" m42
set_directive_bind_op -op mul -impl fabric "case_6" m43
set_directive_bind_op -op mul -impl fabric "case_6" m44
set_directive_bind_op -op mul -impl fabric "case_6" m45
set_directive_bind_op -op mul -impl fabric "case_6" m46
set_directive_bind_op -op mul -impl fabric "case_6" m47
set_directive_bind_op -op mul -impl fabric "case_6" m48
set_directive_bind_op -op mul -impl fabric "case_6" m49
set_directive_bind_op -op mul -impl fabric "case_6" m50
set_directive_bind_op -op mul -impl fabric "case_6" m51
set_directive_bind_op -op mul -impl fabric "case_6" m52
set_directive_bind_op -op mul -impl fabric "case_6" m53
set_directive_bind_op -op mul -impl fabric "case_6" m54
set_directive_bind_op -op mul -impl fabric "case_6" m55
set_directive_bind_op -op mul -impl fabric "case_6" m56
set_directive_bind_op -op mul -impl fabric "case_6" m57
set_directive_bind_op -op mul -impl fabric "case_6" m58
set_directive_bind_op -op mul -impl fabric "case_6" m59
set_directive_bind_op -op mul -impl fabric "case_6" m60
set_directive_bind_op -op mul -impl fabric "case_6" m61
set_directive_bind_op -op mul -impl fabric "case_6" m62
set_directive_bind_op -op mul -impl fabric "case_6" m63
set_directive_bind_op -op mul -impl fabric "case_6" m64
set_directive_bind_op -op mul -impl fabric "case_6" m65
set_directive_bind_op -op mul -impl fabric "case_6" m66
set_directive_bind_op -op mul -impl fabric "case_6" m67
set_directive_bind_op -op mul -impl fabric "case_6" m68
set_directive_bind_op -op mul -impl fabric "case_6" m69
set_directive_bind_op -op mul -impl fabric "case_6" m70
set_directive_bind_op -op mul -impl fabric "case_6" m71
set_directive_bind_op -op mul -impl fabric "case_6" m72
set_directive_bind_op -op mul -impl fabric "case_6" m73
set_directive_bind_op -op mul -impl fabric "case_6" m74

